"use client";

import React, { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "ml" | "hi" | "ta" | "te" | "kn";

type Translations = {
  [key in Language]: {
    [key: string]: string;
  };
};

const translations: Translations = {
  en: {
    "nav.connect": "Setbin Connect",
    "nav.repair": "Setbin Repair",
    "nav.schemic": "Schemic AI",
    "nav.connectBtn": "Connect with us",
    "nav.connectBtnMobile": "Connect",

    "hero.stage1.title": "SETBIN",
    "hero.stage1.subtitle": "The Digital Backbone of the Smartphone Service Industry",
    "hero.stage2.title": "An Industry Worth <span class='text-[#00F0FF]'>Billions</span><br/>Still Running Without <span class='text-[#00F0FF]'>Infrastructure</span>",
    "hero.stage2.subtext": "Technicians. Parts. Operations. Intelligence.<br/>All disconnected.",
    "hero.stage3.title": "From <span class='text-[#00F0FF]'>Fragmentation</span><br/>to <span class='text-[#00F0FF]'>Structure</span>",
    "hero.stage3.subtext": "What if everything worked together?",
    "hero.stage4.title": "SETBIN <span class='text-[#00F0FF]'>connects the ecosystem</span>",
    "hero.stage4.subtext": "Spare sourcing<br/>Service operations<br/>Technical intelligence<br/>All in one platform.",
    "hero.stage5.title": "<span class='text-[#00F0FF]'>Connect.</span> <span class='text-[#ffffff]'>Operate.</span> <span class='text-[#00F0FF]'>Diagnose.</span>",
    "hero.stage5.subtext": "A complete infrastructure<br/>for the modern repair industry.",
    "hero.stage6.title": "SETBIN",
    "hero.stage6.subtext": "Infrastructure for India's Smartphone Service Industry",
    "hero.stage7.title": "Powering the <span class='text-[#00F0FF]'>Future</span> of Mobile Service",
    "hero.stage7.btn": "Explore the Platform",

    "platform.chip": "The Platform",
    "platform.title": "Powering the Next Generation of Service",
    "platform.desc": "A comprehensive ecosystem designed specifically for the smartphone servicing industry.",
    "platform.pillar1.title": "SETBIN CONNECT",
    "platform.pillar1.subtitle": "Verified spare parts marketplace",
    "platform.pillar1.body": "Connect with trusted suppliers. Source genuine parts faster with full transparency.",
    "platform.pillar2.title": "SETBIN REPAIR",
    "platform.pillar2.subtitle": "Service center operating system",
    "platform.pillar2.body": "Manage jobs, track repairs, control inventory and streamline your entire workflow.",
    "platform.pillar3.title": "SCHEMIC AI",
    "platform.pillar3.subtitle": "AI-powered diagnostic intelligence",
    "platform.pillar3.body": "Identify faults using schematic-driven logic instead of trial-and-error repairs.",
    "platform.viewMore": "View More →",
    
    "pillars.chip": "The Pillars of Innovation",
    "pillars.title": "ENGINEERING THE <br/>FUTURE OF REPAIR.",
    "pillars.desc": "We are building a unified ecosystem where supply chains, service centers, and AI diagnostics converge into a single, seamless workflow.",
    "pillars.footer": "Built for Scale • Powered by Intelligence • Trusted by Pros",
    "pillars.connect.subtitle": "ECOSYSTEM",
    "pillars.repair.subtitle": "INFRASTRUCTURE",
    "pillars.schemic.subtitle": "INTELLIGENCE",

    "connect.chip": "SETBIN CONNECT",
    "connect.title": "India's Largest B2B Network for Electronics",
    "connect.desc": "Join India's largest specialized network connecting parts suppliers, tool manufacturers, and service centers.",
    "connect.features.suppliers": "Direct Supplier Access",
    "connect.features.tools": "Premium Tool Sourcing",
    "connect.features.wholesale": "Wholesale Pricing",
    "connect.btn": "Join the Network",

    "connect.story.chip": "SETBIN CONNECT",
    "connect.story.s1.title": "India's B2B Network for Mobile Service",
    "connect.story.s1.desc": "A verified platform connecting technicians, service centers, and spare parts suppliers into one structured ecosystem.",
    "connect.story.s2.tag": "The Old Way",
    "connect.story.s2.title": "Sourcing is Still Manual & Chaotic",
    "connect.story.s2.p1": "No real-time availability",
    "connect.story.s2.p2": "No price clarity",
    "connect.story.s2.p3": "High risk of counterfeit parts",
    "connect.story.s2.p4": "Endless calls and messages",
    "connect.story.s3.tag": "The Solution",
    "connect.story.s3.title": "From Chaos to Structure",
    "connect.story.s3.desc": "Search, compare, and source verified parts from trusted suppliers — instantly.",
    "connect.story.s4.title": "Direct Supplier Access",
    "connect.story.s4.desc": "Connect directly with verified wholesalers across India without delays. No middlemen, no markup.",
    "connect.story.s5.title": "Real-Time Inventory",
    "connect.story.s5.desc": "Know exactly what's available before you order. Live stock indicators eliminate uncertainty and backorder delays.",
    "connect.story.s5.feed": "Live Stock Feed",
    "connect.story.s5.stock": "In Stock",
    "connect.story.s5.p1": "iPhone 13 Pro Screen",
    "connect.story.s5.p2": "Samsung S22 Battery",
    "connect.story.s5.p3": "Type-C Port IC",
    "connect.story.s6.title": "True Wholesale Pricing",
    "connect.story.s6.desc": "Access transparent B2B pricing immediately. Compare rates across verified suppliers without retail competition driving up your costs.",
    "connect.story.s6.retail": "Retail Avg",
    "connect.story.s7.title": "Verified Genuine Parts",
    "connect.story.s7.desc": "Reduce the risk of counterfeit components. Our supplier network is strictly vetted to ensure OEM and high-quality aftermarket parts.",
    "connect.story.s8.title": "From Hours to Minutes",
    "connect.story.s8.desc": "What once took hours of calls and uncertainty now takes seconds on India's verified platform.",
    "connect.story.s8.btn": "Explore Connect Ecosystem",

    // SaaS Showcase Rebrand
    "pro.showcase.heading": "One System for Your Entire Service Business",
    "pro.showcase.subheading": "SETBIN REPAIR",
    "pro.showcase.desc": "From job intake to billing, inventory to financial tracking — SETBIN unifies every operation into one seamless workflow for mobile service centers.",
    "pro.showcase.cta.demo": "Get a Demo",
    "pro.showcase.cta.free": "Start Free Trial",
    "pro.showcase.nav.daybook": "DayBook",
    "pro.showcase.nav.billing": "Billing",
    "pro.showcase.nav.inventory": "Inventory",
    "pro.showcase.nav.reports": "Reports",
    "pro.showcase.nav.dues": "Dues",
    "pro.showcase.nav.exp": "Expenses",
    "pro.showcase.card.rev.title": "REVENUE",
    "pro.showcase.card.rev.amt": "$198.5M",
    "pro.showcase.card.due.title": "PENDING DUES",
    "pro.showcase.card.due.amt": "$15.3M",
    "pro.showcase.card.rules.title": "SERVICE RULES",
    "pro.showcase.card.rules.r1": "RATABLE",
    "pro.showcase.card.rules.r2": "POINT_IN_TIME",
    "pro.showcase.card.rules.r3": "PROPORTIONAL",
    
    "pro.chip": "SETBIN REPAIR",
    "pro.features.repair": "Repair Tracking",
    "pro.features.inventory": "Inventory Management",
    "pro.features.customer": "Customer Communication",
    "pro.btn": "Start Managing",

    "ai.chip": "SCHEMIC AI",
    "ai.title": "Next-Gen Board Level Diagnostics",
    "ai.desc": "Leverage advanced artificial intelligence to analyze complex motherboard schematics and pinpoint hardware faults with unprecedented accuracy.",
    "ai.features.analysis": "Instant Schematic Analysis",
    "ai.features.faults": "Fault Localization",
    "ai.features.solutions": "Repair Solutions Database",
    "ai.btn": "Try Schemic AI",

    "network.chip": "National Network",
    "network.title": "Trusted by Experts across India",
    "network.desc": "Join thousands of service professionals and businesses that rely on SETBIN for their daily operations.",

    "contact.chip": "Get in Touch",
    "contact.title": "Let's Build the Future Together",
    "contact.desc": "Ready to transform your service business? Our team is here to help you get started.",
    "contact.info.title": "Contact Information",
    "contact.info.desc": "Reach out to us through any of these channels.",
    "contact.info.email": "Email Us",
    "contact.info.phone": "Call Us",
    "contact.info.address": "Visit Us",
    "contact.form.name": "Full Name",
    "contact.form.name_placeholder": "John Doe",
    "contact.form.email": "Email Address",
    "contact.form.email_placeholder": "john@example.com",
    "contact.form.subject": "Subject",
    "contact.form.subject_placeholder": "How can we help?",
    "contact.form.message": "Message",
    "contact.form.message_placeholder": "Tell us about your needs...",
    "contact.form.submit": "Send Message",

    "cta.title": "Ready to Revolutionize Your Service Business?",
    "cta.desc": "Join thousands of professionals already using SETBIN to streamline their operations.",
    "cta.btn.start": "Get Started Today",
    "cta.btn.contact": "Contact Sales",

    "contact.card.office.title": "Office Location",
    "contact.card.office.value": "SETTINGS Service Center Ernakulam",
    "contact.card.office.sub": "Kochi, Kerala — India",
    "contact.card.direct.title": "Direct Contact",
    "contact.card.direct.sub": "Mon–Sat · 10AM – 7PM IST",
    "contact.card.email.title": "Enterprise Email",
    "contact.card.email.sub": "Response within 24 hours",
    "contact.send_message": "Send a Message",
    "contact.map.label": "SETBIN // ERNAKULAM",
    "contact.get_directions": "Get Directions",

    "network.city.delhi": "Delhi",
    "network.city.mumbai": "Mumbai",
    "network.city.bangalore": "Bangalore",
    "network.city.hyderabad": "Hyderabad",
    "network.city.chennai": "Chennai",
    "network.city.kolkata": "Kolkata",
    "network.city.ahmedabad": "Ahmedabad",
    "network.city.kochi": "Kochi",

    "platform.card1.title": "Unified Management Ecosystem",
    "platform.card1.desc": "Connect every aspect of your service business in one place.",
    "platform.card2.title": "AI-Powered Diagnostics",
    "platform.card2.desc": "Advanced schematic analysis for precise troubleshooting.",
    "platform.card3.title": "India's Largest Supply Chain",
    "platform.card3.desc": "Access high-quality parts and tools from the country's best suppliers.",

    "pro.dashboard.title": "One System for Your <br/> Entire Service Business",
    "pro.dashboard.desc": "From job intake to billing, inventory to financial tracking — SETBIN unifies every operation into one seamless workflow for mobile service centers.",
    "pro.btn.cta": "Start Your Automation",
    "pro.nav.overview": "OVERVIEW",
    "pro.nav.daybook": "DAYBOOK",
    "pro.nav.services": "SERVICES",
    "pro.nav.billing": "BILLING",
    "pro.nav.expenses": "EXPENSES",
    "pro.nav.dues": "DUES",
    "pro.nav.inventory": "INVENTORY",
    "pro.nav.staff": "STAFF",
    "pro.nav.customers": "CUSTOMERS",
    "pro.nav.vendors": "VENDORS",
    "pro.nav.reports": "REPORTS",

    "pro.card.revenue.title": "DAILY REVENUE",
    "pro.card.revenue.detail": "+15% VS LAST WEEK",
    "pro.card.pending.title": "PENDING JOBS",
    "pro.card.pending.detail": "4 URGENT",
    "pro.card.cash_flow.title": "CASH FLOW",
    "pro.card.cash_flow.detail": "LAST SYNC 2S",
    "pro.card.transactions.title": "TRANSACTIONS",
    "pro.card.transactions.detail": "UPI DOMINANT",
    "pro.card.avg_repair.title": "AVG REPAIR",
    "pro.card.avg_repair.detail": "-5M FROM TARGET",
    "pro.card.ready_jobs.title": "READY JOBS",
    "pro.card.ready_jobs.detail": "WAITING DELIVERY",
    "pro.card.outstanding.title": "OUTSTANDING",
    "pro.card.outstanding.detail": "5 CUSTOMERS",
    "pro.card.inv_match.title": "INV_MATCH",
    "pro.card.inv_match.detail": "GST VERIFIED",
    "pro.card.exp_total.title": "EXP_TOTAL",
    "pro.card.exp_total.detail": "MONTHLY OPEX",
    "pro.card.rent_paid.title": "RENT_PAID",
    "pro.card.rent_paid.detail": "DUE IN 28D",
    "pro.card.receivables.title": "RECEIVABLES",
    "pro.card.receivables.detail": "4 PENDING",
    "pro.card.payables.title": "PAYABLES",
    "pro.card.payables.detail": "DUE IN 3D",
    "pro.card.stock_val.title": "STOCK_VAL",
    "pro.card.stock_val.detail": "450 SKUS",
    "pro.card.low_stock.title": "LOW_STOCK",
    "pro.card.low_stock.detail": "ALERT_ACTIVE",
    "pro.card.efficiency.title": "EFFICIENCY",
    "pro.card.efficiency.detail": "TEAM AVG",
    "pro.card.active_staff.title": "ACTIVE_STAFF",
    "pro.card.active_staff.detail": "4 ON BENCH",
    "pro.card.customers.title": "CUSTOMERS",
    "pro.card.customers.detail": "RECURRING",
    "pro.card.avg_ltv.title": "AVG_LTV",
    "pro.card.avg_ltv.detail": "UP 5%",
    "pro.card.vendors.title": "VENDORS",
    "pro.card.vendors.detail": "3 ACTIVE PO",
    "pro.card.lead_time.title": "LEAD_TIME",
    "pro.card.lead_time.detail": "TOP TIER",
    "pro.card.analytics.title": "ANALYTICS",
    "pro.card.analytics.detail": "REAL-TIME",
    "pro.card.uptime.title": "Uptime",
    "pro.card.uptime.detail": "GLOBAL_CLUSTER",

    "ai.card1.title": "AI-Powered Fault Diagnosis",
    "ai.card1.desc": "Identify device issues instantly using AI-driven analysis of symptoms, behavior, and historical repair data.",
    "ai.card2.title": "Image-Based Component Detection",
    "ai.card2.desc": "Upload motherboard or PCB images and automatically detect components, damaged areas, and key circuit zones.",
    "ai.card3.title": "Smart Repair Guidance",
    "ai.card3.desc": "Get step-by-step repair instructions with recommended tools, precautions, and optimized repair workflows.",
    "ai.card4.title": "AI-Powered Testing",
    "ai.card4.desc": "Know exactly where to test, what values to check, and which components are likely to fail.",
    "ai.card5.title": "Knowledge Engine",
    "ai.card5.desc": "Continuously learns from past repairs, technician inputs, and common faults to improve accuracy over time.",
    "ai.diagnosis.complete": "Diagnosis Complete",
    "ai.diagnosis.sub": "Schematic mapped. Solution ready to print.",

    "footer.desc": "India's first integrated platform for electronics repair shops — connecting technicians, parts suppliers, and AI diagnostics in one ecosystem.",
    "footer.address": "SETBIN Connect Pvt Ltd<br />Kochi, Ernakulam, Kerala — India",
    "footer.platform": "Platform",
    "footer.hardware": "Hardware",
    "footer.software": "Workshop Software",
    "footer.network": "Connect Network",
    "footer.experience": "Experience",
    "footer.solutions": "Solutions",
    "footer.company": "Company",
    "footer.links.diagnostics": "Motherboard Diagnostics",
    "footer.links.repairs": "IC Level Repairs",
    "footer.links.sourcing": "Parts Sourcing",
    "footer.links.erp": "Service Center ERP",
    "footer.links.jobs": "Job Management",
    "footer.links.customers": "Customer Management",
    "footer.links.inventory": "Inventory Sync",
    "footer.links.billing": "Billing & Invoicing",
    "footer.links.staff": "Staff & Roles",
    "footer.links.vendors": "Vendor Accounts",
    "footer.links.analytics": "Reports & Analytics",
    "footer.links.suppliers": "Verified Suppliers",
    "footer.links.distributors": "Verified Distributors",
    "footer.links.logistics": "Logistics Partners",
    "footer.links.dropship": "Drop-Shipping",
    "footer.links.hub": "Technician Hub",
    "footer.links.marketplace": "B2B Marketplace",
    "footer.links.portal": "Customer Portal",
    "footer.links.dashboard": "Technician Dashboard",
    "footer.links.freelance": "For Freelance Techs",
    "footer.links.centers": "For Service Centers",
    "footer.links.chains": "For Enterprise Chains",
    "footer.links.about": "About SETBIN",
    "footer.links.careers": "Careers",
    "footer.links.partners": "Partner Program",
    "footer.links.privacy": "Privacy Policy",
    "footer.links.terms": "Terms of Service",
    "footer.links.disclaimer": "Disclaimer",
    "footer.rights": "All rights reserved."
  },
  ml: {
    "nav.connect": "setbin connect",
    "nav.repair": "setbin repair",
    "nav.schemic": "schemic ai",
    "nav.connectBtn": "ഞങ്ങളുമായി ബന്ധപ്പെടുക",
    "nav.connectBtnMobile": "ബന്ധപ്പെടുക",

    "hero.stage1.title": "SETBIN",
    "hero.stage1.subtitle": "സ്മാർട്ട്‌ഫോൺ സേവന വ്യവസായത്തിന്റെ ഡിജിറ്റൽ നട്ടെല്ല്.",
    "hero.stage2.title": "അടിസ്ഥാന സൗകര്യങ്ങളില്ലാതെ പ്രവർത്തിക്കുന്ന<br/><span class='text-[#00F0FF]'>കോടിക്കണക്കിന് ഡോളറിന്റെ</span> വ്യവസായം.",
    "hero.stage2.subtext": "ടെക്നീഷ്യൻമാർ. പാർട്സ്. പ്രവർത്തനങ്ങൾ.<br/>എല്ലാം വിച്ഛേദിക്കപ്പെട്ടിരിക്കുന്നു.",
    "hero.stage3.title": "ഛിന്നഭിന്നതയിൽ നിന്ന്<br/><span class='text-[#00F0FF]'>ഉറപ്പുള്ള ഒരു ഘടനയിലേക്ക്</span>.",
    "hero.stage3.subtext": "എല്ലാം ഒരുമിച്ച് പ്രവർത്തിച്ചാലോ?",
    "hero.stage4.title": "ഇക്കോസിസ്റ്റത്തെ SETBIN <span class='text-[#00F0FF]'>ബന്ധിപ്പിക്കുന്നു</span>.",
    "hero.stage4.subtext": "സ്പെയർ പാർട്സ്, സേവനങ്ങൾ, വിവരങ്ങൾ<br/>എല്ലാം ഒരൊറ്റ പ്ലാറ്റ്‌ഫോമിൽ.",
    "hero.stage5.title": "<span class='text-[#00F0FF]'>ബന്ധിപ്പിക്കുക.</span> <span class='text-[#ffffff]'>പ്രവർത്തിപ്പിക്കുക.</span> <span class='text-[#00F0FF]'>കണ്ടെത്തുക.</span>",
    "hero.stage5.subtext": "ആധുനിക റിപ്പയർ വ്യവസായത്തിനായുള്ള<br/>പൂർണ്ണമായ അടിസ്ഥാന സൗകര്യങ്ങൾ.",
    "hero.stage6.title": "SETBIN",
    "hero.stage6.subtext": "ഇന്ത്യയിലെ സ്മാർട്ട് ഫോൺ സർവീസ് വ്യവസായത്തിനുള്ള അടിസ്ഥാന സൗകര്യങ്ങൾ.",
    "hero.stage7.title": "മൊബൈൽ സേവനത്തിന്റെ <span class='text-[#00F0FF]'>ഭാവി</span> ശാക്തീകരിക്കുന്നു.",
    "hero.stage7.btn": "പ്ലാറ്റ്ഫോം പര്യവേക്ഷണം ചെയ്യുക",

    "platform.chip": "പ്ലാറ്റ്ഫോം",
    "platform.title": "അടുത്ത തലമുറയിലെ സേവനങ്ങൾ ശാക്തീകരിക്കുന്നു",
    "platform.desc": "സ്മാർട്ട്ഫോൺ സേവന വ്യവസായത്തിന് മാത്രമായി രൂപകൽപ്പന ചെയ്ത സമഗ്രമായ ഒരു ഇക്കോസിസ്റ്റം.",
    "platform.card1.title": "ഏകീകൃത മാനേജ്മെന്റ് ഇക്കോസിസ്റ്റം",
    "platform.card1.desc": "നിങ്ങളുടെ സേവന ബിസിനസ്സിന്റെ എല്ലാ വശങ്ങളും ഒരിടത്ത് ബന്ധിപ്പിക്കുക.",
    "platform.card2.title": "AI പവർ ഡയഗ്നോസ്റ്റിക്സ്",
    "platform.card2.desc": "കൃത്യമായ പ്രശ്നപരിഹാരത്തിനായി നൂതന സ്കീമാറ്റിക് വിശകലനം.",
    "platform.card3.title": "ഇന്ത്യയിലെ വലിയ സപ്ലൈ ചെയിൻ",
    "platform.card3.desc": "രാജ്യത്തെ മികച്ച വിതരണക്കാരിൽ നിന്ന് ഉയർന്ന നിലവാരമുള്ള ഭാഗങ്ങളും ഉപകരണങ്ങളും ആക്സസ് ചെയ്യുക.",

    "pillars.chip": "നവീകരണത്തിന്റെ നെടുംതൂണുകൾ",
    "pillars.title": "റിപ്പയറിംഗിന്റെ ഭാവി <br/>ഞങ്ങൾ നിർമ്മിക്കുന്നു.",
    "pillars.desc": "സപ്ലൈ ചെയിനുകൾ, സർവീസ് സെന്ററുകൾ, AI ഡയഗ്നോസ്റ്റിക്സ് എന്നിവയെ ഒരൊറ്റ പ്ലാറ്റ്‌ഫോമിൽ ഞങ്ങൾ എത്തിക്കുന്നു.",
    "pillars.footer": "സ്കെയിലിനായി നിർമ്മിച്ചത് • ഇന്റലിജൻസ് കരുത്ത് • വിദഗ്ദ്ധർ വിശ്വസിക്കുന്നത്",
    "pillars.connect.subtitle": "ഇക്കോസിസ്റ്റം",
    "pillars.repair.subtitle": "ഇൻഫ്രാസ്ട്രക്ചർ",
    "pillars.schemic.subtitle": "ഇന്റലിജൻസ്",

    "connect.chip": "SETBIN CONNECT",
    "connect.title": "ഇലക്ട്രോണിക്സിനായുള്ള ഇന്ത്യയിലെ ബി2ബി നെറ്റ്‌വർക്കിംഗ്",
    "connect.desc": "പാർട്സ് സപ്ലയർമാരുമായും സർവീസ് സെന്ററുകളുമായും നേരിട്ട് ബന്ധപ്പെടുക.",
    "pro.showcase.heading": "നിങ്ങളുടെ മുഴുവൻ സർവീസ് ബിസിനസ്സും ഒരു സിസ്റ്റത്തിൽ",
    "pro.showcase.subheading": "സെറ്റ്ബിൻ റിപ്പയർ",
    "pro.showcase.desc": "ജോബ് ഇൻടേക്ക് മുതൽ ബില്ലിംഗ് വരെയും, ഇൻവെന്ററി മുതൽ ഫിനാൻഷ്യൽ ട്രാക്കിംഗ് വരെയും — മൊബൈൽ സർവീസ് സെന്ററുകൾക്കായി സെറ്റ്ബിൻ എല്ലാ പ്രവർത്തനങ്ങളെയും ഒരു തടസ്സമില്ലാത്ത വർക്ക്ഫ്ലോയിലേക്ക് കൊണ്ടുവരുന്നു.",
    "pro.showcase.cta.demo": "ഒരു ഡെമോ നേടുക",
    "pro.showcase.cta.free": "സൗജന്യ ട്രയൽ തുടങ്ങൂ",
    "pro.showcase.nav.daybook": "ഡേബുക്ക്",
    "pro.showcase.nav.billing": "ബില്ലിംഗ്",
    "pro.showcase.nav.inventory": "ഇൻവെന്ററി",
    "pro.showcase.nav.reports": "റിപ്പോർട്ടുകൾ",
    "pro.showcase.nav.dues": "بقായകൾ",
    "pro.showcase.nav.exp": "ചെലവുകൾ",
    "pro.showcase.card.rev.title": "വരുമാനം",
    "pro.showcase.card.rev.amt": "$198.5M",
    "pro.showcase.card.due.title": "بقായകൾ",
    "pro.showcase.card.due.amt": "$15.3M",
    "pro.showcase.card.rules.title": "സർവീസ് റൂൾസ്",
    "pro.showcase.card.rules.r1": "റേറ്റബിൾ",
    "pro.showcase.card.rules.r2": "പോയിന്റ്_ഇൻ_ടൈം",
    "pro.showcase.card.rules.r3": "പ്രൊപ്പോർഷണൽ",
    
    "pro.chip": "SETBIN REPAIR",
    "pro.features.repair": "റിപ്പയർ ട്രാക്കിംഗ്",
    "pro.features.inventory": "ഇൻവെന്ററി മാനേജ്മെന്റ്",
    "pro.features.customer": "ഉപഭോക്തൃ ആശയവിനിമയം",
    "pro.btn": "മാനേജിംഗ് ആരംഭിക്കുക",

    "ai.chip": "SCHEMIC AI",
    "ai.title": "നെക്സ്റ്റ്-ജെൻ ബോർഡ് ലെവൽ ഡയഗ്നോസ്റ്റിക്സ്",
    "ai.desc": "സങ്കീർണ്ണമായ മദർബോർഡ് സ്കീമാറ്റിക്സ് വിശകലനം ചെയ്യുന്നതിനും ഹാർഡ്‌വെയർ തകരാറുകൾ മുൻപില്ലാത്തവിധം കൃത്യതയോടെ കണ്ടെത്തുന്നതിനും നൂതന കൃത്രിമബുദ്ധി പ്രയോജനപ്പെടുത്തുക.",
    "ai.features.analysis": "തൽക്ഷണ സ്കീമാറ്റിക് അനാലിസിസ്",
    "ai.features.faults": "തകരാറുകൾ കണ്ടെത്തൽ",
    "ai.features.solutions": "റിപ്പയർ സൊല്യൂഷനുകൾ ഡാറ്റാബേസ്",
    "ai.btn": "Schemic AI പരീക്ഷിക്കുക",

    "network.chip": "ആഗോള നെറ്റ്‌വർക്ക്",
    "network.title": "ലോകമെമ്പാടുമുള്ള വിദഗ്ദ്ധർ വിശ്വസിക്കുന്നത്",
    "network.desc": "തങ്ങളുടെ ദൈനംദിന പ്രവർത്തനങ്ങൾക്കായി ഓൺലൈനിലൂടെ വരുന്ന ആയിരക്കണക്കിന് സേവന പ്രൊഫഷണലുകൾക്കും ബിസിനസുകൾക്കും ഒപ്പം ചേരുക.",

    "contact.chip": "ബന്ധപ്പെടുക",
    "contact.title": "നമുക്ക് ഒരുമിച്ച് ഭാവി കെട്ടിപ്പടുക്കാം",
    "contact.desc": "നിങ്ങളുടെ സേവന ബിസിനസ്സിൽ മാറ്റം വരുത്താൻ തയ്യാറാണോ? നിങ്ങളെ സഹായിക്കാൻ ഞങ്ങളുടെ ടീം ഇവിടെയുണ്ട്.",
    "contact.info.title": "ബന്ധപ്പെടാനുള്ള വിവരങ്ങൾ",
    "contact.info.desc": "ഈ മാർഗ്ഗങ്ങളിലൂടെ ഞങ്ങളെ ബന്ധപ്പെടാം.",
    "contact.info.email": "ഇമെയിൽ ചെയ്യുക",
    "contact.info.phone": "വിളിക്കുക",
    "contact.info.address": "സന്ദർശിക്കുക",
    "contact.form.name": "മുഴുവൻ പേര്",
    "contact.form.name_placeholder": "ജോൺ ഡോ",
    "contact.form.email": "ഇമെയിൽ വിലാസം",
    "contact.form.email_placeholder": "john@example.com",
    "contact.form.subject": "വിഷയം",
    "contact.form.subject_placeholder": "ഞങ്ങൾക്ക് എങ്ങനെ സഹായിക്കാനാകും?",
    "contact.form.message": "സന്ദേശം",
    "contact.form.message_placeholder": "നിങ്ങളുടെ ആവശ്യങ്ങളെക്കുറിച്ച് ഞങ്ങളോട് പറയുക...",
    "contact.form.submit": "സന്ദേശം അയക്കുക",

    "cta.title": "നിങ്ങളുടെ സർവീസ് ബിസിനസ്സിൽ വിപ്ലവം സൃഷ്ടിക്കാൻ തയ്യാറാണോ?",
    "cta.desc": "തങ്ങളുടെ പ്രവർത്തനങ്ങൾ കാര്യക്ഷമമാക്കാൻ ഇതിനകം SETBIN ഉപയോഗിക്കുന്ന ആയിരക്കണക്കിന് പ്രൊഫഷണലുകൾക്കൊപ്പം ചേരുക.",
    "cta.btn.start": "ഇന്നുതന്നെ ആരംഭിക്കുക",
    "cta.btn.contact": "സെയിൽസുമായി ബന്ധപ്പെടുക",

    "connect.features.suppliers": "നേരിട്ടുള്ള സപ്ലയർ ആക്സസ്",
    "connect.features.tools": "പ്രീമിയം ടൂൾ സോഴ്സിങ്",
    "connect.features.wholesale": "ഹോൾസെയിൽ വില",
    "connect.btn": "നെറ്റ്‌വർക്കിൽ ചേരുക",

    "connect.story.chip": "സെറ്റ്ബിൻ കണക്റ്റ്",
    "connect.story.s1.title": "മൊബൈൽ സേവനങ്ങൾക്കായുള്ള ഇന്ത്യയിലെ ബി2ബി നെറ്റ്‌വർക്ക്",
    "connect.story.s1.desc": "ടെക്നീഷ്യൻമാരെയും സർവീസ് സെന്ററുകളെയും സ്പെയർ പാർട്സ് വിതരണക്കാരെയും ഒരു നിശ്ചിത ഇക്കോസിസ്റ്റത്തിലേക്ക് ബന്ധിപ്പിക്കുന്ന ഒരു പ്ലാറ്റ്‌ഫോം.",
    "connect.story.s2.tag": "പഴയ രീതി",
    "connect.story.s2.title": "പാർട്സ് കണ്ടെത്തൽ ഇപ്പോഴും ബുദ്ധിമുട്ടേറിയതാണ്",
    "connect.story.s2.p1": "തത്സമയ ലഭ്യതയില്ല",
    "connect.story.s2.p2": "കൃത്യമായ വില വിവരങ്ങളില്ല",
    "connect.story.s2.p3": "വ്യാജ ഭാഗങ്ങളുടെ വലിയ ഭീഷണി",
    "connect.story.s2.p4": "അനന്തമായ കോളുകളും സന്ദേശങ്ങളും",
    "connect.story.s3.tag": "പരിഹാരം",
    "connect.story.s3.title": "അനിശ്ചിതത്വത്തിൽ നിന്ന് ഐക്യത്തിലേക്ക്",
    "connect.story.s3.desc": "വിശ്വാസയോഗ്യരായ വിതരണക്കാരിൽ നിന്ന് പരിശോധിച്ച ഭാഗങ്ങൾ തൽക്ഷണം തിരയുക, താരതമ്യം ചെയ്യുക, വാങ്ങുക.",
    "connect.story.s4.title": "വിതരണക്കാരുമായി നേരിട്ടുള്ള ബന്ധം",
    "connect.story.s4.desc": "ഇന്ത്യയിലുടനീളമുള്ള വിതരണക്കാരുമായി നേരിട്ട് ബന്ധപ്പെടുക. ഇടനിലക്കാരില്ലാത്തതിനാൽ അധിക ചിലവുകളില്ല.",
    "connect.story.s5.title": "തത്സമയ സ്റ്റോക്ക് വിവരങ്ങൾ",
    "connect.story.s5.desc": "ഓർഡർ ചെയ്യുന്നതിന് മുൻപ് സ്റ്റോക്ക് ഉണ്ടോ എന്ന് ഉറപ്പുവരുത്തുക. ഇത് അനിശ്ചിതത്വം ഒഴിവാക്കുന്നു.",
    "connect.story.s5.feed": "ലൈവ് സ്റ്റോക്ക് ഫീഡ്",
    "connect.story.s5.stock": "സ്റ്റോക്കുണ്ട്",
    "connect.story.s5.p1": "ഐഫോൺ 13 പ്രോ സ്ക്രീൻ",
    "connect.story.s5.p2": "സാംസങ് S22 ബാറ്ററി",
    "connect.story.s5.p3": "ടൈപ്പ്-സി പോർട്ട് ഐസി",
    "connect.story.s6.title": "ഹോൾസെയിൽ വില",
    "connect.story.s6.desc": "ബി2ബി വിലകൾ തൽക്ഷണം കാണുക. ചില്ലറ വിലയേക്കാൾ കുറഞ്ഞ നിരക്കിൽ വിതരണക്കാരിൽ നിന്ന് നേരിട്ട് വാങ്ങുക.",
    "connect.story.s6.retail": "റീട്ടെയിൽ ശരാശരി",
    "connect.story.s7.title": "ഗുണനിലവാരമുള്ള പാർട്സ്",
    "connect.story.s7.desc": "വ്യാജ ഭാഗങ്ങളുടെ ഭീഷണി ഒഴിവാക്കുക. ഉയർന്ന നിലവാരമുള്ളതും ഒറിജിനലുമായ ഭാഗങ്ങൾ മാത്രം ലഭ്യമാക്കുന്നു.",
    "connect.story.s8.title": "മണിക്കൂറുകളിൽ നിന്ന് മിനിറ്റുകളിലേക്ക്",
    "connect.story.s8.desc": "നേരത്തെ മണിക്കൂറുകൾ എടുത്ത പണികൾ ഇപ്പോൾ സെക്കന്റുകൾക്കുള്ളിൽ പൂർത്തിയാക്കാം.",
    "connect.story.s8.btn": "കണക്റ്റ് ഇക്കോസിസ്റ്റം പര്യവേക്ഷണം ചെയ്യുക",

    "contact.card.office.title": "ഓഫീസ് ലൊക്കേഷൻ",
    "contact.card.office.value": "SETTINGS സർവീസ് സെന്റർ എറണാകുളം",
    "contact.card.office.sub": "കൊച്ചി, കേരളം — ഇന്ത്യ",
    "contact.card.direct.title": "നേരിട്ടുള്ള ബന്ധം",
    "contact.card.direct.sub": "തിങ്കൾ-ശനി · 10AM – 7PM IST",
    "contact.card.email.title": "എന്റർപ്രൈസ് ഇമെയിൽ",
    "contact.card.email.sub": "24 മണിക്കൂറിനുള്ളിൽ മറുപടി",
    "contact.send_message": "സന്ദേശം അയക്കുക",
    "contact.map.label": "SETBIN // എറണാകുളം",
    "contact.get_directions": "വഴി കണ്ടെത്തുക",

    "network.city.delhi": "ഡൽഹി",
    "network.city.mumbai": "മുംബൈ",
    "network.city.bangalore": "ബാംഗ്ലൂർ",
    "network.city.hyderabad": "ഹൈദരാബാദ്",
    "network.city.chennai": "ചെന്നൈ",
    "network.city.kolkata": "കൊൽക്കത്ത",
    "network.city.ahmedabad": "അഹമ്മദാബാദ്",
    "network.city.kochi": "കൊച്ചി",

    "platform.pillar1.title": "SETBIN കണക്റ്റ്",
    "platform.pillar1.subtitle": "പരിശോധിച്ച സ്പെയർ പാർട്സ് മാർക്കറ്റ് പ്ലേസ്",
    "platform.pillar1.body": "വിശ്വസനീയരായ വിതരണക്കാരുമായി ബന്ധപ്പെടുക. യഥാർത്ഥ ഭാഗങ്ങൾ വേഗത്തിൽ കണ്ടെത്തുക.",
    "platform.pillar2.title": "SETBIN റിപ്പയർ",
    "platform.pillar2.subtitle": "സർവീസ് സെന്റർ ഓപ്പറേറ്റിംഗ് സിസ്റ്റം",
    "platform.pillar2.body": "ജോലികൾ മാനേജ് ചെയ്യുക, റിപ്പയറുകൾ ട്രാക്ക് ചെയ്യുക, ഇൻവെന്ററി നിയന്ത്രിക്കുക.",
    "platform.pillar3.title": "SCHEMIC AI",
    "platform.pillar3.subtitle": "AI-പവർ ഡയഗ്നോസ്റ്റിക്സ്",
    "platform.pillar3.body": "സ്കീമാറ്റിക് ഉപയോഗിച്ച് തകരാറുകൾ കൃത്യമായി കണ്ടെത്തുക.",
    "platform.viewMore": "കൂടുതൽ കാണുക →",

    "pro.dashboard.title": "നിങ്ങളുടെ ബിസിനസ്സ് മുഴുവൻ <br/> ഒരു കുടക്കീഴിൽ",
    "pro.dashboard.desc": "ജോബ് ഇൻടേക്ക് മുതൽ ബില്ലിംഗ് വരെയും, ഇൻവെന്ററി മുതൽ ഫിനാൻഷ്യൽ ട്രാക്കിംഗ് വരെയും — മൊബൈൽ സർവീസ് സെന്ററുകൾക്കായി സെറ്റ്ബിൻ എല്ലാ പ്രവർത്തനങ്ങളെയും ഒരു തടസ്സമില്ലാത്ത വർക്ക്ഫ്ലോയിലേക്ക് കൊണ്ടുവരുന്നു.",
    "pro.btn.cta": "ഓട്ടോമേഷൻ ആരംഭിക്കുക",
    "pro.nav.overview": "അവലോകനം",
    "pro.nav.daybook": "ഡേബുക്ക്",
    "pro.nav.services": "സേവനങ്ങൾ",
    "pro.nav.billing": "ബില്ലിംഗ്",
    "pro.nav.expenses": "ചെലവുകൾ",
    "pro.nav.dues": "കുടിശ്ശിക",
    "pro.nav.inventory": "ഇൻവെന്ററി",
    "pro.nav.staff": "സ്റ്റാഫ്",
    "pro.nav.customers": "കസ്റ്റമേഴ്സ്",
    "pro.nav.vendors": "വെണ്ടർമാർ",
    "pro.nav.reports": "റിപ്പോർട്ടുകൾ",

    "pro.card.revenue.title": "പ്രതിദിന വരുമാനം",
    "pro.card.revenue.detail": "കഴിഞ്ഞ ആഴ്ചയേക്കാൾ +15%",
    "pro.card.pending.title": "ബാക്കി നിൽക്കുന്ന ജോലികൾ",
    "pro.card.pending.detail": "4 എണ്ണം അടിയന്തിരം",
    "pro.card.cash_flow.title": "ക്യാഷ് ഫ്ലോ",
    "pro.card.cash_flow.detail": "അവസാന അപ്‌ഡേറ്റ് 2 സെക്കൻഡ് മുമ്പ്",
    "pro.card.transactions.title": "ഇടപാടുകൾ",
    "pro.card.transactions.detail": "UPI വഴിയുള്ളവ കൂടുതൽ",
    "pro.card.avg_repair.title": "ശരാശരി റിപ്പയർ സമയം",
    "pro.card.avg_repair.detail": "ലക്ഷ്യത്തേക്കാൾ -5 മിനിറ്റ്",
    "pro.card.ready_jobs.title": "പൂർത്തിയായവ",
    "pro.card.ready_jobs.detail": "ഡെലിവറിക്കായി കാത്തിരിക്കുന്നു",
    "pro.card.outstanding.title": "കുടിശ്ശിക",
    "pro.card.outstanding.detail": "5 ഉപഭോക്താക്കൾ",
    "pro.card.inv_match.title": "ഇൻവെന്ററി ഏകീകരണം",
    "pro.card.inv_match.detail": "GST വെരിഫൈഡ്",
    "pro.card.exp_total.title": "ആകെ ചെലവ്",
    "pro.card.exp_total.detail": "പ്രതിമാസ ചെലവ്",
    "pro.card.rent_paid.title": "വാടക നൽകി",
    "pro.card.rent_paid.detail": "അടുത്തത് 28 ദിവസത്തിനുള്ളിൽ",
    "pro.card.receivables.title": "ലഭിക്കാനുള്ള തുക",
    "pro.card.receivables.detail": "4 എണ്ണം ബാക്കി",
    "pro.card.payables.title": "നൽകാനുള്ള തുക",
    "pro.card.payables.detail": "3 ദിവസത്തിനുള്ളിൽ",
    "pro.card.stock_val.title": "സ്റ്റോക്ക് മൂല്യം",
    "pro.card.stock_val.detail": "450 ഇനങ്ങൾ",
    "pro.card.low_stock.title": "സ്റ്റോക്ക് കുറവാണ്",
    "pro.card.low_stock.detail": "അലേർട്ട് സജീവമാണ്",
    "pro.card.efficiency.title": "കാര്യക്ഷമത",
    "pro.card.efficiency.detail": "ടീം ശരാശരി",
    "pro.card.active_staff.title": "പ്രവർത്തനക്ഷമമായ സ്റ്റാഫ്",
    "pro.card.active_staff.detail": "4 പേർ ഒഴിവുണ്ട്",
    "pro.card.customers.title": "ഉപഭോക്താക്കൾ",
    "pro.card.customers.detail": "ആവർത്തിച്ചുള്ളവർ",
    "pro.card.avg_ltv.title": "ശരാശരി മൂല്യം",
    "pro.card.avg_ltv.detail": "5% വർദ്ധിച്ചു",
    "pro.card.vendors.title": "വെണ്ടർമാർ",
    "pro.card.vendors.detail": "3 സജീവ ഓർഡറുകൾ",
    "pro.card.lead_time.title": "ലഭ്യമാകാൻ എടുക്കുന്ന സമയം",
    "pro.card.lead_time.detail": "മികച്ച നിലവാരം",
    "pro.card.analytics.title": "അനലിറ്റിക്സ്",
    "pro.card.analytics.detail": "തത്സമയം",
    "pro.card.uptime.title": "അപ്‌ടൈം",
    "pro.card.uptime.detail": "ഗ്ലോബൽ ക്ലസ്റ്റർ",

    "ai.card1.title": "AI-പവർ ഫാൾട്ട് ഡയഗ്നോസ്റ്റിക്സ്",
    "ai.card1.desc": "AI ഉപയോഗിച്ച് തകരാറുകൾ തൽക്ഷണം കണ്ടെത്തുക.",
    "ai.card2.title": "ഇമേജ് അടിസ്ഥാനമാക്കിയുള്ള കണ്ടെത്തലുകൾ",
    "ai.card2.desc": "മദർബോർഡ് ചിത്രങ്ങളിൽ നിന്ന് കേടുപാടുകൾ സ്വയം കണ്ടെത്തുക.",
    "ai.card3.title": "സ്മാർട്ട് റിപ്പയർ ഗൈഡൻസ്",
    "ai.card3.desc": "ഘട്ടം ഘട്ടമായുള്ള റിപ്പയർ നിർദ്ദേശങ്ങൾ സ്വന്തമാക്കുക.",
    "ai.card4.title": "AI-പവർ ടെസ്റ്റിംഗ്",
    "ai.card4.desc": "എവിടെ പരിശോധിക്കണം, എന്ത് മൂല്യങ്ങൾ നോക്കണം എന്ന് കൃത്യമായി മനസ്സിലാക്കുക.",
    "ai.card5.title": "നോളജ് എഞ്ചിൻ",
    "ai.card5.desc": "കഴിഞ്ഞകാല റിപ്പയറുകളിൽ നിന്ന് പഠിച്ച് കൃത്യത വർദ്ധിപ്പിക്കുന്നു.",
    "ai.diagnosis.complete": "ഡയഗ്നോസ്റ്റിക്സ് പൂർത്തിയായി",
    "ai.diagnosis.sub": "സ്കീമാറ്റിക് മാപ്പ് ചെയ്തു. പരിഹാരം തയ്യാറാണ്.",

    "footer.desc": "സേവന കേന്ദ്രങ്ങളെയും ടെക്നീഷ്യൻമാരെയും വിതരണക്കാരെയും AI-യുമായി ബന്ധിപ്പിക്കുന്ന ഇന്ത്യയിലെ ആദ്യത്തെ പ്ലാറ്റ്‌ഫോം.",
    "footer.address": "SETBIN കണക്റ്റ് പ്രൈവറ്റ് ലിമിറ്റഡ്<br />കൊച്ചി, എറണാകുളം, കേരളം — ഇന്ത്യ",
    "footer.platform": "പ്ലാറ്റ്‌ഫോം",
    "footer.hardware": "ഹാർഡ്‌വെയർ",
    "footer.software": "വർക്ക്ഷോപ്പ് സോഫ്റ്റ്‌വെയർ",
    "footer.network": "കണക്റ്റ് നെറ്റ്‌വർക്ക്",
    "footer.experience": "അനുഭവം",
    "footer.solutions": "പരിഹാരങ്ങൾ",
    "footer.company": "കമ്പനി",
    "footer.links.diagnostics": "മദർബോർഡ് ഡയഗ്നോസ്റ്റിക്സ്",
    "footer.links.repairs": "ഐസി ലെവൽ റിപ്പയർ",
    "footer.links.sourcing": "പാർട്സ് സോഴ്സിങ്",
    "footer.links.erp": "സർവീസ് സെന്റർ ERP",
    "footer.links.jobs": "ജോബ് മാനേജ്‌മെന്റ്",
    "footer.links.customers": "കസ്റ്റമർ മാനേജ്‌മെന്റ്",
    "footer.links.inventory": "ഇൻവെന്ററി സിങ്ക്",
    "footer.links.billing": "ബില്ലിംഗ് & ഇൻവോയ്‌സിംഗ്",
    "footer.links.staff": "സ്റ്റാഫ് & റോൾസ്",
    "footer.links.vendors": "വെണ്ടർ അക്കൗണ്ടുകൾ",
    "footer.links.analytics": "റിപ്പോർട്ടുകൾ & അനലിറ്റിക്സ്",
    "footer.links.suppliers": "പരിശോധിച്ച സപ്ലയർമാർ",
    "footer.links.distributors": "പരിശോധിച്ച ഡിസ്ട്രിബ്യൂട്ടർമാർ",
    "footer.links.logistics": "ലോജിസ്റ്റിക്സ് പങ്കാളികൾ",
    "footer.links.dropship": "ഡ്രോപ്പ്-ഷിപ്പിംഗ്",
    "footer.links.hub": "ടെക്നീഷ്യൻ ഹബ്",
    "footer.links.marketplace": "ബി2ബി മാർക്കറ്റ് പ്ലേസ്",
    "footer.links.portal": "കസ്റ്റമർ പോർട്ടൽ",
    "footer.links.dashboard": "ടെക്നീഷ്യൻ ഡാഷ്‌ബോർഡ്",
    "footer.links.freelance": "ഫ്രീലാൻസ് ടെക്നീഷ്യൻമാർക്ക്",
    "footer.links.centers": "സർവീസ് സെന്ററുകൾക്ക്",
    "footer.links.chains": "പ്രമുഖ ശൃംഖലകൾക്ക്",
    "footer.links.about": "SETBIN-നെ കുറിച്ച്",
    "footer.links.careers": "കരിയർ",
    "footer.links.partners": "പാർട്ടണർ പ്രോഗ്രാം",
    "footer.links.privacy": "സ്വകാര്യതാ നയം",
    "footer.links.terms": "ഉപയോഗ നിബന്ധനകൾ",
    "footer.links.disclaimer": "നിരാകരണം",
    "footer.rights": "എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം."
  },
  hi: {
    "nav.connect": "सेटबिन कनेक्ट",
    "nav.repair": "सेटबिन रिपेयर",
    "nav.schemic": "स्केमिक एआई",
    "nav.connectBtn": "हमसे जुड़ें",
    "nav.connectBtnMobile": "जुड़ें",
    "hero.stage1.title": "SETBIN",
    "hero.stage1.subtitle": "स्मार्टफोन सेवा उद्योग की डिजिटल रीढ़",
    "hero.stage2.title": "<span class='text-[#00F0FF]'>अरबों</span> का उद्योग<br/>अभी भी <span class='text-[#00F0FF]'>बुनियादी ढांचे</span> के बिना चल रहा है",
    "hero.stage2.subtext": "तकनीशियन। पुर्जे। संचालन। इंटेलिजेंस।<br/>सब अलग-थलग।",
    "hero.stage3.title": "विखंडन से<br/><span class='text-[#00F0FF]'>संरचना</span> तक",
    "hero.stage3.subtext": "क्या होगा अगर सब कुछ एक साथ काम करे?",
    "hero.stage4.title": "SETBIN पारिस्थितिकी तंत्र को <span class='text-[#00F0FF]'>जोड़ता है</span>",
    "hero.stage4.subtext": "स्पेयर सोर्सिंग<br/>सेवा संचालन<br/>तकनीकी इंटेलिजेंस<br/>सब एक ही प्लेटफॉर्म पर।",
    "hero.stage5.title": "<span class='text-[#00F0FF]'>जुड़ें।</span> <span class='text-[#ffffff]'>संचालित करें।</span> <span class='text-[#00F0FF]'>निदान करें।</span>",
    "hero.stage5.subtext": "आधुनिक मरम्मत उद्योग के लिए<br/>एक पूर्ण बुनियादी ढांचा।",
    "hero.stage6.title": "SETBIN",
    "hero.stage6.subtext": "भारत के स्मार्टफोन सेवा उद्योग के लिए बुनियादी ढांचा",
    "hero.stage7.title": "मोबाइल सेवा के <span class='text-[#00F0FF]'>भविष्य</span> को सशक्त बनाना",
    "hero.stage7.btn": "प्लेटफॉर्म देखें",
    
    "pro.dashboard.title": "आपके पूरे सर्विस बिजनेस के लिए <br/> एक सिस्टम",
    "pro.dashboard.desc": "जॉब इनटेक से लेकर बिलिंग तक, इन्वेंट्री से लेकर फाइनेंशियल ट्रैकिंग तक — सेटबिन मोबाइल सर्विस सेंटर्स के लिए हर ऑपरेशन को एक सहज वर्कफ़्लो में जोड़ता है।",
    "pro.btn.cta": "ऑटोमेशन शुरू करें",
    "pro.nav.overview": "अवलोकन",
    "pro.nav.daybook": "डेबुक",
    "pro.nav.services": "सेवाएं",
    "pro.nav.billing": "बिलिंग",
    "pro.nav.expenses": "खर्चे",
    "pro.nav.dues": "बकाया",
    "pro.nav.inventory": "इन्वेंट्री",
    "pro.nav.staff": "स्टाफ",
    "pro.nav.customers": "ग्राहक",
    "pro.nav.vendors": "विक्रेता",
    "pro.nav.reports": "रिपोर्ट",

    "pro.card.revenue.title": "दैनिक राजस्व",
    "pro.card.revenue.detail": "पिछले सप्ताह से +15%",
    "pro.card.pending.title": "लंबित कार्य",
    "pro.card.pending.detail": "4 तत्काल",
    "pro.card.cash_flow.title": "कैश फ्लो",
    "pro.card.cash_flow.detail": "अंतिम सिंक 2 सेकंड पहले",
    "pro.card.transactions.title": "लेनदेन",
    "pro.card.transactions.detail": "UPI प्रमुख",
    "pro.card.avg_repair.title": "औसत मरम्मत समय",
    "pro.card.avg_repair.detail": "लक्ष्य से -5 मिनट",
    "pro.card.ready_jobs.title": "तैयार जॉब्स",
    "pro.card.ready_jobs.detail": "डिलीवरी की प्रतीक्षा",
    "pro.card.outstanding.title": "बकाया राशि",
    "pro.card.outstanding.detail": "5 ग्राहक",
    "pro.card.inv_match.title": "इन्वेंट्री मिलान",
    "pro.card.inv_match.detail": "GST सत्यापित",
    "pro.card.exp_total.title": "कुल खर्च",
    "pro.card.exp_total.detail": "मासिक खर्च",
    "pro.card.rent_paid.title": "किराया भुगतान किया गया",
    "pro.card.rent_paid.detail": "28 दिनों में देय",
    "pro.card.receivables.title": "प्राप्य",
    "pro.card.receivables.detail": "4 लंबित",
    "pro.card.payables.title": "देय",
    "pro.card.payables.detail": "3 दिनों में",
    "pro.card.stock_val.title": "स्टॉक मूल्य",
    "pro.card.stock_val.detail": "450 SKU",
    "pro.card.low_stock.title": "स्टॉक कम है",
    "pro.card.low_stock.detail": "अलर्ट सक्रिय",
    "pro.card.efficiency.title": "दक्षता",
    "pro.card.efficiency.detail": "टीम औसत",
    "pro.card.active_staff.title": "सक्रिय स्टाफ",
    "pro.card.active_staff.detail": "4 उपलब्ध",
    "pro.card.customers.title": "ग्राहक",
    "pro.card.customers.detail": "आवर्ती",
    "pro.card.avg_ltv.title": "औसत मूल्य",
    "pro.card.avg_ltv.detail": "5% बढ़ा",
    "pro.card.vendors.title": "विक्रेता",
    "pro.card.vendors.detail": "3 सक्रिय ऑर्डर",
    "pro.card.lead_time.title": "लीड टाइम",
    "pro.card.lead_time.detail": "शीर्ष स्तर",
    "pro.card.analytics.title": "एनालिटिक्स",
    "pro.card.analytics.detail": "रियल-टाइम",
    "pro.card.uptime.title": "अपटाइम",
    "pro.card.uptime.detail": "ग्लोबल क्लस्टर",

    "ai.card1.title": "AI-पावर्ड फॉल्ट डायग्नोस्टिक्स",
    "ai.card1.desc": "तंत्रिका विश्लेषण के साथ सूक्ष्म स्तर की सर्किट विफलताओं का सटीक पता लगाएं।",
    "ai.card2.title": "रियल-टाइम थर्मल मैपिंग",
    "ai.card2.desc": "पूर्वानुमानित ताप-हस्ताक्षर मॉडलिंग का उपयोग करके ओवरहीटिंग घटकों की पहचान करें।",
    "ai.card3.title": "स्मार्ट रिपेयर गाइडेंस",
    "ai.card3.desc": "जटिल IC-स्तर की मरम्मत के लिए चरण-दर-चरण निर्देश प्राप्त करें।",
    "ai.card4.title": "PCB इंटीग्रिटी टेस्टिंग",
    "ai.card4.desc": "बोर्ड के निशान और कनेक्टिविटी का स्वचालित सत्यापन।",
    "ai.card5.title": "नॉलेज-बेस इंटीग्रेशन",
    "ai.card5.desc": "ज्ञात हार्डवेयर विफलता पैटर्न के वैश्विक डेटाबेस से जुड़ा हुआ।",
    "ai.diagnosis.complete": "डायग्नोस्टिक्स पूर्ण: फॉल्ट की पहचान की गई",
    "ai.diagnosis.sub": "समाधान सर्विस पाइपलाइन में मैप किया गया।",

    "footer.desc": "मोबाइल सर्विस सेंटरों, तकनीशियनों और पुर्जों के आपूर्तिकर्ताओं के लिए भारत का पहला एकीकृत बुनियादी ढांचा।",
    "footer.address": "सेटबिन कनेक्ट प्राइवेट लिमिटेड<br />कोच्चि, एर्नाकुलम, केरल — भारत",
    "footer.platform": "प्लेटफॉर्म",
    "footer.hardware": "हार्डवेयर",
    "footer.software": "कार्यशाला सॉफ्टवेयर",
    "footer.network": "कनेक्ट नेटवर्क",
    "footer.experience": "अनुभव",
    "footer.solutions": "समाधान",
    "footer.company": "कंपनी",
    "footer.links.diagnostics": "मदरबोर्ड डायग्नोस्टिक्स",
    "footer.links.repairs": "IC स्तर की मरम्मत",
    "footer.links.sourcing": "पुर्जों की सोर्सिंग",
    "footer.links.erp": "सर्विस सेंटर ERP",
    "footer.links.jobs": "जॉब मैनेजमेंट",
    "footer.links.customers": "ग्राहक मैनेजमेंट",
    "footer.links.inventory": "इन्वेंट्री सिंक",
    "footer.links.billing": "बिलिंग और चालान",
    "footer.links.staff": "स्टाफ और रोल्स",
    "footer.links.vendors": "विक्रेता खाते",
    "footer.links.analytics": "रिपोर्ट और एनालिटिक्स",
    "footer.links.suppliers": "सत्यापित आपूर्तिकर्ता",
    "footer.links.distributors": "सत्यापित वितरक",
    "footer.links.logistics": "रसद भागीदार",
    "footer.links.dropship": "ड्रॉप-शिपिंग",
    "footer.links.hub": "तकनीशियन हब",
    "footer.links.marketplace": "B2B मार्केटप्लेस",
    "footer.links.portal": "ग्राहक पोर्टल",
    "footer.links.dashboard": "तकनीशियन डैशबोर्ड",
    "footer.links.freelance": "फ्रीलांस तकनीशियनों के लिए",
    "footer.links.centers": "सर्विस सेंटरों के लिए",
    "footer.links.chains": "प्रमुख श्रृंखलाओं के लिए",
    "footer.links.about": "सेटबिन के बारे में",
    "footer.links.careers": "कैरियर",
    "footer.links.partners": "पार्टनर प्रोग्राम",
    "footer.links.privacy": "गोपनीयता नीति",
    "footer.links.terms": "सेवा की शर्तें",
    "footer.links.disclaimer": "अस्वीकरण",
    "footer.rights": "सर्वाधिकार सुरक्षित।"
,
    "platform.chip": "प्लेटफॉर्म",
    "platform.title": "अगली पीढ़ी की सेवा को सशक्त बनाना",
    "platform.desc": "स्मार्टफोन सेवा उद्योग के लिए डिज़ाइन किया गया एक व्यापक पारिस्थितिकी तंत्र।",
    "platform.card1.title": "एकीकृत प्रबंधन पारिस्थितिकी तंत्र",
    "platform.card1.desc": "अपने सेवा व्यवसाय के हर पहलू को एक ही स्थान पर जोड़ें।",
    "platform.card2.title": "AI-संचालित निदान",
    "platform.card2.desc": "सटीक समस्या निवारण के लिए उन्नत योजनाबद्ध विश्लेषण।",
    "platform.card3.title": "भारत की सबसे बड़ी आपूर्ति श्रृंखला",
    "platform.card3.desc": "देश के सर्वोत्तम आपूर्तिकर्ताओं से उच्च गुणवत्ता वाले पुर्जों और उपकरणों तक पहुँचें।",
    "platform.pillar1.title": "SETBIN CONNECT",
    "platform.pillar1.subtitle": "सत्यापित स्पेयर पार्ट्स मार्केटप्लेस",
    "platform.pillar1.body": "विश्वसनीय आपूर्तिकर्ताओं से जुड़ें। पूर्ण पारदर्शिता के साथ असली पुर्जे तेजी से प्राप्त करें।",
    "platform.pillar2.title": "SETBIN REPAIR",
    "platform.pillar2.subtitle": "सर्विस सेंटर ऑपरेटिंग सिस्टम",
    "platform.pillar2.body": "नौकरियों का प्रबंधन करें, मरम्मत को ट्रैक करें, इन्वेंट्री को नियंत्रित करें और अपने कार्यप्रवाह को सुव्यवस्थित करें।",
    "platform.pillar3.title": "SCHEMIC AI",
    "platform.pillar3.subtitle": "AI-संचालित नैदानिक बुद्धिमत्ता",
    "platform.pillar3.body": "परीक्षण-और-त्रुटि मरम्मत के बजाय योजनाबद्ध तर्क का उपयोग करके दोषों की पहचान करें।",
    "platform.viewMore": "और देखें →",

    "pillars.chip": "नवाचार के स्तंभ",
    "pillars.title": "मरम्मत के भविष्य का <br/>निर्माण।",
    "pillars.desc": "हम एक एकीकृत पारिस्थितिकी तंत्र का निर्माण कर रहे हैं जहाँ आपूर्ति श्रृंखला, सेवा केंद्र और AI निदान एक साथ आते हैं।",
    "pillars.footer": "स्केल के लिए निर्मित • बुद्धिमत्ता द्वारा संचालित • पेशेवरों द्वारा विश्वसनीय",
    "pillars.connect.subtitle": "पारिस्थितिकी तंत्र",
    "pillars.repair.subtitle": "बुनियादी ढांचा",
    "pillars.schemic.subtitle": "बुद्धिमत्ता",
    "connect.chip": "SETBIN CONNECT",
    "connect.title": "इलेक्ट्रॉनिक्स के लिए भारत का B2B नेटवर्किंग",
    "connect.desc": "पुर्जों के आपूर्तिकर्ताओं और सेवा केंद्रों को जोड़ने वाले भारत के सबसे बड़े नेटवर्क में शामिल हों।",
    "connect.features.suppliers": "प्रत्यक्ष आपूर्तिकर्ता पहुंच",
    "connect.features.tools": "प्रीमियम टूल सोर्सिंग",
    "connect.features.wholesale": "थोक मूल्य निर्धारण",
    "connect.btn": "नेटवर्क में शामिल हों",

    "connect.story.chip": "SETBIN CONNECT",
    "connect.story.s1.title": "मोबाइल सेवा के लिए भारत का B2B नेटवर्क",
    "connect.story.s1.desc": "तकनीशियनों, सेवा केंद्रों और स्पेयर पार्ट्स आपूर्तिकर्ताओं को एक संरचित पारिस्थितिकी तंत्र में जोड़ने वाला एक सत्यापित मंच।",
    "connect.story.s2.tag": "पुरानी विधि",
    "connect.story.s2.title": "सोर्सिंग अभी भी मैनुअल एवं अव्यवस्थित है",
    "connect.story.s2.p1": "रियल-टाइम उपलब्धता नहीं",
    "connect.story.s2.p2": "कोई मूल्य स्पष्टता नहीं",
    "connect.story.s2.p3": "नकली पुर्जों का अधिक जोखिम",
    "connect.story.s2.p4": "अंतहीन कॉल और संदेश",
    "connect.story.s3.tag": "समाधान",
    "connect.story.s3.title": "अव्यवस्था से संरचना तक",
    "connect.story.s3.desc": "विश्वसनीय आपूर्तिकर्ताओं से सत्यापित पुर्जे खोजें, तुलना करें और तुरंत प्राप्त करें।",
    "connect.story.s4.title": "प्रत्यक्ष आपूर्तिकर्ता पहुंच",
    "connect.story.s4.desc": "विलंब के बिना पूरे भारत में सत्यापित थोक विक्रेताओं से सीधे जुड़ें। कोई बिचौलिए नहीं।",
    "connect.story.s5.title": "रियल-टाइम इन्वेंटरी",
    "connect.story.s5.desc": "ऑर्डर करने से पहले सटीक उपलब्धता जानें। लाइव स्टॉक संकेतक अनिश्चितता को समाप्त करते हैं।",
    "connect.story.s5.feed": "लाइव स्टॉक फ़ीड",
    "connect.story.s5.stock": "स्टॉक में",
    "connect.story.s5.p1": "iPhone 13 Pro स्क्रीन",
    "connect.story.s5.p2": "Samsung S22 बैटरी",
    "connect.story.s5.p3": "Type-C पोर्ट IC",
    "connect.story.s6.title": "सच्ची थोक कीमत",
    "connect.story.s6.desc": "तुरंत पारदर्शी B2B मूल्य निर्धारण एक्सेस करें। सत्यापित आपूर्तिकर्ताओं से दरों की तुलना करें।",
    "connect.story.s6.retail": "खुदरा औसत",
    "connect.story.s7.title": "सत्यापित असली पुर्जे",
    "connect.story.s7.desc": "नकली घटकों का जोखिम कम करें। हमारा आपूर्तिकर्ता नेटवर्क OEM पुर्जों को सुनिश्चित करने के लिए सख्ती से जाँचा गया है।",
    "connect.story.s8.title": "घंटों से मिनटों तक",
    "connect.story.s8.desc": "जो काम कभी घंटों की कॉल से होता था, वह अब भारत के सत्यापित प्लेटफ़ॉर्म पर सेकंडों में हो जाता है।",
    "connect.story.s8.btn": "कनेक्ट इकोसिस्टम एक्सप्लोर करें",

    // SaaS Showcase Rebrand
    "pro.showcase.heading": "अपना पूरा सर्विस बिजनेस एक ही सिस्टम में चलाएं",
    "pro.showcase.subheading": "SETBIN REPAIR",
    "pro.showcase.desc": "जॉब इनटेक से लेकर बिलिंग तक, इन्वेंट्री से लेकर फाइनेंशियल ट्रैकिंग तक — SETBIN मोबाइल सर्विस सेंटरों के लिए हर ऑपरेशन को एक निर्बाध वर्कफ्लो में जोड़ता है।",
    "pro.showcase.cta.demo": "डेमो देखें",
    "pro.showcase.cta.free": "फ्री ट्रायल शुरू करें",
    "pro.showcase.nav.daybook": "डेबुक",
    "pro.showcase.nav.billing": "बिलिंग",
    "pro.showcase.nav.inventory": "इन्वेंट्री",
    "pro.showcase.nav.reports": "रिपोर्ट",
    "pro.showcase.nav.dues": "बकाया",
    "pro.showcase.nav.exp": "खर्चे",
    "pro.showcase.card.rev.title": "राजस्व",
    "pro.showcase.card.rev.amt": "$198.5M",
    "pro.showcase.card.due.title": "बकाया",
    "pro.showcase.card.due.amt": "$15.3M",
    "pro.showcase.card.rules.title": "सेवा नियम",
    "pro.showcase.card.rules.r1": "रेटबल",
    "pro.showcase.card.rules.r2": "पॉइंट_इन_टाइम",
    "pro.showcase.card.rules.r3": "आनुपातिक",
    
    "pro.chip": "SETBIN REPAIR",
    "pro.title": "अपने सेवा व्यवसाय को ऊपर उठाएं",
    "pro.desc": "मरम्मत की दुकानों के लिए पूर्ण प्रबंधन पाइपलाइन। अपने वर्कफ़्लो को सुव्यवस्थित करें।",
    "pro.features.repair": "मरम्मत ट्रैकिंग",
    "pro.features.inventory": "इन्वेंटरी प्रबंधन",
    "pro.features.customer": "ग्राहक संचार",
    "pro.btn": "प्रबंधन शुरू करें",
    "ai.chip": "SCHEMIC AI",
    "ai.title": "अगली पीढ़ी के बोर्ड स्तर के निदान",
    "ai.desc": "हार्डवेयर दोषों को इंगित करने के लिए उन्नत कृत्रिम बुद्धिमत्ता का लाभ उठाएं।",
    "ai.features.analysis": "त्वरित विश्लेषण",
    "ai.features.faults": "दोष स्थानीयकरण",
    "ai.features.solutions": "मरम्मत समाधान",
    "ai.btn": "Schemic AI आज़माएं",
    "network.chip": "राष्ट्रीय नेटवर्क",
    "network.title": "भारत भर के विशेषज्ञों द्वारा विश्वसनीय",
    "network.desc": "उन हजारों सेवा पेशेवरों में शामिल हों जो SETBIN पर भरोसा करते हैं।",
    "contact.chip": "संपर्क करें",
    "contact.title": "आइए साथ मिलकर भविष्य बनाएं",
    "contact.desc": "अपने सेवा व्यवसाय को बदलने के लिए तैयार हैं?",
    "contact.info.title": "संपर्क जानकारी",
    "contact.info.email": "हमें ईमेल करें",
    "contact.info.phone": "हमें कॉल करें",
    "contact.info.address": "हमसे मिलें",
    "contact.form.name": "पूरा नाम",
    "contact.form.submit": "संदेश भेजें",
    "cta.title": "व्यवसाय में क्रांति लाने के लिए तैयार हैं?",
    "cta.desc": "हजारों पेशेवरों में शामिल हों जो SETBIN का उपयोग कर रहे हैं।",
    "cta.btn.start": "आज ही शुरू करें",
    "cta.btn.contact": "बिक्री से संपर्क करें",

    "contact.form.name_placeholder": "जॉन डो",
    "contact.form.email": "ईमेल पता",
    "contact.form.email_placeholder": "john@example.com",
    "contact.form.subject": "विषय",
    "contact.form.subject_placeholder": "हम आपकी कैसे मदद कर सकते हैं?",
    "contact.form.message": "संदेश",
    "contact.form.message_placeholder": "अपनी आवश्यकताओं के बारे में हमें बताएं...",

    "contact.card.office.title": "कार्यालय का पता",
    "contact.card.office.value": "SETTINGS सर्विस सेंटर एर्नाकुलम",
    "contact.card.office.sub": "कोच्चि, केरल — भारत",
    "contact.card.direct.title": "सीधा संपर्क",
    "contact.card.direct.sub": "सोम-शनि · सुबह 10 बजे – शाम 7 बजे IST",
    "contact.card.email.title": "एंटरप्राइज ईमेल",
    "contact.card.email.sub": "24 घंटे के भीतर जवाब",
    "contact.send_message": "संदेश भेजें",
    "contact.map.label": "SETBIN // एर्नाकुलम",
    "contact.get_directions": "दिशा-निर्देश प्राप्त करें",

    "network.city.delhi": "दिल्ली",
    "network.city.mumbai": "मुंबई",
    "network.city.bangalore": "बैंगलोर",
    "network.city.hyderabad": "हैदराबाद",
    "network.city.chennai": "चेन्नई",
    "network.city.kolkata": "कोलकाता",
    "network.city.ahmedabad": "अहमदाबाद",
    "network.city.kochi": "कोच्चि"
  },
  ta: {
    "nav.connect": "செட்பின் கனெக்ட்",
    "nav.repair": "செட்பின் ரிப்பேர்",
    "nav.schemic": "ஸ்கெமிக் ஏஐ",
    "nav.connectBtn": "எங்களுடன் இணையுங்கள்",
    "nav.connectBtnMobile": "இணையுங்கள்",
    "hero.stage1.title": "SETBIN",
    "hero.stage1.subtitle": "ஸ்மார்ட்போன் சேவைத் துறையின் டிஜிட்டல் முதுகெலும்பு",
    "hero.stage2.title": "பில்லியன் டாலர் மதிப்புள்ள தொழில்<br/>இன்னும் உள்கட்டமைப்பு இல்லாமல் இயங்குகிறது",
    "hero.stage2.subtext": "தொழில்நுட்ப வல்லுநர்கள். பாகங்கள். செயல்பாடுகள். நுண்ணறிவு.<br/>எல்லாம் துண்டிக்கப்பட்டுள்ளன.",
    "hero.stage3.title": "துண்டு துண்டாக இருப்பதிலிருந்து<br/>கட்டமைப்பு வரை",
    "hero.stage3.subtext": "எல்லாம் ஒன்றாக வேலை செய்தால் என்ன?",
    "hero.stage4.title": "SETBIN சுற்றுச்சூழல் அமைப்பை இணைக்கிறது",
    "hero.stage4.subtext": "பாகங்கள் தேடுதல்<br/>சேவை செயல்பாடுகள்<br/>தொழில்நுட்ப நுண்ணறிவு<br/>எல்லாம் ஒரே தளத்தில்.",
    "hero.stage5.title": "இணையுங்கள். இயக்குங்கள். கண்டறியுங்கள்.",
    "hero.stage5.subtext": "நவீன பழுதுபார்க்கும் துறைக்கான<br/>ஒரு முழுமையான உள்கட்டமைப்பு.",
    "hero.stage6.title": "SETBIN",
    "hero.stage6.subtext": "இந்திய ஸ்மார்ட்போன் சேவைத் துறைக்கான உள்கட்டமைப்பு",
    "hero.stage7.title": "மொபைல் சேவையின் எதிர்காலத்தை மேம்படுத்துதல்",
    "hero.stage7.btn": "தளத்தை ஆராயுங்கள்",

    "pro.dashboard.title": "உங்கள் முழு சேவை வணிகத்திற்கும் <br/> ஒரு அமைப்பு",
    "pro.dashboard.desc": "வேலை எடுப்பது முதல் பில்லிங் வரை, சரக்கு முதல் நிதி கண்காணிப்பு வரை — செட்பின் மொபைல் சேவை மையங்களுக்கான ஒவ்வொரு செயல்பாட்டையும் ஒரு தடையற்ற பணிப்பாய்வுக்கு கொண்டு வருகிறது.",
    "pro.btn.cta": "ஆட்டோமேஷனைத் தொடங்குங்கள்",
    "pro.nav.overview": "மேலோட்டம்",
    "pro.nav.daybook": "டேபுக்",
    "pro.nav.services": "சேவைகள்",
    "pro.nav.billing": "பில்லிங்",
    "pro.nav.expenses": "செலவுகள்",
    "pro.nav.dues": "பாக்கி",
    "pro.nav.inventory": "சரக்கு",
    "pro.nav.staff": "ஊழியர்கள்",
    "pro.nav.customers": "வாடிக்கையாளர்கள்",
    "pro.nav.vendors": "விற்பனையாளர்கள்",
    "pro.nav.reports": "அறிக்கைகள்",

    "pro.card.revenue.title": "தினசரி வருமானம்",
    "pro.card.revenue.detail": "கடந்த வாரத்தை விட +15%",
    "pro.card.pending.title": "நிலுவையில் உள்ள வேலைகள்",
    "pro.card.pending.detail": "4 அவசரமானவை",
    "pro.card.cash_flow.title": "பணப்புழக்கம்",
    "pro.card.cash_flow.detail": "கடைசி ஒத்திசைவு 2 வினாடிகளுக்கு முன்பு",
    "pro.card.transactions.title": "பரிவர்த்தனைகள்",
    "pro.card.transactions.detail": "UPI அதிகம்",
    "pro.card.avg_repair.title": "சராசரி பழுதுபார்க்கும் நேரம்",
    "pro.card.avg_repair.detail": "இலக்கை விட -5 நிமிடங்கள்",
    "pro.card.ready_jobs.title": "தயாரான வேலைகள்",
    "pro.card.ready_jobs.detail": "டெலிவரிக்காகக் காத்திருக்கிறது",
    "pro.card.outstanding.title": "பாக்கி தொகை",
    "pro.card.outstanding.detail": "5 வாடிக்கையாளர்கள்",
    "pro.card.inv_match.title": "சரக்கு பொருத்தம்",
    "pro.card.inv_match.detail": "GST சரிபார்க்கப்பட்டது",
    "pro.card.exp_total.title": "மொத்த செலவு",
    "pro.card.exp_total.detail": "மாதாந்திர செலவு",
    "pro.card.rent_paid.title": "வாடகை செலுத்தப்பட்டது",
    "pro.card.rent_paid.detail": "28 நாட்களில் செலுத்த வேண்டியது",
    "pro.card.receivables.title": "பெற வேண்டியவை",
    "pro.card.receivables.detail": "4 நிலுவையில் உள்ளது",
    "pro.card.payables.title": "செலுத்த வேண்டியவை",
    "pro.card.payables.detail": "3 நாட்களில்",
    "pro.card.stock_val.title": "சரக்கு மதிப்பு",
    "pro.card.stock_val.detail": "450 SKUகள்",
    "pro.card.low_stock.title": "சரக்கு குறைவாக உள்ளது",
    "pro.card.low_stock.detail": "எச்சரிக்கை செயலில் உள்ளது",
    "pro.card.efficiency.title": "திறன்",
    "pro.card.efficiency.detail": "குழு சராசரி",
    "pro.card.active_staff.title": "செயலில் உள்ள ஊழியர்கள்",
    "pro.card.active_staff.detail": "4 பேர் உள்ளனர்",
    "pro.card.customers.title": "வாடிக்கையாளர்கள்",
    "pro.card.customers.detail": "திரும்பத் திரும்ப வருபவர்கள்",
    "pro.card.avg_ltv.title": "சராசரி மதிப்பு",
    "pro.card.avg_ltv.detail": "5% அதிகரித்துள்ளது",
    "pro.card.vendors.title": "விற்பனையாளர்கள்",
    "pro.card.vendors.detail": "3 செயலில் உள்ள ஆர்டர்கள்",
    "pro.card.lead_time.title": "முன்னணி நேரம்",
    "pro.card.lead_time.detail": "உயர்மட்டம்",
    "pro.card.analytics.title": "அனலிட்டிக்ஸ்",
    "pro.card.analytics.detail": "நிகழ்நேரம்",
    "pro.card.uptime.title": "அப்டைம்",
    "pro.card.uptime.detail": "குளோபல் கிளஸ்டர்",

    "ai.card1.title": "AI-இயங்கும் தவறு கண்டறிதல்",
    "ai.card1.desc": "நியூாரல் பகுப்பாய்வு மூலம் மைக்ரோ அளவிலான சர்க்யூட் தோல்விகளைத் துல்லியமாகக் கண்டறியவும்.",
    "ai.card2.title": "நிகழ்நேர வெப்ப வரைபடம்",
    "ai.card2.desc": "முன்கணிப்பு வெப்ப-கையெழுத்து மாதிரியைப் பயன்படுத்தி அதிக வெப்பமடையும் கூறுகளை அடையாளம் காணவும்.",
    "ai.card3.title": "ஸ்மார்ட் பழுதுபார்ப்பு வழிகாட்டுதல்",
    "ai.card3.desc": "சிக்கலான IC-நிலை பழுதுபார்ப்புகளுக்கான படிப்படியான வழிமுறைகளைப் பெறுங்கள்.",
    "ai.card4.title": "PCB ஒருமைப்பாடு சோதனை",
    "ai.card4.desc": "போர்டு தடயங்கள் மற்றும் இணைப்பு ஆகியவற்றின் தானியங்கி சரிபார்ப்பு.",
    "ai.card5.title": "அறிவு-அடிப்படை ஒருங்கிணைப்பு",
    "ai.card5.desc": "அறியப்பட்ட வன்பொருள் தோல்வி வடிவங்களின் உலகளாவிய தரவுத்தளத்துடன் இணைக்கப்பட்டுள்ளது.",
    "ai.diagnosis.complete": "கண்டறிதல் முடிந்தது: தவறு அடையாளம் காணப்பட்டது",
    "ai.diagnosis.sub": "தீர்வு சேவை பைப்லைனில் வரைபடமாக்கப்பட்டது.",

    "footer.desc": "மொபைல் சேவை மையங்கள், தொழில்நுட்ப வல்லுநர்கள் மற்றும் உதிரிபாக சப்ளையர்களுக்கான இந்தியாவின் முதல் ஒருங்கிணைந்த உள்கட்டமைப்பு.",
    "footer.address": "செட்பின் கனெக்ட் பிரைவேட் லிமிடெட்<br />கொச்சி, எர்ணாகுளம், கேரளா — இந்தியா",
    "footer.platform": "பிளாட்பார்ம்",
    "footer.software": "ஒர்க்ஷாப் மென்பொருள்",
    "footer.network": "கனெக்ட் நெட்வொர்க்",
    "footer.company": "நிறுவனம்",
    "footer.links.diagnostics": "மதர்போர்டு கண்டறிதல்",
    "footer.links.repairs": "IC நிலை பழுதுபார்ப்பு",
    "footer.links.sourcing": "உதிரிபாகங்கள் பெறுதல்",
    "footer.links.erp": "சேவை மைய ERP",
    "footer.links.inventory": "சரக்கு ஒத்திசைவு",
    "footer.links.billing": "பில்லிங் மற்றும் இன்வாய்ஸிங்",
    "footer.links.suppliers": "சரிபார்க்கப்பட்ட சப்ளையர்கள்",
    "footer.links.logistics": "தளவாட கூட்டாளர்கள்",
    "footer.links.marketplace": "B2B சந்தை",
    "footer.links.about": "செட்பின் பற்றி",
    "footer.links.privacy": "தனியுரிமைக் கொள்கை",
    "footer.links.terms": "சேவை விதிமுறைகள்",
    "footer.links.disclaimer": "நிபந்தனைகள்",
    "footer.rights": "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",

    "platform.chip": "தளம்",
    "platform.title": "அடுத்த தலைமுறை சேவையை மேம்படுத்துதல்",
    "platform.desc": "ஸ்மார்ட்போன் சேவைத் துறைக்காக வடிவமைக்கப்பட்ட விரிவான சுற்றுச்சூழல் அமைப்பு.",
    "platform.pillar1.title": "SETBIN CONNECT",
    "platform.pillar1.subtitle": "சரிபார்க்கப்பட்ட உதிரி பாகங்கள் மெய்நிகர் சந்தை",
    "platform.pillar1.body": "நம்பகமான சப்ளையர்களுடன் இணையுங்கள். முழு வெளிப்படைத்தன்மையுடன் உண்மையான பாகங்களை விரைவாகப் பெறுங்கள்.",
    "platform.pillar2.title": "SETBIN REPAIR",
    "platform.pillar2.subtitle": "சேவை மைய இயக்க முறைமை",
    "platform.pillar2.body": "பணிகளை நிர்வகிக்கவும், பழுதுபார்ப்புகளைக் கண்காணிக்கவும், இருப்பைக் கட்டுப்படுத்தவும் மற்றும் உங்கள் பணிப்பாய்வுகளை சீரமைக்கவும்.",
    "platform.pillar3.title": "SCHEMIC AI",
    "platform.pillar3.subtitle": "AI-இயங்கும் நோய் கண்டறிதல் நுண்ணறிவு",
    "platform.pillar3.body": "சோதனை மற்றும் பிழை பழுதுபார்ப்புகளுக்கு பதிலாக திட்டவட்டமான தர்க்கத்தைப் பயன்படுத்தி பிழைகளைக் கண்டறியவும்.",
    "platform.viewMore": "மேலும் பார்க்க →",

    "pillars.chip": "புதுமையின் தூண்கள்",
    "pillars.title": "பழுதுபார்ப்பின் எதிர்காலத்தை <br/>உருவாக்குகிறோம்.",
    "pillars.desc": "சப்ளை செயின்கள், சேவை மையங்கள் மற்றும் AI கண்டறிதல் ஆகியவை ஒன்றிணையும் ஒரு ஒருங்கிணைந்த கட்டமைப்பை நாங்கள் உருவாக்குகிறோம்.",
    "pillars.footer": "வளர்ச்சிக்காக உருவாக்கப்பட்டது • நுண்ணறிவால் இயக்கப்படுகிறது • நிபுணர்களால் நம்பப்படுகிறது",
    "pillars.connect.subtitle": "சுற்றுச்சூழல் அமைப்பு",
    "pillars.repair.subtitle": "உள்கட்டமைப்பு",
    "pillars.schemic.subtitle": "நுண்ணறிவு",
    "connect.chip": "SETBIN CONNECT",
    "connect.title": "இந்திய B2B நெட்வொர்க்கிங்",
    "connect.desc": "இந்தியாவின் மிகப்பெரிய சிறப்பு நெட்வொர்க்கில் இணையுங்கள்.",
    "connect.features.suppliers": "நேரடி சப்ளையர் அணுகல்",
    "connect.features.tools": "பிரீமியம் கருவி தேடுதல்",
    "connect.features.wholesale": "மொத்த விற்பனை விலை",
    "connect.btn": "நெட்வொர்க்கில் இணையுங்கள்",

    "connect.story.chip": "SETBIN CONNECT",
    "connect.story.s1.title": "மொபைல் சேவைக்கான இந்தியாவின் B2B நெட்வொர்க்",
    "connect.story.s1.desc": "தொழில்நுட்ப வல்லுநர்கள், சேவை மையங்கள் மற்றும் உதிரி பாகங்கள் சப்ளையர்களை ஒரே கட்டமைப்பில் இணைக்கும் சரிபார்க்கப்பட்ட தளம்.",
    "connect.story.s2.tag": "பழைய முறை",
    "connect.story.s2.title": "சோர்சிங் இன்னும் கையேடு மற்றும் குழப்பமாக உள்ளது",
    "connect.story.s2.p1": "நிகழ்நேர கிடைக்கும் தன்மை இல்லை",
    "connect.story.s2.p2": "விலை நெளிவு இல்லை",
    "connect.story.s2.p3": "போலி பாகங்களின் அதிக ஆபத்து",
    "connect.story.s2.p4": "முடிவில்லாத அழைப்புகள் மற்றும் செய்திகள்",
    "connect.story.s3.tag": "தீர்வு",
    "connect.story.s3.title": "குழப்பத்திலிருந்து கட்டமைப்பு வரை",
    "connect.story.s3.desc": "நம்பகமான சப்ளையர்களிடமிருந்து சரிபார்க்கப்பட்ட பாகங்களை தேடுங்கள், ஒப்பிடுங்கள் மற்றும் உடனடியாக பெறுங்கள்.",
    "connect.story.s4.title": "நேரடி சப்ளையர் அணுகல்",
    "connect.story.s4.desc": "இடைத்தரகர்கள் இல்லாமல் இந்தியா முழுவதும் சரிபார்க்கப்பட்ட மொத்த வணிகர்களுடன் நேரடியாக இணையுங்கள்.",
    "connect.story.s5.title": "நிகழ்நேர சரக்கு",
    "connect.story.s5.desc": "கட்டளையிடுவதற்கு முன்பு சரியாக என்னவென்று தெரியும். நேரடி பங்கு குறிகாட்டிகள் நிச்சயமற்ற தன்மையை நீக்குகின்றன.",
    "connect.story.s5.feed": "நேரடி பங்கு ஊட்டம்",
    "connect.story.s5.stock": "கையிருப்பில் உள்ளது",
    "connect.story.s5.p1": "iPhone 13 Pro திரை",
    "connect.story.s5.p2": "Samsung S22 மின்கலம்",
    "connect.story.s5.p3": "Type-C போர்ட் IC",
    "connect.story.s6.title": "உண்மையான மொத்த விலை",
    "connect.story.s6.desc": "உடனடியாக வெளிப்படையான B2B விலையை அணுகுங்கள். சரிபார்க்கப்பட்ட சப்ளையர்களிடையே விலைகளை ஒப்பிடுங்கள்.",
    "connect.story.s6.retail": "சில்லறை சராசரி",
    "connect.story.s7.title": "சரிபார்க்கப்பட்ட உண்மையான பாகங்கள்",
    "connect.story.s7.desc": "போலி கூறுகளின் அபாயத்தை குறையுங்கள். OEM மற்றும் உயர்தர பாகங்களை உறுதிப்படுத்த எங்கள் சப்ளையர் நெட்வொர்க் கண்டிப்பாக சோதிக்கப்படுகிறது.",
    "connect.story.s8.title": "மணிநேரங்கள் நிமிடங்களாக",
    "connect.story.s8.desc": "ஒருமுறை மணிக்கணக்கான அழைப்புகளில் நடந்தது இப்போது இந்தியாவின் சரிபார்க்கப்பட்ட தளத்தில் வினாடிகளில் ஆகிறது.",
    "connect.story.s8.btn": "கனெக்ட் சுற்றுச்சூழல் ஆராயுங்கள்",

    // SaaS Showcase Rebrand
    "pro.showcase.heading": "உங்கள் முழு சேவை வணிகத்தையும் ஒரே அமைப்பில் நடத்துங்கள்",
    "pro.showcase.subheading": "SETBIN REPAIR",
    "pro.showcase.desc": "வேலை எடுப்பது முதல் பில்லிங் வரை, இருப்பு முதல் நிதி கண்காணிப்பு வரை — SETBIN மொபைல் சேவை மையங்களுக்கான ஒவ்வொரு செயல்பாட்டையும் ஒரு தடையற்ற பணிப்பாய்வுக்குள் இணைக்கிறது.",
    "pro.showcase.cta.demo": "ஒரு டெமோவைப் பெறுங்கள்",
    "pro.showcase.cta.free": "இலவச சோதனையைத் தொடங்கவும்",
    "pro.showcase.nav.daybook": "டேபுக்",
    "pro.showcase.nav.billing": "பில்லிங்",
    "pro.showcase.nav.inventory": "இருப்பு",
    "pro.showcase.nav.reports": "அறிக்கைகள்",
    "pro.showcase.nav.dues": "நிலுவைத் தொகை",
    "pro.showcase.nav.exp": "செலவுகள்",
    "pro.showcase.card.rev.title": "வருவாய்",
    "pro.showcase.card.rev.amt": "$198.5M",
    "pro.showcase.card.due.title": "நிலுவைத் தொகை",
    "pro.showcase.card.due.amt": "$15.3M",
    "pro.showcase.card.rules.title": "சேவை விதிகள்",
    "pro.showcase.card.rules.r1": "மதிப்பிடத்தக்கது",
    "pro.showcase.card.rules.r2": "சரியான நேரத்தில்",
    "pro.showcase.card.rules.r3": "விகிதாசார",
    
    "pro.chip": "SETBIN REPAIR",
    "pro.title": "உங்கள் சேவை வணிகத்தை உயர்த்துங்கள்",
    "pro.desc": "பழுதுபார்க்கும் கடைகளுக்கான முழுமையான மேலாண்மை குழாய்.",
    "pro.features.repair": "பழுதுபார்க்கும் கண்காணிப்பு",
    "pro.features.inventory": "இருப்பு மேலாண்மை",
    "pro.features.customer": "வாடிக்கையாளர் தொடர்பு",
    "pro.btn": "மேலாண்மையை தொடங்குங்கள்",
    "ai.chip": "SCHEMIC AI",
    "ai.title": "அடுத்த தலைமுறை நோய் கண்டறிதல்",
    "ai.desc": "வன்பொருள் குறைபாடுகளை துல்லியமாக சுட்டிக்காட்ட AI ஐப் பயன்படுத்தவும்.",
    "ai.features.analysis": "உடனடி பகுப்பாய்வு",
    "ai.features.faults": "குறைகளை கண்டறிதல்",
    "ai.features.solutions": "தீர்வுகள் தரவுத்தளம்",
    "ai.btn": "Schemic AI ஐ முயற்சிக்கவும்",
    "network.chip": "தேசிய நெட்வொர்க்",
    "network.title": "இந்திய நிபுணர்களால் நம்பப்படுகிறது",
    "network.desc": "SETBIN ஐ நம்பியிருக்கும் ஆயிரக்கணக்கான வணிகங்களுடன் இணையுங்கள்.",
    "contact.chip": "தொடர்பு கொள்ள",
    "contact.title": "ஒன்றாக எதிர்காலத்தை உருவாக்குவோம்",
    "contact.desc": "உங்கள் சேவை வணிகத்தை மாற்றத் தயாரா?",
    "contact.info.title": "தொடர்பு விவரங்கள்",
    "contact.info.email": "மின்னஞ்சல் அனுப்புங்கள்",
    "contact.info.phone": "எங்களை அழையுங்கள்",
    "contact.info.address": "எங்களைப் பார்வையிடவும்",
    "contact.form.name": "முழு பெயர்",
    "contact.form.submit": "செய்தி அனுப்பு",
    "cta.title": "புரட்சியை ஏற்படுத்தத் தயாரா?",
    "cta.desc": "SETBIN ஐப் பயன்படுத்தும் ஆயிரக்கணக்கான நிபுணர்களுடன் இணையுங்கள்.",
    "cta.btn.start": "இன்றே தொடங்குங்கள்",
    "cta.btn.contact": "விற்பனை பிரிவை தொடர்பு கொள்ளவும்",

    "contact.form.name_placeholder": "ஜான் டோ",
    "contact.form.email": "மின்னஞ்சல் முகவரி",
    "contact.form.email_placeholder": "john@example.com",
    "contact.form.subject": "பொருள்",
    "contact.form.subject_placeholder": "நாங்கள் உங்களுக்கு எப்படி உதவ முடியும்?",
    "contact.form.message": "செய்தி",
    "contact.form.message_placeholder": "உங்கள் தேவைகளைப் பற்றி எங்களிடம் கூறுங்கள்...",

    "contact.card.office.title": "அலுவலக இருப்பிடம்",
    "contact.card.office.value": "SETTINGS சேவை மையம் எர்ணாகுளம்",
    "contact.card.office.sub": "கொச்சி, கேரளா — இந்தியா",
    "contact.card.direct.title": "நேரடி தொடர்பு",
    "contact.card.direct.sub": "திங்கள்-சனி · காலை 10 – மாலை 7 IST",
    "contact.card.email.title": "நிறுவன மின்னஞ்சல்",
    "contact.card.email.sub": "24 மணி நேரத்திற்குள் பதில்",
    "contact.send_message": "செய்தி அனுப்பு",
    "contact.map.label": "SETBIN // எர்ணாகுளம்",
    "contact.get_directions": "திசைகளைப் பெறுக",

    "network.city.delhi": "டெல்லி",
    "network.city.mumbai": "மும்பை",
    "network.city.bangalore": "பெங்களூரு",
    "network.city.hyderabad": "ஹைதராபாத்",
    "network.city.chennai": "சென்னை",
    "network.city.kolkata": "கொல்கத்தா",
    "network.city.ahmedabad": "அகமதாபாத்",
    "network.city.kochi": "கொச்சி",

    "platform.card1.title": "ஒருங்கிணைந்த மேலாண்மை அமைப்பு",
    "platform.card1.desc": "உங்கள் சேவை வணிகத்தின் ஒவ்வொரு அம்சத்தையும் ஒரே இடத்தில் இணைக்கவும்.",
    "platform.card2.title": "AI-இயங்கும் நோய் கண்டறிதல்",
    "platform.card2.desc": "துல்லியமான சரிசெய்தலுக்கான மேம்பட்ட திட்டவட்டமான பகுப்பாய்வு.",
    "platform.card3.title": "இந்தியாவின் மிகப்பெரிய சப்ளை செயின்",
    "platform.card3.desc": "நாட்டின் சிறந்த சப்ளையர்களிடமிருந்து உயர்தர பாகங்கள் மற்றும் கருவிகளைப் பெறுங்கள்."
  },
  te: {
    "nav.connect": "సెట్‌బిన్ కనెక్ట్",
    "nav.repair": "సెట్‌బిన్ రిపేర్",
    "nav.schemic": "స్కెమిక్ AI",
    "nav.connectBtn": "మాతో కనెక్ట్ అవ్వండి",
    "nav.connectBtnMobile": "కనెక్ట్",
    "hero.stage1.title": "SETBIN",
    "hero.stage1.subtitle": "స్మార్ట్‌ఫోన్ సేవా పరిశ్రమ యొక్క డిజిటల్ వెన్నెముక",
    "hero.stage2.title": "బిలియన్ల విలువైన పరిశ్రమ<br/>మౌలిక సదుపాయాలు లేకుండానే నడుస్తోంది",
    "hero.stage2.subtext": "టెక్నీషియన్లు. భాగాలు. కార్యకలాపాలు. ఇంటెలిజెన్స్.<br/>అన్నీ విడివిడిగా ఉన్నాయి.",
    "hero.stage3.title": "విచ్ఛిన్నం నుండి<br/>నిర్మాణం వరకు",
    "hero.stage3.subtext": "అన్నీ కలిసి పనిచేస్తే ఎలా ఉంటుంది?",
    "hero.stage4.title": "SETBIN పర్యావరణ వ్యవస్థను కలుపుతుంది",
    "hero.stage4.subtext": "విడిభాగాల సేకరణ<br/>సేవా కార్యకలాపాలు<br/>సాంకేతిక ఇంటెలిజెన్స్<br/>అన్నీ ఒకే ప్లాట్‌ఫారమ్‌లో.",
    "hero.stage5.title": "కనెక్ట్ అవ్వండి. నిర్వహించండి.",
    "hero.stage5.subtext": "ఆధునిక మరమ్మతు పరిశ్రమ కోసం<br/>మౌలిక సదుపాయాలు.",
    "hero.stage6.title": "SETBIN",
    "hero.stage6.subtext": "భారతీయ స్మార్ట్‌ఫోన్ సేవా పరిశ్రమ కోసం మౌలిక సదుపాయాలు",
    "hero.stage7.title": "మొబైల్ సేవల భవిష్యత్తును శక్తివంతం చేయడం",
    "hero.stage7.btn": "ప్లాట్‌ఫారమ్‌ను అన్వేషించండి",

    "pro.dashboard.title": "మీ మొత్తం సర్వీస్ బిజినెస్‌ను ఒకే సిస్టమ్‌లో <br/> నిర్వహించండి",
    "pro.dashboard.desc": "జాబ్ ఇన్‌టేక్ నుండి బిల్లింగ్ వరకు, ఇన్వెంటరీ నుండి ఫైనాన్షియల్ ట్రాకింగ్ వరకు — SETBIN మొబైల్ సర్వీస్ సెంటర్ల కోసం ప్రతి ఆపరేషన్‌ను ఒకే అతుకులు లేని వర్క్‌ఫ్లోగా మారుస్తుంది.",
    "pro.btn.cta": "ఆటోమేషన్ ప్రారంభించండి",
    "pro.nav.overview": "ఓవర్‌వ్యూ",
    "pro.nav.daybook": "డేబుక్",
    "pro.nav.services": "సర్వీసెస్",
    "pro.nav.billing": "బిల్లింగ్",
    "pro.nav.expenses": "ఖర్చులు",
    "pro.nav.dues": "బకాయిలు",
    "pro.nav.inventory": "ఇన్వెంటరీ",
    "pro.nav.staff": "స్టాఫ్",
    "pro.nav.customers": "కస్టమర్స్",
    "pro.nav.vendors": "వెండర్స్",
    "pro.nav.reports": "రిపోర్ట్స్",

    "pro.card.revenue.title": "రోజువారీ ఆదాయం",
    "pro.card.revenue.detail": "గత వారం కంటే +15%",
    "pro.card.pending.title": "పెండింగ్ పనులు",
    "pro.card.pending.detail": "4 అత్యవసరం",
    "pro.card.cash_flow.title": "క్యాష్ ఫ్లో",
    "pro.card.cash_flow.detail": "చివరి సమకాలీకరణ 2 సెకన్ల క్రితం",
    "pro.card.transactions.title": "లావాదేవీలు",
    "pro.card.transactions.detail": "UPI ప్రధానం",
    "pro.card.avg_repair.title": "సగటు మరమ్మతు సమయం",
    "pro.card.avg_repair.detail": "లక్ష్యం కంటే -5 నిమిషాలు",
    "pro.card.ready_jobs.title": "సిద్ధంగా ఉన్న పనులు",
    "pro.card.ready_jobs.detail": "డెలివరీ కోసం నిరీక్షణ",
    "pro.card.outstanding.title": "బకాయి మొత్తం",
    "pro.card.outstanding.detail": "5 కస్టమర్లు",
    "pro.card.inv_match.title": "ఇన్వెంటరీ మ్యాచ్",
    "pro.card.inv_match.detail": "GST ధృవీకరించబడింది",
    "pro.card.exp_total.title": "మొత్తం ఖర్చు",
    "pro.card.exp_total.detail": "నెలవారీ ఖర్చు",
    "pro.card.rent_paid.title": "అద్దె చెల్లించబడింది",
    "pro.card.rent_paid.detail": "28 రోజుల్లో చెల్లించాలి",
    "pro.card.receivables.title": "రావలసినవి",
    "pro.card.receivables.detail": "4 పెండింగ్",
    "pro.card.payables.title": "చెల్లించవలసినవి",
    "pro.card.payables.detail": "3 రోజుల్లో",
    "pro.card.stock_val.title": "స్టాక్ విలువ",
    "pro.card.stock_val.detail": "450 SKUలు",
    "pro.card.low_stock.title": "స్టాక్ తక్కువగా ఉంది",
    "pro.card.low_stock.detail": "అలర్ట్ యాక్టివ్",
    "pro.card.efficiency.title": "సామర్థ్యం",
    "pro.card.efficiency.detail": "టీమ్ సగటు",
    "pro.card.active_staff.title": "యాక్టివ్ స్టాఫ్",
    "pro.card.active_staff.detail": "4 అందుబాటులో ఉన్నారు",
    "pro.card.customers.title": "కస్టమర్లు",
    "pro.card.customers.detail": "పునరావృతమయ్యే",
    "pro.card.avg_ltv.title": "సగటు విలువ",
    "pro.card.avg_ltv.detail": "5% పెరిగింది",
    "pro.card.vendors.title": "వెండర్స్",
    "pro.card.vendors.detail": "3 యాక్టివ్ ఆర్డర్లు",
    "pro.card.lead_time.title": "లీడ్ టైమ్",
    "pro.card.lead_time.detail": "టాప్ టైర్",
    "pro.card.analytics.title": "అనలిటిక్స్",
    "pro.card.analytics.detail": "రియల్-టైమ్",
    "pro.card.uptime.title": "అప్‌టైమ్",
    "pro.card.uptime.detail": "గ్లోబల్ క్లస్టర్",

    "ai.card1.title": "AI-ఆధారిత ఫాల్ట్ డయాగ్నోస్టిక్స్",
    "ai.card1.desc": "న్యూరల్ విశ్లేషణతో మైక్రో-లెవల్ సర్క్యూట్ విఫలాలను ఖచ్చితంగా గుర్తించండి.",
    "ai.card2.title": "రియల్-టైమ్ థర్మల్ మ్యాపింగ్",
    "ai.card2.desc": "ప్రిడిక్టివ్ హీట్-సిగ్నేచర్ మోడలింగ్ ఉపయోగించి ఓవర్ హీటింగ్ భాగాలను గుర్తించండి.",
    "ai.card3.title": "స్మార్ట్ రిపేర్ గైడెన్స్",
    "ai.card3.desc": "సంక్లిష్టమైన IC-స్థాయి మరమ్మతుల కోసం దశల వారీ సూచనలను పొందండి.",
    "ai.card4.title": "PCB ఇంటిగ్రిటీ టెస్టింగ్",
    "ai.card4.desc": "బోర్డు ట్రేస్ మరియు కనెక్టివిటీ యొక్క ఆటోమేటెడ్ ధృవీకరణ.",
    "ai.card5.title": "నాలెడ్జ్-బేస్ ఇంటిగ్రేషన్",
    "ai.card5.desc": "తెలిసిన హార్డ్‌వేర్ వైఫల్యం నమూనాల గ్లోబల్ డేటాబేస్‌కు కనెక్ట్ చేయబడింది.",
    "ai.diagnosis.complete": "డయాగ్నోస్టిక్స్ పూర్తయింది: ఫాల్ట్ గుర్తించబడింది",
    "ai.diagnosis.sub": "పరిష్కారం సర్వీస్ పైప్‌లైన్‌కు మ్యాప్ చేయబడింది.",

    "footer.desc": "మొబైల్ సర్వీస్ సెంటర్లు, టెక్నీషియన్లు మరియు విడిభాగాల సరఫరాదారుల కోసం భారతదేశం యొక్క మొదటి ఏకీకృత మౌలిక సదుపాయాలు.",
    "footer.address": "SEBIN కనెక్ట్ ప్రైవేట్ లిమిటెడ్<br />కొచ్చి, ఎర్నాకులం, కేరళ — భారతదేశం",
    "footer.platform": "ప్లాట్‌ఫారమ్",
    "footer.software": "వర్క్‌షాప్ సాఫ్ట్‌వేర్",
    "footer.network": "కనెక్ట్ నెట్‌వర్క్",
    "footer.company": "కంపెనీ",
    "footer.links.diagnostics": "మదర్ బోర్డ్ డయాగ్నోస్టిక్స్",
    "footer.links.repairs": "IC స్థాయి రిపేర్",
    "footer.links.sourcing": "పార్ట్స్ సోర్సింగ్",
    "footer.links.erp": "సర్వీస్ సెంటర్ ERP",
    "footer.links.inventory": "ఇన్వెంటరీ సింక్",
    "footer.links.billing": "బిల్లింగ్ & ఇన్వాయిస్",
    "footer.links.suppliers": "ధృవీకరించబడిన సరఫరాదారులు",
    "footer.links.logistics": "లాజిస్టిక్స్ భాగస్వాములు",
    "footer.links.marketplace": "B2B మార్కెట్‌ప్లేస్",
    "footer.links.about": "SETBIN గురించి",
    "footer.links.privacy": "గోప్యతా విధానం",
    "footer.links.terms": "సేవా నిబంధనలు",
    "footer.links.disclaimer": "నిరాకరణ",
    "footer.rights": "సర్వ హక్కులూ ప్రత్యేకించబడినవి."
,
    "platform.chip": "ప్లాట్‌ఫారమ్",
    "platform.title": "తదుపరి తరం సేవను శక్తివంతం చేయడం",
    "platform.desc": "స్మార్ట్‌ఫోన్ సేవా పరిశ్రమ కోసం రూపొందించబడిన పర్యావరణ వ్యవస్థ.",
    "platform.card1.title": "ఏకీకృత నిర్వహణ",
    "platform.card1.desc": "వ్యాపారంలోని అన్ని అంశాలను ఒకే చోట కనెక్ట్ చేయండి.",
    "platform.card2.title": "AI-ఆధారిత రోగ నిర్ధారణ",
    "platform.card2.desc": "ఖచ్చితమైన సమస్య గుర్తింపు కోసం అధునాతన విశ్లేషణ.",
    "platform.card3.title": "భారతీయ సప్లై చైన్",
    "platform.card3.desc": "ధృవీకరించబడిన సరఫరాదారుల నుండి భాగాలు పొందండి.",

    "pillars.chip": "ఆవిష్కరణల మూలస్తంభాలు",
    "pillars.title": "మరమ్మత్తు భవిష్యత్తును <br/>నిర్మించడం.",
    "pillars.desc": "సరఫరా గొలుసులు, సేవా కేంద్రాలు మరియు AI రోగ నిర్ధారణను మేము ఒకే చోట కలుపుతున్నాము.",
    "pillars.footer": "స్కేల్ కోసం నిర్మించబడింది • ఇంటెలిజెన్స్ శక్తి • నిపుణుల విశ్వాసం",
    "pillars.connect.subtitle": "పర్యావరణ వ్యవస్థ",
    "pillars.repair.subtitle": "మౌలిక సదుపాయాలు",
    "pillars.schemic.subtitle": "ఇంటెలిజెన్స్",
    "connect.chip": "SETBIN CONNECT",
    "connect.title": "భారతీయ B2B నెట్‌వర్కింగ్",
    "connect.desc": "ప్రపంచంలోనే అతిపెద్ద నెట్‌వర్క్‌లో చేరండి.",
    "connect.features.suppliers": "సరఫరాదారు యాక్సెస్",
    "connect.features.tools": "సాధనాల సేకరణ",
    "connect.features.wholesale": "టోకు ధరలు",
    "connect.btn": "నెట్‌వర్క్‌లో చేరండి",

    "connect.story.chip": "SETBIN CONNECT",
    "connect.story.s1.title": "మొబైల్ సేవ కోసం భారతదేశం యొక్క B2B నెట్‌వర్క్",
    "connect.story.s1.desc": "టెక్నీషియన్లు, సేవా కేంద్రాలు మరియు విడి భాగాల సరఫరాదారులను ఒకే నిర్మాణాత్మక పర్యావరణ వ్యవస్థలో కనెక్ట్ చేసే ధృవీకరించబడిన ప్లాట్‌ఫారమ్.",
    "connect.story.s2.tag": "పాత పద్ధతి",
    "connect.story.s2.title": "సోర్సింగ్ ఇంకా మాన్యువల్ & అస్తవ్యస్తంగా ఉంది",
    "connect.story.s2.p1": "రియల్-టైమ్ లభ్యత లేదు",
    "connect.story.s2.p2": "ధర స్పష్టత లేదు",
    "connect.story.s2.p3": "నకిలీ విడిభాగాల ప్రమాదం ఎక్కువ",
    "connect.story.s2.p4": "అంతులేని కాల్‌లు మరియు సందేశాలు",
    "connect.story.s3.tag": "పరిష్కారం",
    "connect.story.s3.title": "గందరగోళం నుండి నిర్మాణం వరకు",
    "connect.story.s3.desc": "నమ్మకమైన సరఫరాదారుల నుండి ధృవీకరించబడిన విడిభాగాలను వెతకండి, పోల్చండి మరియు వెంటనే పొందండి.",
    "connect.story.s4.title": "నేరుగా సరఫరాదారు యాక్సెస్",
    "connect.story.s4.desc": "జాప్యం లేకుండా భారతదేశం అంతటా ధృవీకరించబడిన హోల్‌సేలర్లతో నేరుగా కనెక్ట్ అవ్వండి. దళారీలు లేరు.",
    "connect.story.s5.title": "రియల్-టైమ్ ఇన్వెంటరీ",
    "connect.story.s5.desc": "ఆర్డర్ చేయడానికి ముందు ఏమి అందుబాటులో ఉందో సరిగ్గా తెలుసుకోండి. లైవ్ స్టాక్ సూచికలు అనిశ్చితిని తొలగిస్తాయి.",
    "connect.story.s5.feed": "నేరు స్టాక్ ఫీడ్",
    "connect.story.s5.stock": "స్టాక్‌లో ఉంది",
    "connect.story.s5.p1": "iPhone 13 Pro స్క్రీన్",
    "connect.story.s5.p2": "Samsung S22 బ్యాటరీ",
    "connect.story.s5.p3": "Type-C పోర్ట్ IC",
    "connect.story.s6.title": "నిజమైన హోల్‌సేల్ ధర",
    "connect.story.s6.desc": "వెంటనే పారదర్శక B2B ధరను యాక్సెస్ చేయండి. ధృవీకరించబడిన సరఫరాదారుల అంతటా రేట్లను పోల్చండి.",
    "connect.story.s6.retail": "రిటైల్ సరాసరి",
    "connect.story.s7.title": "ధృవీకరించబడిన అసలైన విడిభాగాలు",
    "connect.story.s7.desc": "నకిలీ భాగాల ప్రమాదాన్ని తగ్గించండి. OEM మరియు అధిక నాణ్యత అఫ్టర్‌మార్కెట్ విడిభాగాలను నిర్ధారించడానికి మా సరఫరాదారు నెట్‌వర్క్ కఠినంగా పరీక్షించబడింది.",
    "connect.story.s8.title": "గంటల నుండి నిమిషాలకు",
    "connect.story.s8.desc": "ఒకప్పుడు గంటల కాల్‌లు అవసరమైనది ఇప్పుడు భారతదేశం యొక్క ధృవీకరించబడిన ప్లాట్‌ఫారమ్‌లో సెకన్లలో జరుగుతుంది.",
    "connect.story.s8.btn": "కనెక్ట్ ఎకోసిస్టమ్ అన్వేషించండి",

    // SaaS Showcase Rebrand
    "pro.showcase.heading": "మీ మొత్తం సర్వీస్ బిజినెస్‌ను ఒకే సిస్టమ్‌లో నిర్వహించండి",
    "pro.showcase.subheading": "SETBIN REPAIR",
    "pro.showcase.desc": "జాబ్ ఇన్‌టేక్ నుండి బిల్లింగ్ వరకు, ఇన్వెంటరీ నుండి ఫైనాన్షియల్ ట్రాకింగ్ వరకు — SETBIN మొబైల్ సర్వీస్ సెంటర్ల కోసం ప్రతి ఆపరేషన్‌ను ఒకే అతుకులు లేని వర్క్‌ఫ్లోగా మారుస్తుంది.",
    "pro.showcase.cta.demo": "డెమో పొందండి",
    "pro.showcase.cta.free": "ఉచిత ట్రయల్ ప్రారంభించండి",
    "pro.showcase.nav.daybook": "డేబుక్",
    "pro.showcase.nav.billing": "బిల్లింగ్",
    "pro.showcase.nav.inventory": "ఇన్వెంటరీ",
    "pro.showcase.nav.reports": "రిపోర్ట్స్",
    "pro.showcase.nav.dues": "బకాయిలు",
    "pro.showcase.nav.exp": "ఖర్చులు",
    "pro.showcase.card.rev.title": "రాబడి",
    "pro.showcase.card.rev.amt": "$198.5M",
    "pro.showcase.card.due.title": "బకాయిలు",
    "pro.showcase.card.due.amt": "$15.3M",
    "pro.showcase.card.rules.title": "సేవా నియమాలు",
    "pro.showcase.card.rules.r1": "రేటబుల్",
    "pro.showcase.card.rules.r2": "పాయింట్_ఇన్_టైమ్",
    "pro.showcase.card.rules.r3": "ప్రొపోర్షనల్",
    
    "pro.chip": "SETBIN REPAIR",
    "pro.title": "మీ సేవా వ్యాపారాన్ని మెరుగుపరచుకోండి",
    "pro.desc": "మరమ్మతు దుకాణాల కోసం పూర్తి నిర్వహణ పైప్‌లైన్.",
    "pro.features.repair": "మరమ్మతు ట్రాకింగ్",
    "pro.features.inventory": "ఇన్వెంటరీ మేనేజ్మెంట్",
    "pro.features.customer": "కస్టమర్ కమ్యూనికేషన్",
    "pro.btn": "నిర్వహణను ప్రారంభించండి",
    "ai.chip": "SCHEMIC AI",
    "ai.title": "నెక్స్ట్-జెన్ రోగనిర్ధారణ",
    "ai.desc": "హార్డ్‌వేర్ లోపాలను గుర్తించడానికి AIని ఉపయోగించండి.",
    "ai.features.analysis": "తక్షణ విశ్లేషణ",
    "ai.features.faults": "లోపాల గుర్తింపు",
    "ai.features.solutions": "పరిష్కారాల డేటాబేస్",
    "ai.btn": "Schemic AIని ప్రయత్నించండి",
    "network.chip": "జాతీయ నెట్‌వర్క్",
    "network.title": "నిపుణులచే విశ్వసించబడింది",
    "network.desc": "SETBINపై ఆధారపడే వేలాది వ్యాపారాలలో చేరండి.",
    "contact.chip": "సంప్రదించండి",
    "contact.title": "కలిసి భవిష్యత్తును నిర్మిద్దాం",
    "contact.desc": "వ్యాపారాన్ని మార్చడానికి సిద్ధంగా ఉన్నారా?",
    "contact.info.title": "సంప్రదింపు సమాచారం",
    "contact.info.email": "ఈమెయిల్ చేయండి",
    "contact.info.phone": "కాల్ చేయండి",
    "contact.info.address": "మమ్మల్ని సందర్శించండి",
    "contact.form.name": "పూర్తి పేరు",
    "contact.form.submit": "సందేశం పంపండి",
    "cta.title": "విప్లవం తీసుకురావడానికి సిద్ధంగా ఉన్నారా?",
    "cta.desc": "SETBINని ఉపయోగిస్తున్న నిపుణులతో చేరండి.",
    "cta.btn.start": "ఈరోజే ప్రారంభించండి",
    "cta.btn.contact": "సేల్స్‌ను సంప్రదించండి",

    "contact.form.name_placeholder": "జాన్ డో",
    "contact.form.email": "ఈమెయిల్ చిరునామా",
    "contact.form.email_placeholder": "john@example.com",
    "contact.form.subject": "విషయం",
    "contact.form.subject_placeholder": "మేము మీకు ఎలా సహాయం చేయగలము?",
    "contact.form.message": "సందేశం",
    "contact.form.message_placeholder": "మీ అవసరాల గురించి మాకు చెప్పండి...",

    "contact.card.office.title": "కార్యాలయ స్థానం",
    "contact.card.office.value": "SETTINGS సర్వీస్ సెంటర్ ఎర్నాకులం",
    "contact.card.office.sub": "కొచ్చి, కేరళ — భారతదేశం",
    "contact.card.direct.title": "నేరుగా సంప్రదించండి",
    "contact.card.direct.sub": "సోమ-శని · ఉదయం 10 – సాయంత్రం 7 IST",
    "contact.card.email.title": "ఎంటర్‌ప్రైజ్ ఈమెయిల్",
    "contact.card.email.sub": "24 గంటల్లో ప్రత్యుత్తరం",
    "contact.send_message": "సందేశం పంపండి",
    "contact.map.label": "SETBIN // ఎర్నాకులం",
    "contact.get_directions": "దిశలను పొందండి",

    "network.city.delhi": "ఢిల్లీ",
    "network.city.mumbai": "ముంబై",
    "network.city.bangalore": "బెంగళూరు",
    "network.city.hyderabad": "హైదరాబాద్",
    "network.city.chennai": "చెన్నై",
    "network.city.kolkata": "కోల్‌కతా",
    "network.city.ahmedabad": "అహ్మదాబాద్",
    "network.city.kochi": "కొచ్చి",

    "platform.pillar1.title": "SETBIN కనెక్ట్",
    "platform.pillar1.subtitle": "ధృవీకరించబడిన స్పేర్ పార్ట్స్ మార్కెట్‌ప్లేస్",
    "platform.pillar1.body": "నమ్మకమైన సరఫరాదారులతో కనెక్ట్ అవ్వండి. అసలైన భాగాలను వేగంగా పొందండి.",
    "platform.pillar2.title": "SETBIN రిపేర్",
    "platform.pillar2.subtitle": "సర్వీస్ సెంటర్ ఆపరేటింగ్ సిస్టమ్",
    "platform.pillar2.body": "పనులను నిర్వహించండి, రిపేర్లను ట్రాక్ చేయండి, ఇన్వెంటరీని నియంత్రించండి.",
    "platform.pillar3.title": "SCHEMIC AI",
    "platform.pillar3.subtitle": "AI-ఆధారిత డయాగ్నోస్టిక్స్",
    "platform.pillar3.body": "స్కెమాటిక్ ఉపయోగించి లోపాలను ఖచ్చితంగా గుర్తించండి.",
    "platform.viewMore": "మరింత చూడండి →"
  },
  kn: {
    "nav.connect": "ಸೆಟ್‌ಬಿನ್ ಕನೆಕ್ಟ್",
    "nav.repair": "ಸೆಟ್‌ಬಿನ್ ರಿಪೇರಿ",
    "nav.schemic": "ಸ್ಕೆಮಿಕ್ AI",
    "nav.connectBtn": "ನಮ್ಮೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಿ",
    "nav.connectBtnMobile": "ಸಂಪರ್ಕಿಸಿ",
    "hero.stage1.title": "SETBIN",
    "hero.stage1.subtitle": "ಸ್ಮಾರ್ಟ್‌ಫೋನ್ ಸೇವಾ ಉದ್ಯಮದ ಡಿಜಿಟಲ್ ಬೆನ್ನೆಲುಬು",
    "hero.stage2.title": "ಬಿಲಿಯನ್ ಡಾಲರ್ ಉದ್ಯಮ<br/>ಮೂಲಸೌಕರ್ಯವಿಲ್ಲದೆ ನಡೆಯುತ್ತಿದೆ",
    "hero.stage2.subtext": "ತಂತ್ರಜ್ಞರು. ಭಾಗಗಳು. ಕಾರ್ಯಾಚರಣೆಗಳು. ಬುದ್ಧಿವಂತಿಕೆ.<br/>ಎಲ್ಲವೂ ಕಡಿತಗೊಂಡಿದೆ.",
    "hero.stage3.title": "ವಿಘಟನೆಯಿಂದ<br/>ರಚನೆಯವರೆಗೆ",
    "hero.stage3.subtext": "ಎಲ್ಲವೂ ಒಟ್ಟಾಗಿ ಕೆಲಸ ಮಾಡಿದರೆ ಏನಾಗುತ್ತದೆ?",
    "hero.stage4.title": "SETBIN ಪರಿಸರ ವ್ಯವಸ್ಥೆಯನ್ನು ಸಂಪರ್ಕಿಸುತ್ತದೆ",
    "hero.stage4.subtext": "ಬಿಡಿಭಾಗಗಳ ಸಂಗ್ರಹಣೆ<br/>ಸೇವಾ ಕಾರ್ಯಾಚರಣೆಗಳು<br/>ತಾಂತ್ರಿಕ ಬುದ್ಧಿವಂತಿಕೆ<br/>ಎಲ್ಲವೂ ಒಂದೇ ವೇದಿಕೆಯಲ್ಲಿ.",
    "hero.stage5.title": "ಸಂಪರ್ಕಿಸಿ. ನಿರ್ವಹಿಸಿ.",
    "hero.stage5.subtext": "ಆಧುನಿಕ ರಿಪೇರಿ ಉದ್ಯಮಕ್ಕಾಗಿ<br/>ಮೂಲಸೌಕರ್ಯ.",
    "hero.stage6.title": "SETBIN",
    "hero.stage6.subtext": "ಭಾರತದ ಸ್ಮಾರ್ಟ್‌ಫೋನ್ ಸೇವಾ ಉದ್ಯಮಕ್ಕೆ ಮೂಲಸೌಕರ್ಯ",
    "hero.stage7.title": "ಮೊಬೈಲ್ ಸೇವೆಯ ಭವಿಷ್ಯವನ್ನು ಸಬಲೀಕರಣಗೊಳಿಸುವುದು",
    "hero.stage7.btn": "ವೇದಿಕೆಯನ್ನು ಅನ್ವೇಷಿಸಿ",

    "pro.dashboard.title": "ನಿಮ್ಮ ಇಡೀ ಸೇವಾ ವ್ಯವಹಾರವನ್ನು ಒಂದೇ ಸಿಸ್ಟಮ್‌ನಲ್ಲಿ <br/> ನಡೆಸಿ",
    "pro.dashboard.desc": "ಕೆಲಸದ ಪ್ರವೇಶದಿಂದ ಬಿಲ್ಲಿಂಗ್‌ವರೆಗೆ, ದಾಸ್ತಾನುಗಳಿಂದ ಹಣಕಾಸಿನ ಟ್ರ್ಯಾಕಿಂಗ್‌ವರೆಗೆ — SETBIN ಮೊಬೈಲ್ ಸೇವಾ ಕೇಂದ್ರಗಳ ಪ್ರತಿ ಕಾರ್ಯಾಚರಣೆಯನ್ನು ಒಂದು ಸುಗಮ ಕೆಲಸದ ಹರಿವಿನೊಳಗೆ ತರುತ್ತದೆ.",
    "pro.btn.cta": "ಸ್ವಯಂಚಾಲಿತತೆಯನ್ನು ಪ್ರಾರಂಭಿಸಿ",
    "pro.nav.overview": "ಅವಲೋಕನ",
    "pro.nav.daybook": "ಡೇ ಬುಕ್",
    "pro.nav.services": "ಸೇವೆಗಳು",
    "pro.nav.billing": "ಬಿಲ್ಲಿಂಗ್",
    "pro.nav.expenses": "ವೆಚ್ಚಗಳು",
    "pro.nav.dues": "ಬಾಕಿ",
    "pro.nav.inventory": "ದಾಸ್ತಾನು",
    "pro.nav.staff": "ಸಿಬ್ಬಂದಿ",
    "pro.nav.customers": "ಗ್ರಾಹಕರು",
    "pro.nav.vendors": "ಮಾರಾಟಗಾರರು",
    "pro.nav.reports": "ವರದಿಗಳು",

    "pro.card.revenue.title": "ದೈನಂದಿನ ಆದಾಯ",
    "pro.card.revenue.detail": "ಕಳೆದ ವಾರಕ್ಕಿಂತ +15%",
    "pro.card.pending.title": "ಬಾಕಿ ಇರುವ ಕೆಲಸಗಳು",
    "pro.card.pending.detail": "4 ತುರ್ತು",
    "pro.card.cash_flow.title": "ನಗದು ಹರಿವು",
    "pro.card.cash_flow.detail": "ಕೊನೆಯ ಸಿಂಕ್ 2 ಸೆಕೆಂಡುಗಳ ಹಿಂದೆ",
    "pro.card.transactions.title": "ವ್ಯವಹಾರಗಳು",
    "pro.card.transactions.detail": "UPI ಪ್ರಾಬಲ್ಯ",
    "pro.card.avg_repair.title": "ಸರಾಸರಿ ರಿಪೇರಿ ಸಮಯ",
    "pro.card.avg_repair.detail": "ಗುರಿಗಿಂತ -5 ನಿಮಿಷಗಳು",
    "pro.card.ready_jobs.title": "ಸಿದ್ಧ ಕೆಲಸಗಳು",
    "pro.card.ready_jobs.detail": "ವಿತರಣೆಗೆ ಕಾಯುತ್ತಿದೆ",
    "pro.card.outstanding.title": "ಬಾಕಿ ಮೊತ್ತ",
    "pro.card.outstanding.detail": "5 ಗ್ರಾಹಕರು",
    "pro.card.inv_match.title": "ದಾಸ್ತಾನು ಹರಿವು",
    "pro.card.inv_match.detail": "GST ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
    "pro.card.exp_total.title": "ಒಟ್ಟು ವೆಚ್ಚ",
    "pro.card.exp_total.detail": "ಮಾಸಿಕ ವೆಚ್ಚ",
    "pro.card.rent_paid.title": "ಬಾಡಿಗೆ ಪಾವತಿಸಲಾಗಿದೆ",
    "pro.card.rent_paid.detail": "28 ದಿನಗಳಲ್ಲಿ ಬಾಕಿ ಇದೆ",
    "pro.card.receivables.title": "ಪಡೆಯಬೇಕಾದವುಗಳು",
    "pro.card.receivables.detail": "4 ಬಾಕಿ ಇದೆ",
    "pro.card.payables.title": "ಪಾವತಿಸಬೇಕಾದವುಗಳು",
    "pro.card.payables.detail": "3 ದಿನಗಳಲ್ಲಿ",
    "pro.card.stock_val.title": "ದಾಸ್ತಾನು ಮೌಲ್ಯ",
    "pro.card.stock_val.detail": "450 SKU ಗಳು",
    "pro.card.low_stock.title": "ದಾಸ್ತಾನು ಕಡಿಮೆಯಿದೆ",
    "pro.card.low_stock.detail": "ಎಚ್ಚರಿಕೆ ಸಕ್ರಿಯವಾಗಿದೆ",
    "pro.card.efficiency.title": "ದಕ್ಷತೆ",
    "pro.card.efficiency.detail": "ತಂಡದ ಸರಾಸರಿ",
    "pro.card.active_staff.title": "ಸಕ್ರಿಯ ಸಿಬ್ಬಂದಿ",
    "pro.card.active_staff.detail": "4 ಜನರು ಲಭ್ಯವಿದ್ದಾರೆ",
    "pro.card.customers.title": "ಗ್ರಾಹಕರು",
    "pro.card.customers.detail": "ಮರುಕಳಿಸುವವರು",
    "pro.card.avg_ltv.title": "ಸರಾಸರಿ ಮೌಲ್ಯ",
    "pro.card.avg_ltv.detail": "5% ಹೆಚ್ಚಾಗಿದೆ",
    "pro.card.vendors.title": "ಮಾರಾಟಗಾರರು",
    "pro.card.vendors.detail": "3 ಸಕ್ರಿಯ ಆರ್ಡರ್‌ಗಳು",
    "pro.card.lead_time.title": "ಲೀಡ್ ಟೈಮ್",
    "pro.card.lead_time.detail": "ಉನ್ನತ ಮಟ್ಟದ",
    "pro.card.analytics.title": "ಅನಾಲಿಟಿಕ್ಸ್",
    "pro.card.analytics.detail": "ನೈಜ ಸಮಯ",
    "pro.card.uptime.title": "ಅಪ್‌ಟೈಮ್",
    "pro.card.uptime.detail": "ಜಾಗತಿಕ ಕ್ಲಸ್ಟರ್",

    "ai.card1.title": "AI-ಚಾಲಿತ ದೋಷ ರೋಗನಿರ್ಣಯ",
    "ai.card1.desc": "ನರಗಳ ವಿಶ್ಲೇಷಣೆಯೊಂದಿಗೆ ಮೈಕ್ರೋ-ಲೆವೆಲ್ ಸರ್ಕ್ಯೂಟ್ ವೈಫಲ್ಯಗಳನ್ನು ನಿಖರವಾಗಿ ಗುರುತಿಸಿ.",
    "ai.card2.title": "ನೈಜ ಸಮಯದ ಉಷ್ಣ ಮ್ಯಾಪಿಂಗ್",
    "ai.card2.desc": "ಭವಿಷ್ಯಸೂಚಕ ಶಾಖ-ಸಹಿ ಮಾದರಿಯನ್ನು ಬಳಸಿಕೊಂಡು ಅತಿಯಾಗಿ ಕಾಯುತ್ತಿರುವ ಘಟಕಗಳನ್ನು ಗುರುತಿಸಿ.",
    "ai.card3.title": "ಸ್ಮಾರ್ಟ್ ರಿಪೇರಿ ಮಾರ್ಗದರ್ಶನ",
    "ai.card3.desc": "ಸಂಕೀರ್ಣ IC-ಮಟ್ಟದ ರಿಪೇರಿಗಳಿಗಾಗಿ ಹಂತ-ಹಂತದ ಸೂಚನೆಗಳನ್ನು ಪಡೆಯಿರಿ.",
    "ai.card4.title": "PCB ಸಮಗ್ರತೆಯ ಪರೀಕ್ಷೆ",
    "ai.card4.desc": "ಬೋರ್ಡ್ ಟ್ರೇಸ್ ಮತ್ತು ಕನೆಕ್ಟಿವಿಟಿಯ ಸ್ವಯಂಚಾಲಿತ ಪರಿಶೀಲನೆ.",
    "ai.card5.title": "ಜ್ಞಾನ-ಆಧಾರಿತ ಏಕೀಕರಣ",
    "ai.card5.desc": "ತಿಳಿದಿರುವ ಹಾರ್ಡ್‌ವೇರ್ ವೈಫಲ್ಯದ ಮಾದರಿಗಳ ಜಾಗತಿಕ ಡೇಟಾಬೇಸ್‌ಗೆ ಸಂಪರ್ಕಿಸಲಾಗಿದೆ.",
    "ai.diagnosis.complete": "ರೋಗನಿರ್ಣಯ ಪೂರ್ಣಗೊಂಡಿದೆ: ದೋಷ ಗುರುತಿಸಲಾಗಿದೆ",
    "ai.diagnosis.sub": "ಪರಿಹಾರವನ್ನು ಸೇವಾ ಪೈಪ್‌ಲೈನ್‌ಗೆ ಮ್ಯಾಪ್ ಮಾಡಲಾಗಿದೆ.",

    "footer.desc": "ಮೊಬೈಲ್ ಸೇವಾ ಕೇಂದ್ರಗಳು, ತಂತ್ರಜ್ಞರು ಮತ್ತು ಬಿಡಿಭಾಗಗಳ ಪೂರೈಕೆದಾರರಿಗಾಗಿ ಭಾರತದ ಮೊದಲ ಸಂಯೋಜಿತ ಮೂಲಸೌಕರ್ಯ.",
    "footer.address": "SETBIN ಕನೆಕ್ಟ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್<br />ಕೊಚ್ಚಿ, ಎರ್ನಾಕುಲಂ, ಕೇರಳ — ಭಾರತ",
    "footer.platform": "ವೇದಿಕೆ",
    "footer.software": "ಕಾರ್ಯಾಗಾರ ಸಾಫ್ಟ್‌ವೇರ್",
    "footer.network": "ಕನೆಕ್ಟ್ ನೆಟ್‌ವರ್ಕ್",
    "footer.company": "ಕಂಪನಿ",
    "footer.links.diagnostics": "ಮದರ್‌ಬೋರ್ಡ್ ರೋಗನಿರ್ಣಯ",
    "footer.links.repairs": "IC ಮಟ್ಟದ ರಿಪೇರಿ",
    "footer.links.sourcing": "ಭಾಗಗಳ ಸಂಗ್ರಹಣೆ",
    "footer.links.erp": "ಸೇವಾ ಕೇಂದ್ರ ERP",
    "footer.links.inventory": "ದಾಸ್ತಾನು ಸಿಂಕ್",
    "footer.links.billing": "ಬಿಲ್ಲಿಂಗ್ ಮತ್ತು ಇನ್ವಾಯ್ಸಿಂಗ್",
    "footer.links.suppliers": "ಪರಿಶೀಲಿಸಿದ ಪೂರೈಕೆದಾರರು",
    "footer.links.logistics": "ಲಾಜಿಸ್ಟಿಕ್ಸ್ ಪಾಲುದಾರರು",
    "footer.links.marketplace": "B2B ಮಾರುಕಟ್ಟೆ",
    "footer.links.about": "SETBIN ಬಗ್ಗೆ",
    "footer.links.privacy": "ಗೌಪ್ಯತಾ ನೀತಿ",
    "footer.links.terms": "ಸೇವಾ ನಿಯಮಗಳು",
    "footer.links.disclaimer": "ಹಕ್ಕುತ್ಯಾಗ",
    "footer.rights": "ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ."
,
    "platform.chip": "ವೇದಿಕೆ",
    "platform.title": "ಸೇವೆಯನ್ನು ಸಬಲೀಕರಣಗೊಳಿಸುವುದು",
    "platform.pillar2.title": "SETBIN REPAIR",
    "platform.pillar2.subtitle": "ಸೇವಾ ಕೇಂದ್ರ ಕಾರ್ಯನಿರ್ವಹಣಾ ವ್ಯವಸ್ಥೆ",
    "platform.pillar2.body": "ಕೆಲಸಗಳನ್ನು ನಿರ್ವಹಿಸಿ, ರಿಪೇರಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ, ದಾಸ್ತಾನು ನಿಯಂತ್ರಿಸಿ ಮತ್ತು ನಿಮ್ಮ ಕೆಲಸದ ಹರಿವನ್ನು ಸುಗಮಗೊಳಿಸಿ.",
    "platform.pillar3.title": "SCHEMIC AI",
    "platform.pillar3.subtitle": "AI-ಚಾಲಿತ ರೋಗನಿರ್ಣಯ ಬುದ್ಧಿವಂತಿಕೆ",
    "platform.pillar3.body": "ಪ್ರಯೋಗ-ಮತ್ತು-ದೋಷ ರಿಪೇರಿಗಳ ಬದಲಿಗೆ ಸ್ಕೆಮ್ಯಾಟಿಕ್ ಲಾಜಿಕ್ ಬಳಸಿ ದೋಷಗಳನ್ನು ಗುರುತಿಸಿ.",
    "platform.viewMore": "ಇನ್ನಷ್ಟು ನೋಡಿ →",

    "pillars.chip": "ನಾವೀನ್ಯತೆಯ ಸ್ತಂಭಗಳು",
    "pillars.title": "ರಿಪೇರಿ ಭವಿಷ್ಯವನ್ನು <br/>ನಿರ್ಮಿಸುವುದು.",
    "pillars.desc": "ಪೂರೈಕೆ ಸರಪಳಿಗಳು, ಸೇವಾ ಕೇಂದ್ರಗಳು ಮತ್ತು AI ರೋಗನಿರ್ಣಯವನ್ನು ಒಂದು ವೇದಿಕೆಯಲ್ಲಿ ನಾವು ತರುತ್ತಿದ್ದೇವೆ.",
    "pillars.footer": "ಬೆಳವಣಿಗೆಗಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ • ಬುದ್ಧಿವಂತಿಕೆಯಿಂದ ಚಾಲಿತ • ತಜ್ಞರ ವಿಶ್ವಾಸ",
    "pillars.connect.subtitle": "ಪರಿಸರ ವ್ಯವಸ್ಥೆ",
    "pillars.repair.subtitle": "ಮೂಲಸೌಕರ್ಯ",
    "pillars.schemic.subtitle": "ಬುದ್ಧಿವಂತಿಕೆ",
    "connect.chip": "SETBIN CONNECT",
    "connect.title": "ಭಾರತದ B2B ನೆಟ್‌ವರ್ಕಿಂಗ್",
    "connect.desc": "ಭಾರತದ ಅತಿದೊಡ್ಡ ನೆಟ್‌ವರ್ಕ್‌ಗೆ ಸೇರಿ.",
    "connect.features.suppliers": "ನೇರ ಪೂರೈಕೆದಾರ ಪ್ರವೇಶ",
    "connect.features.tools": "ಸಾಧನ ಸಂಗ್ರಹಣೆ",
    "connect.features.wholesale": "ಸಗಟು ಬೆಲೆ",
    "connect.btn": "ನೆಟ್‌ವರ್ಕ್‌ಗೆ ಸೇರಿ",

    "connect.story.chip": "SETBIN CONNECT",
    "connect.story.s1.title": "ಮೊಬೈಲ್ ಸೇವೆಗಾಗಿ ಭಾರತದ B2B ನೆಟ್‌ವರ್ಕ್",
    "connect.story.s1.desc": "ತಂತ್ರಜ್ಞರು, ಸೇವಾ ಕೇಂದ್ರಗಳು ಮತ್ತು ಬಿಡಿಭಾಗಗಳ ಪೂರೈಕೆದಾರರನ್ನು ಒಂದೇ ರಚನಾತ್ಮಕ ಪರಿಸರ ವ್ಯವಸ್ಥೆಯಲ್ಲಿ ಸಂಪರ್ಕಿಸುವ ಪರಿಶೀಲಿಸಿದ ವೇದಿಕೆ.",
    "connect.story.s2.tag": "ಹಳೆಯ ವಿಧಾನ",
    "connect.story.s2.title": "ಸೋರ್ಸಿಂಗ್ ಇನ್ನೂ ಹಸ್ತಚಾಲಿತ ಮತ್ತು ಅಸ್ತವ್ಯಸ್ತ",
    "connect.story.s2.p1": "ನಿಜ-ಸಮಯ ಲಭ್ಯತೆ ಇಲ್ಲ",
    "connect.story.s2.p2": "ಬೆಲೆ ಸ್ಪಷ್ಟತೆ ಇಲ್ಲ",
    "connect.story.s2.p3": "ನಕಲಿ ಭಾಗಗಳ ಹೆಚ್ಚಿನ ಅಪಾಯ",
    "connect.story.s2.p4": "ಅಂತ್ಯವಿಲ್ಲದ ಕರೆಗಳು ಮತ್ತು ಸಂದೇಶಗಳು",
    "connect.story.s3.tag": "ಪರಿಹಾರ",
    "connect.story.s3.title": "ಗೊಂದಲದಿಂದ ರಚನೆಗೆ",
    "connect.story.s3.desc": "ವಿಶ್ವಾಸಾರ್ಹ ಪೂರೈಕೆದಾರರಿಂದ ಪರಿಶೀಲಿಸಿದ ಭಾಗಗಳನ್ನು ಹುಡುಕಿ, ಹೋಲಿಸಿ ಮತ್ತು ತಕ್ಷಣ ಪಡೆದುಕೊಳ್ಳಿ.",
    "connect.story.s4.title": "ನೇರ ಪೂರೈಕೆದಾರ ಪ್ರವೇಶ",
    "connect.story.s4.desc": "ವಿಳಂಬ ಇಲ್ಲದೆ ಭಾರತ ಉದ್ದಕ್ಕೂ ಪರಿಶೀಲಿತ ಸಗಟು ವ್ಯಾಪಾರಿಗಳೊಂದಿಗೆ ನೇರವಾಗಿ ಸಂಪರ್ಕಿಸಿ. ಯಾವುದೇ ಮಧ್ಯವರ್ತಿಗಳಿಲ್ಲ.",
    "connect.story.s5.title": "ನಿಜ-ಸಮಯ ದಾಸ್ತಾನು",
    "connect.story.s5.desc": "ಆರ್ಡರ್ ಮಾಡುವ ಮೊದಲು ನಿಖರವಾಗಿ ಏನು ಲಭ್ಯವಿದೆ ಎಂದು ತಿಳಿಯಿರಿ. ಲೈವ್ ಸ್ಟಾಕ್ ಸೂಚಕಗಳು ಅನಿಶ್ಚಿತತೆಯನ್ನು ನಿವಾರಿಸುತ್ತವೆ.",
    "connect.story.s5.feed": "ಲೈವ್ ಸ್ಟಾಕ್ ಫೀಡ್",
    "connect.story.s5.stock": "ಸ್ಟಾಕ್‌ನಲ್ಲಿದೆ",
    "connect.story.s5.p1": "iPhone 13 Pro ಸ್ಕ್ರೀನ್",
    "connect.story.s5.p2": "Samsung S22 ಬ್ಯಾಟರಿ",
    "connect.story.s5.p3": "Type-C ಪೋರ್ಟ್ IC",
    "connect.story.s6.title": "ನಿಜವಾದ ಸಗಟು ಬೆಲೆ",
    "connect.story.s6.desc": "ತಕ್ಷಣ ಪಾರದರ್ಶಕ B2B ಬೆಲೆ ನಿರ್ಧಾರ ಪ್ರವೇಶಿಸಿ. ಪರಿಶೀಲಿತ ಪೂರೈಕೆದಾರರ ನಡುವೆ ದರಗಳನ್ನು ಹೋಲಿಸಿ.",
    "connect.story.s6.retail": "ಚಿಲ್ಲರೆ ಸರಾಸರಿ",
    "connect.story.s7.title": "ಪರಿಶೀಲಿಸಿದ ಅಸಲಿ ಭಾಗಗಳು",
    "connect.story.s7.desc": "ನಕಲಿ ಘಟಕಗಳ ಅಪಾಯ ಕಡಿಮೆ ಮಾಡಿ. ನಮ್ಮ ಪೂರೈಕೆದಾರ ನೆಟ್‌ವರ್ಕ್ OEM ಭಾಗಗಳನ್ನು ಖಾತ್ರಿಗೊಳಿಸಲು ಕಟ್ಟುನಿಟ್ಟಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ.",
    "connect.story.s8.title": "ಗಂಟೆಗಳಿಂದ ನಿಮಿಷಗಳಿಗೆ",
    "connect.story.s8.desc": "ಒಮ್ಮೆ ಗಂಟೆಗಟ್ಟಲೆ ಕರೆ ಮಾಡಬೇಕಿದ್ದ ಕೆಲಸ ಈಗ ಭಾರತದ ಪರಿಶೀಲಿತ ವೇದಿಕೆಯಲ್ಲಿ ಸೆಕೆಂಡುಗಳಲ್ಲಿ ಆಗುತ್ತದೆ.",
    "connect.story.s8.btn": "ಕನೆಕ್ಟ್ ಇಕೋಸಿಸ್ಟಮ್ ಅನ್ವೇಷಿಸಿ",

    // SaaS Showcase Rebrand
    "pro.showcase.heading": "ನಿಮ್ಮ ಇಡೀ ಸೇವಾ ವ್ಯವಹಾರವನ್ನು ಒಂದೇ ಸಿಸ್ಟಮ್‌ನಲ್ಲಿ ನಡೆಸಿ",
    "pro.showcase.subheading": "SETBIN REPAIR",
    "pro.showcase.desc": "ಜಾಬ್ ಇಂಟೇಕ್‌ನಿಂದ ಬಿಲ್ಲಿಂಗ್‌ವರೆಗೆ, ದಾಸ್ತಾನುಗಳಿಂದ ಆರ್ಥಿಕ ಟ್ರ್ಯಾಕಿಂಗ್‌ವರೆಗೆ — SETBIN ಮೊಬೈಲ್ ಸೇವಾ ಕೇಂದ್ರಗಳಿಗಾಗಿ ಪ್ರತಿ ಕಾರ್ಯಾಚರಣೆಯನ್ನು ಒಂದು ತಡೆರಹಿತ ವರ್ಕ್‌ಫ್ಲೋ ಆಗಿ ಏಕೀಕರಿಸುತ್ತದೆ.",
    "pro.showcase.cta.demo": "ಡೆಮೊ ಪಡೆಯಿರಿ",
    "pro.showcase.cta.free": "ಉಚಿತ ಪ್ರಯೋಗ ಪ್ರಾರಂಭಿಸಿ",
    "pro.showcase.nav.daybook": "ಡೇಬುಕ್",
    "pro.showcase.nav.billing": "ಬಿಲ್ಲಿಂಗ್",
    "pro.showcase.nav.inventory": "ದಾಸ್ತಾನು",
    "pro.showcase.nav.reports": "ವರದಿಗಳು",
    "pro.showcase.nav.dues": "ಬಾಕಿ",
    "pro.showcase.nav.exp": "ವೆಚ್ಚಗಳು",
    "pro.showcase.card.rev.title": "ಆದಾಯ",
    "pro.showcase.card.rev.amt": "$198.5M",
    "pro.showcase.card.due.title": "ಬಾಕಿ",
    "pro.showcase.card.due.amt": "$15.3M",
    "pro.showcase.card.rules.title": "ಸೇವಾ ನಿಯಮಗಳು",
    "pro.showcase.card.rules.r1": "ರೇಟಬಲ್",
    "pro.showcase.card.rules.r2": "ಸರಿಯಾದ ಸಮಯದಲ್ಲಿ",
    "pro.showcase.card.rules.r3": "ಅನುಪಾತದ",
    
    "pro.chip": "SETBIN REPAIR",
    "pro.title": "ವ್ಯವಹಾರವನ್ನು ಉನ್ನತೀಕರಿಸಿ",
    "pro.desc": "ರಿಪೇರಿ ಅಂಗಡಿಗಳಿಗೆ ಸಂಪೂರ್ಣ ನಿರ್ವಹಣೆ ಪೈಪ್‌ಲೈನ್.",
    "pro.features.repair": "ರಿಪೇರಿ ಟ್ರ್ಯಾಕಿಂಗ್",
    "pro.features.inventory": "ದಾಸ್ತಾನು ನಿರ್ವಹಣೆ",
    "pro.features.customer": "ಗ್ರಾಹಕ ಸಂವಹನ",
    "pro.btn": "ನಿರ್ವಹಣೆಯನ್ನು ಪ್ರಾರಂಭಿಸಿ",
    "ai.chip": "SCHEMIC AI",
    "ai.title": "ನೆಕ್ಸ್ಟ್-ಜೆನ್ ರೋಗನಿರ್ಣಯ",
    "ai.desc": "ದೋಷಗಳನ್ನು ಗುರುತಿಸಲು AI ಬಳಸಿ.",
    "ai.features.analysis": "ತತ್‌ಕ್ಷಣದ ವಿಶ್ಲೇಷಣೆ",
    "ai.features.faults": "ದೋಷಗಳನ್ನು ಗುರುತಿಸುವುದು",
    "ai.features.solutions": "ರಿಪೇರಿ ಪರಿಹಾರಗಳು",
    "ai.btn": "Schemic AI ಅನ್ನು ಪ್ರಯತ್ನಿಸಿ",
    "network.chip": "ರಾಷ್ಟ್ರೀಯ ನೆಟ್‌ವರ್ಕ್",
    "network.title": "ತಜ್ಞರಿಂದ ವಿಶ್ವಾಸಾರ್ಹ",
    "network.desc": "SETBIN ಅನ್ನು ನಂಬುವ ಸಾವಿರಾರು ವ್ಯವಹಾರಗಳಿಗೆ ಸೇರಿ.",
    "contact.chip": "ಸಂಪರ್ಕಿಸಿ",
    "contact.title": "ಒಟ್ಟಾಗಿ ಭವಿಷ್ಯವನ್ನು ನಿರ್ಮಿಸೋಣ",
    "contact.desc": "ವ್ಯವಹಾರವನ್ನು ಬದಲಾಯಿಸಲು ಸಿದ್ಧರಿದ್ದೀರಾ?",
    "contact.info.title": "ಸಂಪರ್ಕ ಮಾಹಿತಿ",
    "contact.info.email": "ಇಮೇಲ್ ಮಾಡಿ",
    "contact.info.phone": "ಕರೆ ಮಾಡಿ",
    "contact.info.address": "ನಮಗೆ ಭೇಟಿ ನೀಡಿ",
    "contact.form.name": "ಪೂರ್ಣ ಹೆಸರು",
    "contact.form.submit": "ಸಂದೇಶ ಕಳುಹಿಸಿ",
    "cta.title": "ಕ್ರಾಂತಿ ತರಲು ಸಿದ್ಧರಿದ್ದೀರಾ?",
    "cta.desc": "ವೃತ್ತಿಪರರೊಂದಿಗೆ ಸೇರಿ.",
    "cta.btn.start": "ಇಂದೇ ಪ್ರಾರಂಭಿಸಿ",
    "cta.btn.contact": "ಬಿಕ್ರಿ ಶಾಖೆಯನ್ನು ಸಂಪರ್ಕಿಸಿ",

    "contact.form.name_placeholder": "ಜಾನ್ ಡೋ",
    "contact.form.email": "ಇಮೇಲ್ ವಿಳಾಸ",
    "contact.form.email_placeholder": "john@example.com",
    "contact.form.subject": "ವಿಷಯ",
    "contact.form.subject_placeholder": "ನಾವು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?",
    "contact.form.message": "ಸಂದೇಶ",
    "contact.form.message_placeholder": "ನಿಮ್ಮ ಅಗತ್ಯಗಳ ಬಗ್ಗೆ ತಿಳಿಸಿ...",

    "contact.card.office.title": "ಕಚೇರಿ ಸ್ಥಳ",
    "contact.card.office.value": "SETTINGS ಸೇವಾ ಕೇಂದ್ರ ಎರ್ನಾಕುಲಂ",
    "contact.card.office.sub": "ಕೊಚ್ಚಿ, ಕೇರಳ — ಭಾರತ",
    "contact.card.direct.title": "ನೇರ ಸಂಪರ್ಕ",
    "contact.card.direct.sub": "ಸೋಮ-ಶನಿ · ಬೆಳಗ್ಗೆ 10 – ಸಂಜೆ 7 IST",
    "contact.card.email.title": "ಎಂಟರ್‌ಪ್ರೈಸ್ ಇಮೇಲ್",
    "contact.card.email.sub": "24 ಗಂಟೆಗಳ ಒಳಗೆ ಪ್ರತಿಕ್ರಿಯೆ",
    "contact.send_message": "ಸಂದೇಶ ಕಳುಹಿಸಿ",
    "contact.map.label": "SETBIN // ಎರ್ನಾಕುಲಂ",
    "contact.get_directions": "ದಿಕ್ಕುಗಳನ್ನು ಪಡೆಯಿರಿ",

    "network.city.delhi": "ದೆಹಲಿ",
    "network.city.mumbai": "ಮುಂಬೈ",
    "network.city.bangalore": "ಬೆಂಗಳೂರು",
    "network.city.hyderabad": "ಹೈದರಾಬಾದ್",
    "network.city.chennai": "ಚೆನ್ನೈ",
    "network.city.kolkata": "ಕೋಲ್ಕತ್ತಾ",
    "network.city.ahmedabad": "ಅಹಮದಾಬಾದ್",
    "network.city.kochi": "ಕೊಚ್ಚಿ",

    "platform.card1.title": "ಏಕೀಕೃತ ನಿರ್ವಹಣಾ ಪರಿಸರ ವ್ಯವಸ್ಥೆ",
    "platform.card1.desc": "ನಿಮ್ಮ ಸೇವಾ ವ್ಯವಹಾರದ ಪ್ರತಿಯೊಂದು ಅಂಶವನ್ನು ಒಂದೇ ಸ್ಥಳದಲ್ಲಿ ಸಂಪರ್ಕಿಸಿ.",
    "platform.card2.title": "AI-ಚಾಲಿತ ರೋಗನಿರ್ಣಯ",
    "platform.card2.desc": "ನಿಖರವಾದ ದೋಷನಿವಾರಣೆಗಾಗಿ ಸುಧಾರಿತ ಸ್ಕೆಮ್ಯಾಟಿಕ್ ವಿಶ್ಲೇಷಣೆ.",
    "platform.card3.title": "ಭಾರತದ ಅತಿದೊಡ್ಡ ಪೂರೈಕೆ ಸರಪಳಿ",
    "platform.card3.desc": "ದೇಶದ ಅತ್ಯುತ್ತಮ ಪೂರೈಕೆದಾರರಿಂದ ಉತ್ತಮ ಗುಣಮಟ್ಟದ ಭಾಗಗಳು ಮತ್ತು ಸಾಧನಗಳನ್ನು ಪಡೆದುಕೊಳ್ಳಿ."
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
