"use client";

import React, { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "ml" | "hi" | "ta" | "te" | "kn";

type Translations = {
  [key in Language]: {
    [key: string]: string;
  };
};

const translations: Translations = {
  en: {
    "nav.connect": "Setbin Connect",
    "nav.repair": "Setbin Repair",
    "nav.schemic": "Schemic AI",
    "nav.connectBtn": "Connect with us",
    "nav.connectBtnMobile": "Connect",

    "hero.stage1.title": "SETBIN",
    "hero.stage1.subtitle": "The Digital Backbone of the Smartphone Service Industry",
    "hero.stage2.title": "An Industry Worth Billions<br/>Still Running Without Infrastructure",
    "hero.stage2.subtext": "Technicians. Parts. Operations. Intelligence.<br/>All disconnected.",
    "hero.stage3.title": "From Fragmentation<br/>to Structure",
    "hero.stage3.subtext": "What if everything worked together?",
    "hero.stage4.title": "SETBIN connects the ecosystem",
    "hero.stage4.subtext": "Spare sourcing<br/>Service operations<br/>Technical intelligence<br/>All in one platform.",
    "hero.stage5.title": "Connect. Operate. Diagnose.",
    "hero.stage5.subtext": "A complete infrastructure<br/>for the modern repair industry.",
    "hero.stage6.title": "SETBIN",
    "hero.stage6.subtext": "Infrastructure for India's Smartphone Service Industry",
    "hero.stage7.title": "Powering the Future of Mobile Service",
    "hero.stage7.btn": "Explore the Platform",

    "platform.chip": "The Platform",
    "platform.title": "Powering the Next Generation of Service",
    "platform.desc": "A comprehensive ecosystem designed specifically for the smartphone servicing industry.",
    "platform.pillar1.title": "SETBIN CONNECT",
    "platform.pillar1.subtitle": "Verified spare parts marketplace",
    "platform.pillar1.body": "Connect with trusted suppliers. Source genuine parts faster with full transparency.",
    "platform.pillar2.title": "SETBIN REPAIR",
    "platform.pillar2.subtitle": "Service center operating system",
    "platform.pillar2.body": "Manage jobs, track repairs, control inventory and streamline your entire workflow.",
    "platform.pillar3.title": "SCHEMIC AI",
    "platform.pillar3.subtitle": "AI-powered diagnostic intelligence",
    "platform.pillar3.body": "Identify faults using schematic-driven logic instead of trial-and-error repairs.",
    "platform.viewMore": "View More →",
    
    "pillars.chip": "The Pillars of Innovation",
    "pillars.title": "ENGINEERING THE <br/>FUTURE OF REPAIR.",
    "pillars.desc": "We are building a unified ecosystem where supply chains, service centers, and AI diagnostics converge into a single, seamless workflow.",
    "pillars.footer": "Built for Scale • Powered by Intelligence • Trusted by Pros",
    "pillars.connect.subtitle": "ECOSYSTEM",
    "pillars.repair.subtitle": "INFRASTRUCTURE",
    "pillars.schemic.subtitle": "INTELLIGENCE",

    "connect.chip": "SETBIN CONNECT",
    "connect.title": "India's Largest B2B Network for Electronics",
    "connect.desc": "Join India's largest specialized network connecting parts suppliers, tool manufacturers, and service centers.",
    "connect.features.suppliers": "Direct Supplier Access",
    "connect.features.tools": "Premium Tool Sourcing",
    "connect.features.wholesale": "Wholesale Pricing",
    "connect.btn": "Join the Network",

    "connect.story.chip": "SETBIN CONNECT",
    "connect.story.s1.title": "India's B2B Network for Mobile Service",
    "connect.story.s1.desc": "A verified platform connecting technicians, service centers, and spare parts suppliers into one structured ecosystem.",
    "connect.story.s2.tag": "The Old Way",
    "connect.story.s2.title": "Sourcing is Still Manual & Chaotic",
    "connect.story.s2.p1": "No real-time availability",
    "connect.story.s2.p2": "No price clarity",
    "connect.story.s2.p3": "High risk of counterfeit parts",
    "connect.story.s2.p4": "Endless calls and messages",
    "connect.story.s3.tag": "The Solution",
    "connect.story.s3.title": "From Chaos to Structure",
    "connect.story.s3.desc": "Search, compare, and source verified parts from trusted suppliers — instantly.",
    "connect.story.s4.title": "Direct Supplier Access",
    "connect.story.s4.desc": "Connect directly with verified wholesalers across India without delays. No middlemen, no markup.",
    "connect.story.s5.title": "Real-Time Inventory",
    "connect.story.s5.desc": "Know exactly what's available before you order. Live stock indicators eliminate uncertainty and backorder delays.",
    "connect.story.s5.feed": "Live Stock Feed",
    "connect.story.s5.stock": "In Stock",
    "connect.story.s5.p1": "iPhone 13 Pro Screen",
    "connect.story.s5.p2": "Samsung S22 Battery",
    "connect.story.s5.p3": "Type-C Port IC",
    "connect.story.s6.title": "True Wholesale Pricing",
    "connect.story.s6.desc": "Access transparent B2B pricing immediately. Compare rates across verified suppliers without retail competition driving up your costs.",
    "connect.story.s6.retail": "Retail Avg",
    "connect.story.s7.title": "Verified Genuine Parts",
    "connect.story.s7.desc": "Reduce the risk of counterfeit components. Our supplier network is strictly vetted to ensure OEM and high-quality aftermarket parts.",
    "connect.story.s8.title": "From Hours to Minutes",
    "connect.story.s8.desc": "What once took hours of calls and uncertainty now takes seconds on India's verified platform.",
    "connect.story.s8.btn": "Explore Connect Ecosystem",

    // SaaS Showcase Rebrand
    "pro.showcase.heading": "One System for Your Entire Service Business",
    "pro.showcase.subheading": "SETBIN REPAIR",
    "pro.showcase.desc": "From job intake to billing, inventory to financial tracking — SETBIN unifies every operation into one seamless workflow for mobile service centers.",
    "pro.showcase.cta.demo": "Get a Demo",
    "pro.showcase.cta.free": "Start Free Trial",
    "pro.showcase.nav.daybook": "DayBook",
    "pro.showcase.nav.billing": "Billing",
    "pro.showcase.nav.inventory": "Inventory",
    "pro.showcase.nav.reports": "Reports",
    "pro.showcase.nav.dues": "Dues",
    "pro.showcase.nav.exp": "Expenses",
    "pro.showcase.card.rev.title": "REVENUE",
    "pro.showcase.card.rev.amt": "$198.5M",
    "pro.showcase.card.due.title": "PENDING DUES",
    "pro.showcase.card.due.amt": "$15.3M",
    "pro.showcase.card.rules.title": "SERVICE RULES",
    "pro.showcase.card.rules.r1": "RATABLE",
    "pro.showcase.card.rules.r2": "POINT_IN_TIME",
    "pro.showcase.card.rules.r3": "PROPORTIONAL",
    
    "pro.chip": "SETBIN REPAIR",
    "pro.title": "Elevate Your Service Business",
    "pro.desc": "Complete management pipeline for repair shops and independent technicians. Streamline your workflow from intake to delivery.",
    "pro.features.repair": "Repair Tracking",
    "pro.features.inventory": "Inventory Management",
    "pro.features.customer": "Customer Communication",
    "pro.btn": "Start Managing",

    "ai.chip": "SCHEMIC AI",
    "ai.title": "Next-Gen Board Level Diagnostics",
    "ai.desc": "Leverage advanced artificial intelligence to analyze complex motherboard schematics and pinpoint hardware faults with unprecedented accuracy.",
    "ai.features.analysis": "Instant Schematic Analysis",
    "ai.features.faults": "Fault Localization",
    "ai.features.solutions": "Repair Solutions Database",
    "ai.btn": "Try Schemic AI",

    "network.chip": "National Network",
    "network.title": "Trusted by Experts across India",
    "network.desc": "Join thousands of service professionals and businesses that rely on SETBIN for their daily operations.",

    "contact.chip": "Get in Touch",
    "contact.title": "Let's Build the Future Together",
    "contact.desc": "Ready to transform your service business? Our team is here to help you get started.",
    "contact.info.title": "Contact Information",
    "contact.info.desc": "Reach out to us through any of these channels.",
    "contact.info.email": "Email Us",
    "contact.info.phone": "Call Us",
    "contact.info.address": "Visit Us",
    "contact.form.name": "Full Name",
    "contact.form.name_placeholder": "John Doe",
    "contact.form.email": "Email Address",
    "contact.form.email_placeholder": "john@example.com",
    "contact.form.subject": "Subject",
    "contact.form.subject_placeholder": "How can we help?",
    "contact.form.message": "Message",
    "contact.form.message_placeholder": "Tell us about your needs...",
    "contact.form.submit": "Send Message",

    "cta.title": "Ready to Revolutionize Your Service Business?",
    "cta.desc": "Join thousands of professionals already using SETBIN to streamline their operations.",
    "cta.btn.start": "Get Started Today",
    "cta.btn.contact": "Contact Sales"
  },
  ml: {
    "nav.connect": "setbin connect",
    "nav.repair": "setbin repair",
    "nav.schemic": "schemic ai",
    "nav.connectBtn": "ഞങ്ങളുമായി ബന്ധപ്പെടുക",
    "nav.connectBtnMobile": "ബന്ധപ്പെടുക",

    "hero.stage1.title": "SETBIN",
    "hero.stage1.subtitle": "സ്മാർട്ട്‌ഫോൺ സേവന വ്യവസായത്തിന്റെ ഡിജിറ്റൽ നട്ടെല്ല്.",
    "hero.stage2.title": "അടിസ്ഥാന സൗകര്യങ്ങളില്ലാതെ പ്രവർത്തിക്കുന്ന<br/>കോടിക്കണക്കിന് ഡോളറിന്റെ വ്യവസായം.",
    "hero.stage2.subtext": "ടെക്നീഷ്യൻമാർ. പാർട്സ്. പ്രവർത്തനങ്ങൾ.<br/>എല്ലാം വിച്ഛേദിക്കപ്പെട്ടിരിക്കുന്നു.",
    "hero.stage3.title": "ഛിന്നഭിന്നതയിൽ നിന്ന്<br/>ഉറപ്പുള്ള ഒരു ഘടനയിലേക്ക്.",
    "hero.stage3.subtext": "എല്ലാം ഒരുമിച്ച് പ്രവർത്തിച്ചാലോ?",
    "hero.stage4.title": "ഇക്കോസിസ്റ്റത്തെ SETBIN ബന്ധിപ്പിക്കുന്നു.",
    "hero.stage4.subtext": "സ്പെയർ പാർട്സ്, സേവനങ്ങൾ, വിവരങ്ങൾ<br/>എല്ലാം ഒരൊറ്റ പ്ലാറ്റ്‌ഫോമിൽ.",
    "hero.stage5.title": "ബന്ധിപ്പിക്കുക. പ്രവർത്തിപ്പിക്കുക. കണ്ടെത്തുക.",
    "hero.stage5.subtext": "ആധുനിക റിപ്പയർ വ്യവസായത്തിനായുള്ള<br/>പൂർണ്ണമായ അടിസ്ഥാന സൗകര്യങ്ങൾ.",
    "hero.stage6.title": "SETBIN",
    "hero.stage6.subtext": "ഇന്ത്യയിലെ സ്മാർട്ട് ഫോൺ സർവീസ് വ്യവസായത്തിനുള്ള അടിസ്ഥാന സൗകര്യങ്ങൾ.",
    "hero.stage7.title": "മൊബൈൽ സേവനത്തിന്റെ ഭാവി ശാക്തീകരിക്കുന്നു.",
    "hero.stage7.btn": "പ്ലാറ്റ്ഫോം പര്യവേಕ್ಷണം ചെയ്യുക",

    "platform.chip": "പ്ലാറ്റ്ഫോം",
    "platform.title": "അടുത്ത തലമുറയിലെ സേവനങ്ങൾ ശാക്തീകരിക്കുന്നു",
    "platform.desc": "സ്മാർട്ട്ഫോൺ സേവന വ്യവസായത്തിന് മാത്രമായി രൂപകൽപ്പന ചെയ്ത സമഗ്രമായ ഒരു ഇക്കോസിസ്റ്റം.",
    "platform.card1.title": "ഏകീകൃത മാനേജ്മെന്റ് ഇക്കോസിസ്റ്റം",
    "platform.card1.desc": "നിങ്ങളുടെ സേവന ബിസിനസ്സിന്റെ എല്ലാ വശങ്ങളും ഒരിടത്ത് ബന്ധിപ്പിക്കുക.",
    "platform.card2.title": "AI പവർ ഡയഗ്നോസ്റ്റിക്സ്",
    "platform.card2.desc": "കൃത്യമായ പ്രശ്നപരിഹാരത്തിനായി നൂതന സ്കീമാറ്റിക് വിശകലനം.",
    "platform.card3.title": "ഇന്ത്യയിലെ വലിയ സപ്ലൈ ചെയിൻ",
    "platform.card3.desc": "രാജ്യത്തെ മികച്ച വിതരണക്കാരിൽ നിന്ന് ഉയർന്ന നിലവாரമുള്ള ഭാഗങ്ങളും ഉപകരണങ്ങളും ആക്സസ് ചെയ്യുക.",

    "pillars.chip": "നവീകരണത്തിന്റെ നെടുംതൂണുകൾ",
    "pillars.title": "റിപ്പയറിംഗിന്റെ ഭാവി <br/>ഞങ്ങൾ നിർമ്മിക്കുന്നു.",
    "pillars.desc": "സപ്ലൈ ചെയിനുകൾ, സർവീസ് സെന്ററുകൾ, AI ഡയഗ്നോസ്റ്റിക്സ് എന്നിവയെ ഒരൊറ്റ പ്ലാറ്റ്‌ഫോമിൽ ഞങ്ങൾ എത്തിക്കുന്നു.",
    "pillars.footer": "സ്കെയിലിനായി നിർമ്മിച്ചത് • ഇന്റലിജൻസ് കരുത്ത് • വിദഗ്ദ്ധർ വിശ്വസിക്കുന്നത്",
    "pillars.connect.subtitle": "ഇക്കോസിസ്റ്റം",
    "pillars.repair.subtitle": "ഇൻഫ്രാസ്ട്രക്ചർ",
    "pillars.schemic.subtitle": "ഇന്റലിജൻസ്",

    "connect.chip": "SETBIN CONNECT",
    "connect.title": "ഇലക്ട്രോണിക്സിനായുള്ള ഇന്ത്യയിലെ ബി2ബി നെറ്റ്‌വർക്കിംഗ്",
    "connect.desc": "പാർട്സ് സപ്ലയർമാരുമായും സർവീസ് സെന്ററുകളുമായും നേരിട്ട് ബന്ധപ്പെടുക.",
    "pro.showcase.heading": "നിങ്ങളുടെ മുഴുവൻ സർവീസ് ബിസിനസ്സും ഒരു സിസ്റ്റത്തിൽ",
    "pro.showcase.subheading": "സെറ്റ്ബിൻ റിപ്പയർ",
    "pro.showcase.desc": "ജോബ് ഇൻടേക്ക് മുതൽ ബില്ലിംഗ് വരെയും, ഇൻവെന്ററി മുതൽ ഫിനാൻഷ്യൽ ട്രാക്കിംഗ് വരെയും — മൊബൈൽ സർവീസ് സെന്ററുകൾക്കായി സെറ്റ്ബിൻ എല്ലാ പ്രവർത്തനങ്ങളെയും ഒരു തടസ്സമില്ലാത്ത വർക്ക്ഫ്ലോയിലേക്ക് കൊണ്ടുവരുന്നു.",
    "pro.showcase.cta.demo": "ഒരു ഡെമോ നേടുക",
    "pro.showcase.cta.free": "സൗജന്യ ട്രയൽ തുടങ്ങൂ",
    "pro.showcase.nav.daybook": "ഡേബുക്ക്",
    "pro.showcase.nav.billing": "ബില്ലിംഗ്",
    "pro.showcase.nav.inventory": "ഇൻവെന്ററി",
    "pro.showcase.nav.reports": "റിപ്പോർട്ടുകൾ",
    "pro.showcase.nav.dues": "بقായകൾ",
    "pro.showcase.nav.exp": "ചെലവുകൾ",
    "pro.showcase.card.rev.title": "വരുമാനം",
    "pro.showcase.card.rev.amt": "$198.5M",
    "pro.showcase.card.due.title": "بقായകൾ",
    "pro.showcase.card.due.amt": "$15.3M",
    "pro.showcase.card.rules.title": "സർവീസ് റൂൾസ്",
    "pro.showcase.card.rules.r1": "റേറ്റബിൾ",
    "pro.showcase.card.rules.r2": "പോയിന്റ്_ഇൻ_ടൈം",
    "pro.showcase.card.rules.r3": "പ്രൊപ്പോർഷണൽ",
    
    "pro.chip": "SETBIN REPAIR",
    "pro.title": "നിങ്ങളുടെ സർവീസ് ബിസിനസ്സ് മെച്ചപ്പെടുത്തുക",
    "pro.desc": "റിപ്പയർ ഷോപ്പുകൾക്കും സ്വതന്ത്ര ടെക്നീഷ്യൻമാർക്കുമായുള്ള സമ്പൂർണ്ണ മാനേജ്മെന്റ് പൈപ്പ്ലൈൻ. ബുക്കിംഗ് മുതൽ ഡെലിവറി വരെയുള്ള നിങ്ങളുടെ വർക്ക്ഫ്ലോ കാര്യക്ഷമമാക്കുക.",
    "pro.features.repair": "റിപ്പയർ ട്രാക്കിംഗ്",
    "pro.features.inventory": "ഇൻവെന്ററി മാനേജ്മെന്റ്",
    "pro.features.customer": "ഉപഭോക്തൃ ആശയവിനിമയം",
    "pro.btn": "മാനേജിംഗ് ആരംഭിക്കുക",

    "ai.chip": "SCHEMIC AI",
    "ai.title": "നെക്സ്റ്റ്-ജെൻ ബോർഡ് ലെവൽ ഡയഗ്നോസ്റ്റിക്സ്",
    "ai.desc": "സങ്കീർണ്ണമായ മദർബോർഡ് സ്കീമാറ്റിക്സ് വിശകലനം ചെയ്യുന്നതിനും ഹാർഡ്‌വെയർ തകരാറുകൾ മുൻപില്ലാത്തവിധം കൃത്യതയോടെ കണ്ടെത്തുന്നതിനും നൂതന കൃത്രിമബുദ്ധി പ്രയോജനപ്പെടുത്തുക.",
    "ai.features.analysis": "തൽക്ഷണ സ്കീമാറ്റിക് അനാലിസിസ്",
    "ai.features.faults": "തകരാറുകൾ കണ്ടെത്തൽ",
    "ai.features.solutions": "റിപ്പയർ സൊല്യൂഷനുകൾ ഡാറ്റാബേസ്",
    "ai.btn": "Schemic AI പരീക്ഷിക്കുക",

    "network.chip": "ആഗോള നെറ്റ്‌വർക്ക്",
    "network.title": "ലോകമെമ്പാടുമുള്ള വിദഗ്ദ്ധർ വിശ്വസിക്കുന്നത്",
    "network.desc": "തങ്ങളുടെ ദൈനംദിന പ്രവർത്തനങ്ങൾക്കായി ഓൺലൈനിലൂടെ വരുന്ന ആയിരക്കണക്കിന് സേവന പ്രൊഫഷണലുകൾക്കും ബിസിനസുകൾക്കും ഒപ്പം ചേരുക.",

    "contact.chip": "ബന്ധപ്പെടുക",
    "contact.title": "നമുക്ക് ഒരുമിച്ച് ഭാവി കെട്ടിപ്പടുക്കാം",
    "contact.desc": "നിങ്ങളുടെ സേവന ബിസിനസ്സിൽ മാറ്റം വരുത്താൻ തയ്യാറാണോ? നിങ്ങളെ സഹായിക്കാൻ ഞങ്ങളുടെ ടീം ഇവിടെയുണ്ട്.",
    "contact.info.title": "ബന്ധപ്പെടാനുള്ള വിവരങ്ങൾ",
    "contact.info.desc": "ഈ മാർഗ്ഗങ്ങളിലൂടെ ഞങ്ങളെ ബന്ധപ്പെടാം.",
    "contact.info.email": "ഇമെയിൽ ചെയ്യുക",
    "contact.info.phone": "വിളിക്കുക",
    "contact.info.address": "സന്ദർശിക്കുക",
    "contact.form.name": "മുഴുവൻ പേര്",
    "contact.form.name_placeholder": "ജോൺ ഡോ",
    "contact.form.email": "ഇമെയിൽ വിലാസം",
    "contact.form.email_placeholder": "john@example.com",
    "contact.form.subject": "വിഷയം",
    "contact.form.subject_placeholder": "ഞങ്ങൾക്ക് എങ്ങനെ സഹായിക്കാനാകും?",
    "contact.form.message": "സന്ദേശം",
    "contact.form.message_placeholder": "നിങ്ങളുടെ ആവശ്യങ്ങളെക്കുറിച്ച് ഞങ്ങളോട് പറയുക...",
    "contact.form.submit": "സന്ദേശം അയക്കുക",

    "cta.title": "നിങ്ങളുടെ സർവീസ് ബിസിനസ്സിൽ വിപ്ലവം സൃഷ്ടിക്കാൻ തയ്യാറാണോ?",
    "cta.desc": "തങ്ങളുടെ പ്രവർത്തനങ്ങൾ കാര്യക്ഷമമാക്കാൻ ഇതിനകം SETBIN ഉപയോഗിക്കുന്ന ആയിരക്കണക്കിന് പ്രൊഫഷണലുകൾക്കൊപ്പം ചേരുക.",
    "cta.btn.start": "ഇന്നുതന്നെ ആരംഭിക്കുക",
    "cta.btn.contact": "സെയിൽസുമായി ബന്ധപ്പെടുക"
  },
  hi: {
    "nav.connect": "सेटबिन कनेक्ट",
    "nav.repair": "सेटबिन रिपेयर",
    "nav.schemic": "स्केमिक एआई",
    "nav.connectBtn": "हमसे जुड़ें",
    "nav.connectBtnMobile": "जुड़ें",
    "hero.stage1.title": "SETBIN",
    "hero.stage1.subtitle": "स्मार्टफोन सेवा उद्योग की डिजिटल रीढ़",
    "hero.stage2.title": "अरबों का उद्योग<br/>अभी भी बुनियादी ढांचे के बिना चल रहा है",
    "hero.stage2.subtext": "तकनीशियन। पुर्जे। संचालन। इंटेलिजेंस।<br/>सब अलग-थलग।",
    "hero.stage3.title": "विखंडन से<br/>संरचना तक",
    "hero.stage3.subtext": "क्या होगा अगर सब कुछ एक साथ काम करे?",
    "hero.stage4.title": "SETBIN पारिस्थितिकी तंत्र को जोड़ता है",
    "hero.stage4.subtext": "स्पेयर सोर्सिंग<br/>सेवा संचालन<br/>तकनीकी इंटेलिजेंस<br/>सब एक ही प्लेटफॉर्म पर।",
    "hero.stage5.title": "जुड़ें। संचालित करें। निदान करें।",
    "hero.stage5.subtext": "आधुनिक मरम्मत उद्योग के लिए<br/>एक पूर्ण बुनियादी ढांचा।",
    "hero.stage6.title": "SETBIN",
    "hero.stage6.subtext": "भारत के स्मार्टफोन सेवा उद्योग के लिए बुनियादी ढांचा",
    "hero.stage7.title": "मोबाइल सेवा के भविष्य को सशक्त बनाना",
    "hero.stage7.btn": "प्लेटफॉर्म देखें",
    "platform.chip": "प्लेटफॉर्म",
    "platform.title": "अगली पीढ़ी की सेवा को सशक्त बनाना",
    "platform.desc": "स्मार्टफोन सेवा उद्योग के लिए डिज़ाइन किया गया एक व्यापक पारिस्थितिकी तंत्र।",
    "platform.pillar1.title": "SETBIN CONNECT",
    "platform.pillar1.subtitle": "सत्यापित स्पेयर पार्ट्स मार्केटप्लेस",
    "platform.pillar1.body": "विश्वसनीय आपूर्तिकर्ताओं से जुड़ें। पूर्ण पारदर्शिता के साथ असली पुर्जे तेजी से प्राप्त करें।",
    "platform.pillar2.title": "SETBIN REPAIR",
    "platform.pillar2.subtitle": "सर्विस सेंटर ऑपरेटिंग सिस्टम",
    "platform.pillar2.body": "नौकरियों का प्रबंधन करें, मरम्मत को ट्रैक करें, इन्वेंट्री को नियंत्रित करें और अपने कार्यप्रवाह को सुव्यवस्थित करें।",
    "platform.pillar3.title": "SCHEMIC AI",
    "platform.pillar3.subtitle": "AI-संचालित नैदानिक बुद्धिमत्ता",
    "platform.pillar3.body": "परीक्षण-और-त्रुटि मरम्मत के बजाय योजनाबद्ध तर्क का उपयोग करके दोषों की पहचान करें।",
    "platform.viewMore": "और देखें →",

    "pillars.chip": "नवाचार के स्तंभ",
    "pillars.title": "मरम्मत के भविष्य का <br/>निर्माण।",
    "pillars.desc": "हम एक एकीकृत पारिस्थितिकी तंत्र का निर्माण कर रहे हैं जहाँ आपूर्ति श्रृंखला, सेवा केंद्र और AI निदान एक साथ आते हैं।",
    "pillars.footer": "स्केल के लिए निर्मित • बुद्धिमत्ता द्वारा संचालित • पेशेवरों द्वारा विश्वसनीय",
    "pillars.connect.subtitle": "पारिस्थितिकी तंत्र",
    "pillars.repair.subtitle": "बुनियादी ढांचा",
    "pillars.schemic.subtitle": "बुद्धिमत्ता",
    "connect.chip": "SETBIN CONNECT",
    "connect.title": "इलेक्ट्रॉनिक्स के लिए भारत का B2B नेटवर्किंग",
    "connect.desc": "पुर्जों के आपूर्तिकर्ताओं और सेवा केंद्रों को जोड़ने वाले भारत के सबसे बड़े नेटवर्क में शामिल हों।",
    "connect.features.suppliers": "प्रत्यक्ष आपूर्तिकर्ता पहुंच",
    "connect.features.tools": "प्रीमियम टूल सोर्सिंग",
    "connect.features.wholesale": "थोक मूल्य निर्धारण",
    "connect.btn": "नेटवर्क में शामिल हों",

    "connect.story.chip": "SETBIN CONNECT",
    "connect.story.s1.title": "मोबाइल सेवा के लिए भारत का B2B नेटवर्क",
    "connect.story.s1.desc": "तकनीशियनों, सेवा केंद्रों और स्पेयर पार्ट्स आपूर्तिकर्ताओं को एक संरचित पारिस्थितिकी तंत्र में जोड़ने वाला एक सत्यापित मंच।",
    "connect.story.s2.tag": "पुरानी विधि",
    "connect.story.s2.title": "सोर्सिंग अभी भी मैनुअल एवं अव्यवस्थित है",
    "connect.story.s2.p1": "रियल-टाइम उपलब्धता नहीं",
    "connect.story.s2.p2": "कोई मूल्य स्पष्टता नहीं",
    "connect.story.s2.p3": "नकली पुर्जों का अधिक जोखिम",
    "connect.story.s2.p4": "अंतहीन कॉल और संदेश",
    "connect.story.s3.tag": "समाधान",
    "connect.story.s3.title": "अव्यवस्था से संरचना तक",
    "connect.story.s3.desc": "विश्वसनीय आपूर्तिकर्ताओं से सत्यापित पुर्जे खोजें, तुलना करें और तुरंत प्राप्त करें।",
    "connect.story.s4.title": "प्रत्यक्ष आपूर्तिकर्ता पहुंच",
    "connect.story.s4.desc": "विलंब के बिना पूरे भारत में सत्यापित थोक विक्रेताओं से सीधे जुड़ें। कोई बिचौलिए नहीं।",
    "connect.story.s5.title": "रियल-टाइम इन्वेंटरी",
    "connect.story.s5.desc": "ऑर्डर करने से पहले सटीक उपलब्धता जानें। लाइव स्टॉक संकेतक अनिश्चितता को समाप्त करते हैं।",
    "connect.story.s5.feed": "लाइव स्टॉक फ़ीड",
    "connect.story.s5.stock": "स्टॉक में",
    "connect.story.s5.p1": "iPhone 13 Pro स्क्रीन",
    "connect.story.s5.p2": "Samsung S22 बैटरी",
    "connect.story.s5.p3": "Type-C पोर्ट IC",
    "connect.story.s6.title": "सच्ची थोक कीमत",
    "connect.story.s6.desc": "तुरंत पारदर्शी B2B मूल्य निर्धारण एक्सेस करें। सत्यापित आपूर्तिकर्ताओं से दरों की तुलना करें।",
    "connect.story.s6.retail": "खुदरा औसत",
    "connect.story.s7.title": "सत्यापित असली पुर्जे",
    "connect.story.s7.desc": "नकली घटकों का जोखिम कम करें। हमारा आपूर्तिकर्ता नेटवर्क OEM पुर्जों को सुनिश्चित करने के लिए सख्ती से जाँचा गया है।",
    "connect.story.s8.title": "घंटों से मिनटों तक",
    "connect.story.s8.desc": "जो काम कभी घंटों की कॉल से होता था, वह अब भारत के सत्यापित प्लेटफ़ॉर्म पर सेकंडों में हो जाता है।",
    "connect.story.s8.btn": "कनेक्ट इकोसिस्टम एक्सप्लोर करें",

    // SaaS Showcase Rebrand
    "pro.showcase.heading": "अपना पूरा सर्विस बिजनेस एक ही सिस्टम में चलाएं",
    "pro.showcase.subheading": "SETBIN REPAIR",
    "pro.showcase.desc": "जॉब इनटेक से लेकर बिलिंग तक, इन्वेंट्री से लेकर फाइनेंशियल ट्रैकिंग तक — SETBIN मोबाइल सर्विस सेंटरों के लिए हर ऑपरेशन को एक निर्बाध वर्कफ्लो में जोड़ता है।",
    "pro.showcase.cta.demo": "डेमो देखें",
    "pro.showcase.cta.free": "फ्री ट्रायल शुरू करें",
    "pro.showcase.nav.daybook": "डेबुक",
    "pro.showcase.nav.billing": "बिलिंग",
    "pro.showcase.nav.inventory": "इन्वेंट्री",
    "pro.showcase.nav.reports": "रिपोर्ट",
    "pro.showcase.nav.dues": "बकाया",
    "pro.showcase.nav.exp": "खर्चे",
    "pro.showcase.card.rev.title": "राजस्व",
    "pro.showcase.card.rev.amt": "$198.5M",
    "pro.showcase.card.due.title": "बकाया",
    "pro.showcase.card.due.amt": "$15.3M",
    "pro.showcase.card.rules.title": "सेवा नियम",
    "pro.showcase.card.rules.r1": "रेटबल",
    "pro.showcase.card.rules.r2": "पॉइंट_इन_टाइम",
    "pro.showcase.card.rules.r3": "आनुपातिक",
    
    "pro.chip": "SETBIN REPAIR",
    "pro.title": "अपने सेवा व्यवसाय को ऊपर उठाएं",
    "pro.desc": "मरम्मत की दुकानों के लिए पूर्ण प्रबंधन पाइपलाइन। अपने वर्कफ़्लो को सुव्यवस्थित करें।",
    "pro.features.repair": "मरम्मत ट्रैकिंग",
    "pro.features.inventory": "इन्वेंटरी प्रबंधन",
    "pro.features.customer": "ग्राहक संचार",
    "pro.btn": "प्रबंधन शुरू करें",
    "ai.chip": "SCHEMIC AI",
    "ai.title": "अगली पीढ़ी के बोर्ड स्तर के निदान",
    "ai.desc": "हार्डवेयर दोषों को इंगित करने के लिए उन्नत कृत्रिम बुद्धिमत्ता का लाभ उठाएं।",
    "ai.features.analysis": "त्वरित विश्लेषण",
    "ai.features.faults": "दोष स्थानीयकरण",
    "ai.features.solutions": "मरम्मत समाधान",
    "ai.btn": "Schemic AI आज़माएं",
    "network.chip": "राष्ट्रीय नेटवर्क",
    "network.title": "भारत भर के विशेषज्ञों द्वारा विश्वसनीय",
    "network.desc": "उन हजारों सेवा पेशेवरों में शामिल हों जो SETBIN पर भरोसा करते हैं।",
    "contact.chip": "संपर्क करें",
    "contact.title": "आइए साथ मिलकर भविष्य बनाएं",
    "contact.desc": "अपने सेवा व्यवसाय को बदलने के लिए तैयार हैं?",
    "contact.info.title": "संपर्क जानकारी",
    "contact.info.email": "हमें ईमेल करें",
    "contact.info.phone": "हमें कॉल करें",
    "contact.info.address": "हमसे मिलें",
    "contact.form.name": "पूरा नाम",
    "contact.form.submit": "संदेश भेजें",
    "cta.title": "व्यवसाय में क्रांति लाने के लिए तैयार हैं?",
    "cta.desc": "हजारों पेशेवरों में शामिल हों जो SETBIN का उपयोग कर रहे हैं।",
    "cta.btn.start": "आज ही शुरू करें",
    "cta.btn.contact": "बिक्री से संपर्क करें"
  },
  ta: {
    "nav.connect": "செட்பின் கனெக்ட்",
    "nav.repair": "செட்பின் ரிப்பேர்",
    "nav.schemic": "ஸ்கெமிக் ஏஐ",
    "nav.connectBtn": "எங்களுடன் இணையுங்கள்",
    "nav.connectBtnMobile": "இணையுங்கள்",
    "hero.stage1.title": "SETBIN",
    "hero.stage1.subtitle": "ஸ்மார்ட்போன் சேவைத் துறையின் டிஜிட்டல் முதுகெலும்பு",
    "hero.stage2.title": "பில்லியன் டாலர் மதிப்புள்ள தொழில்<br/>இன்னும் உள்கட்டமைப்பு இல்லாமல் இயங்குகிறது",
    "hero.stage2.subtext": "தொழில்நுட்ப வல்லுநர்கள். பாகங்கள். செயல்பாடுகள். நுண்ணறிவு.<br/>எல்லாம் துண்டிக்கப்பட்டுள்ளன.",
    "hero.stage3.title": "துண்டு துண்டாக இருப்பதிலிருந்து<br/>கட்டமைப்பு வரை",
    "hero.stage3.subtext": "எல்லாம் ஒன்றாக வேலை செய்தால் என்ன?",
    "hero.stage4.title": "SETBIN சுற்றுச்சூழல் அமைப்பை இணைக்கிறது",
    "hero.stage4.subtext": "பாகங்கள் தேடுதல்<br/>சேவை செயல்பாடுகள்<br/>தொழில்நுட்ப நுண்ணறிவு<br/>எல்லாம் ஒரே தளத்தில்.",
    "hero.stage5.title": "இணையுங்கள். இயக்குங்கள். கண்டறியுங்கள்.",
    "hero.stage5.subtext": "நவீன பழுதுபார்க்கும் துறைக்கான<br/>ஒரு முழுமையான உள்கட்டமைப்பு.",
    "hero.stage6.title": "SETBIN",
    "hero.stage6.subtext": "இந்திய ஸ்மார்ட்போன் சேவைத் துறைக்கான உள்கட்டமைப்பு",
    "hero.stage7.title": "மொபைல் சேவையின் எதிர்காலத்தை மேம்படுத்துதல்",
    "hero.stage7.btn": "தளத்தை ஆராயுங்கள்",
    "platform.chip": "தளம்",
    "platform.title": "அடுத்த தலைமுறை சேவையை மேம்படுத்துதல்",
    "platform.desc": "ஸ்மார்ட்போன் சேவைத் துறைக்காக வடிவமைக்கப்பட்ட விரிவான சுற்றுச்சூழல் அமைப்பு.",
    "platform.pillar1.title": "SETBIN CONNECT",
    "platform.pillar1.subtitle": "சரிபார்க்கப்பட்ட உதிரி பாகங்கள் மெய்நிகர் சந்தை",
    "platform.pillar1.body": "நம்பகமான சப்ளையர்களுடன் இணையுங்கள். முழு வெளிப்படைத்தன்மையுடன் உண்மையான பாகங்களை விரைவாகப் பெறுங்கள்.",
    "platform.pillar2.title": "SETBIN REPAIR",
    "platform.pillar2.subtitle": "சேவை மைய இயக்க முறைமை",
    "platform.pillar2.body": "பணிகளை நிர்வகிக்கவும், பழுதுபார்ப்புகளைக் கண்காணிக்கவும், இருப்பைக் கட்டுப்படுத்தவும் மற்றும் உங்கள் பணிப்பாய்வுகளை சீரமைக்கவும்.",
    "platform.pillar3.title": "SCHEMIC AI",
    "platform.pillar3.subtitle": "AI-இயங்கும் நோய் கண்டறிதல் நுண்ணறிவு",
    "platform.pillar3.body": "சோதனை மற்றும் பிழை பழுதுபார்ப்புகளுக்கு பதிலாக திட்டவட்டமான தர்க்கத்தைப் பயன்படுத்தி பிழைகளைக் கண்டறியவும்.",
    "platform.viewMore": "மேலும் பார்க்க →",

    "pillars.chip": "புதுமையின் தூண்கள்",
    "pillars.title": "பழுதுபார்ப்பின் எதிர்காலத்தை <br/>உருவாக்குகிறோம்.",
    "pillars.desc": "சப்ளை செயின்கள், சேவை மையங்கள் மற்றும் AI கண்டறிதல் ஆகியவை ஒன்றிணையும் ஒரு ஒருங்கிணைந்த கட்டமைப்பை நாங்கள் உருவாக்குகிறோம்.",
    "pillars.footer": "வளர்ச்சிக்காக உருவாக்கப்பட்டது • நுண்ணறிவால் இயக்கப்படுகிறது • நிபுணர்களால் நம்பப்படுகிறது",
    "pillars.connect.subtitle": "சுற்றுச்சூழல் அமைப்பு",
    "pillars.repair.subtitle": "உள்கட்டமைப்பு",
    "pillars.schemic.subtitle": "நுண்ணறிவு",
    "connect.chip": "SETBIN CONNECT",
    "connect.title": "இந்திய B2B நெட்வொர்க்கிங்",
    "connect.desc": "இந்தியாவின் மிகப்பெரிய சிறப்பு நெட்வொர்க்கில் இணையுங்கள்.",
    "connect.features.suppliers": "நேரடி சப்ளையர் அணுகல்",
    "connect.features.tools": "பிரீமியம் கருவி தேடுதல்",
    "connect.features.wholesale": "மொத்த விற்பனை விலை",
    "connect.btn": "நெட்வொர்க்கில் இணையுங்கள்",

    "connect.story.chip": "SETBIN CONNECT",
    "connect.story.s1.title": "மொபைல் சேவைக்கான இந்தியாவின் B2B நெட்வொர்க்",
    "connect.story.s1.desc": "தொழில்நுட்ப வல்லுநர்கள், சேவை மையங்கள் மற்றும் உதிரி பாகங்கள் சப்ளையர்களை ஒரே கட்டமைப்பில் இணைக்கும் சரிபார்க்கப்பட்ட தளம்.",
    "connect.story.s2.tag": "பழைய முறை",
    "connect.story.s2.title": "சோர்சிங் இன்னும் கையேடு மற்றும் குழப்பமாக உள்ளது",
    "connect.story.s2.p1": "நிகழ்நேர கிடைக்கும் தன்மை இல்லை",
    "connect.story.s2.p2": "விலை நெளிவு இல்லை",
    "connect.story.s2.p3": "போலி பாகங்களின் அதிக ஆபத்து",
    "connect.story.s2.p4": "முடிவில்லாத அழைப்புகள் மற்றும் செய்திகள்",
    "connect.story.s3.tag": "தீர்வு",
    "connect.story.s3.title": "குழப்பத்திலிருந்து கட்டமைப்பு வரை",
    "connect.story.s3.desc": "நம்பகமான சப்ளையர்களிடமிருந்து சரிபார்க்கப்பட்ட பாகங்களை தேடுங்கள், ஒப்பிடுங்கள் மற்றும் உடனடியாக பெறுங்கள்.",
    "connect.story.s4.title": "நேரடி சப்ளையர் அணுகல்",
    "connect.story.s4.desc": "இடைத்தரகர்கள் இல்லாமல் இந்தியா முழுவதும் சரிபார்க்கப்பட்ட மொத்த வணிகர்களுடன் நேரடியாக இணையுங்கள்.",
    "connect.story.s5.title": "நிகழ்நேர சரக்கு",
    "connect.story.s5.desc": "கட்டளையிடுவதற்கு முன்பு சரியாக என்னவென்று தெரியும். நேரடி பங்கு குறிகாட்டிகள் நிச்சயமற்ற தன்மையை நீக்குகின்றன.",
    "connect.story.s5.feed": "நேரடி பங்கு ஊட்டம்",
    "connect.story.s5.stock": "கையிருப்பில் உள்ளது",
    "connect.story.s5.p1": "iPhone 13 Pro திரை",
    "connect.story.s5.p2": "Samsung S22 மின்கலம்",
    "connect.story.s5.p3": "Type-C போர்ட் IC",
    "connect.story.s6.title": "உண்மையான மொத்த விலை",
    "connect.story.s6.desc": "உடனடியாக வெளிப்படையான B2B விலையை அணுகுங்கள். சரிபார்க்கப்பட்ட சப்ளையர்களிடையே விலைகளை ஒப்பிடுங்கள்.",
    "connect.story.s6.retail": "சில்லறை சராசரி",
    "connect.story.s7.title": "சரிபார்க்கப்பட்ட உண்மையான பாகங்கள்",
    "connect.story.s7.desc": "போலி கூறுகளின் அபாயத்தை குறையுங்கள். OEM மற்றும் உயர்தர பாகங்களை உறுதிப்படுத்த எங்கள் சப்ளையர் நெட்வொர்க் கண்டிப்பாக சோதிக்கப்படுகிறது.",
    "connect.story.s8.title": "மணிநேரங்கள் நிமிடங்களாக",
    "connect.story.s8.desc": "ஒருமுறை மணிக்கணக்கான அழைப்புகளில் நடந்தது இப்போது இந்தியாவின் சரிபார்க்கப்பட்ட தளத்தில் வினாடிகளில் ஆகிறது.",
    "connect.story.s8.btn": "கனெக்ட் சுற்றுச்சூழல் ஆராயுங்கள்",

    // SaaS Showcase Rebrand
    "pro.showcase.heading": "உங்கள் முழு சேவை வணிகத்தையும் ஒரே அமைப்பில் நடத்துங்கள்",
    "pro.showcase.subheading": "SETBIN REPAIR",
    "pro.showcase.desc": "வேலை எடுப்பது முதல் பில்லிங் வரை, இருப்பு முதல் நிதி கண்காணிப்பு வரை — SETBIN மொபைல் சேவை மையங்களுக்கான ஒவ்வொரு செயல்பாட்டையும் ஒரு தடையற்ற பணிப்பாய்வுக்குள் இணைக்கிறது.",
    "pro.showcase.cta.demo": "ஒரு டெமோவைப் பெறுங்கள்",
    "pro.showcase.cta.free": "இலவச சோதனையைத் தொடங்கவும்",
    "pro.showcase.nav.daybook": "டேபுக்",
    "pro.showcase.nav.billing": "பில்லிங்",
    "pro.showcase.nav.inventory": "இருப்பு",
    "pro.showcase.nav.reports": "அறிக்கைகள்",
    "pro.showcase.nav.dues": "நிலுவைத் தொகை",
    "pro.showcase.nav.exp": "செலவுகள்",
    "pro.showcase.card.rev.title": "வருவாய்",
    "pro.showcase.card.rev.amt": "$198.5M",
    "pro.showcase.card.due.title": "நிலுவைத் தொகை",
    "pro.showcase.card.due.amt": "$15.3M",
    "pro.showcase.card.rules.title": "சேவை விதிகள்",
    "pro.showcase.card.rules.r1": "மதிப்பிடத்தக்கது",
    "pro.showcase.card.rules.r2": "சரியான நேரத்தில்",
    "pro.showcase.card.rules.r3": "விகிதாசார",
    
    "pro.chip": "SETBIN REPAIR",
    "pro.title": "உங்கள் சேவை வணிகத்தை உயர்த்துங்கள்",
    "pro.desc": "பழுதுபார்க்கும் கடைகளுக்கான முழுமையான மேலாண்மை குழாய்.",
    "pro.features.repair": "பழுதுபார்க்கும் கண்காணிப்பு",
    "pro.features.inventory": "இருப்பு மேலாண்மை",
    "pro.features.customer": "வாடிக்கையாளர் தொடர்பு",
    "pro.btn": "மேலாண்மையை தொடங்குங்கள்",
    "ai.chip": "SCHEMIC AI",
    "ai.title": "அடுத்த தலைமுறை நோய் கண்டறிதல்",
    "ai.desc": "வன்பொருள் குறைபாடுகளை துல்லியமாக சுட்டிக்காட்ட AI ஐப் பயன்படுத்தவும்.",
    "ai.features.analysis": "உடனடி பகுப்பாய்வு",
    "ai.features.faults": "குறைகளை கண்டறிதல்",
    "ai.features.solutions": "தீர்வுகள் தரவுத்தளம்",
    "ai.btn": "Schemic AI ஐ முயற்சிக்கவும்",
    "network.chip": "தேசிய நெட்வொர்க்",
    "network.title": "இந்திய நிபுணர்களால் நம்பப்படுகிறது",
    "network.desc": "SETBIN ஐ நம்பியிருக்கும் ஆயிரக்கணக்கான வணிகங்களுடன் இணையுங்கள்.",
    "contact.chip": "தொடர்பு கொள்ள",
    "contact.title": "ஒன்றாக எதிர்காலத்தை உருவாக்குவோம்",
    "contact.desc": "உங்கள் சேவை வணிகத்தை மாற்றத் தயாரா?",
    "contact.info.title": "தொடர்பு விவரங்கள்",
    "contact.info.email": "மின்னஞ்சல் அனுப்புங்கள்",
    "contact.info.phone": "எங்களை அழையுங்கள்",
    "contact.info.address": "எங்களைப் பார்வையிடவும்",
    "contact.form.name": "முழு பெயர்",
    "contact.form.submit": "செய்தி அனுப்பு",
    "cta.title": "புரட்சியை ஏற்படுத்தத் தயாரா?",
    "cta.desc": "SETBIN ஐப் பயன்படுத்தும் ஆயிரக்கணக்கான நிபுணர்களுடன் இணையுங்கள்.",
    "cta.btn.start": "இன்றே தொடங்குங்கள்",
    "cta.btn.contact": "விற்பனை பிரிவை தொடர்பு கொள்ளவும்"
  },
  te: {
    "nav.connect": "సెట్‌బిన్ కనెక్ట్",
    "nav.repair": "సెట్‌బిన్ రిపేర్",
    "nav.schemic": "స్కెమిక్ AI",
    "nav.connectBtn": "మాతో కనెక్ట్ అవ్వండి",
    "nav.connectBtnMobile": "కనెక్ట్",
    "hero.stage1.title": "SETBIN",
    "hero.stage1.subtitle": "స్మార్ట్‌ఫోన్ సేవా పరిశ్రమ యొక్క డిజిటల్ వెన్నెముక",
    "hero.stage2.title": "బిలియన్ల విలువైన పరిశ్రమ<br/>మౌలిక సదుపాయాలు లేకుండానే నడుస్తోంది",
    "hero.stage2.subtext": "టెక్నీషియన్లు. భాగాలు. కార్యకలాపాలు. ఇంటెలిజెన్స్.<br/>అన్నీ విడివిడిగా ఉన్నాయి.",
    "hero.stage3.title": "విచ్ఛిన్నం నుండి<br/>నిర్మాణం వరకు",
    "hero.stage3.subtext": "అన్నీ కలిసి పనిచేస్తే ఎలా ఉంటుంది?",
    "hero.stage4.title": "SETBIN పర్యావరణ వ్యవస్థను కలుపుతుంది",
    "hero.stage4.subtext": "విడిభాగాల సేకరణ<br/>సేవా కార్యకలాపాలు<br/>సాంకేతిక ఇంటెలిజెన్స్<br/>అన్నీ ఒకే ప్లాట్‌ఫారమ్‌లో.",
    "hero.stage5.title": "కనెక్ట్ అవ్వండి. నిర్వహించండి.",
    "hero.stage5.subtext": "ఆధునిక మరమ్మతు పరిశ్రమ కోసం<br/>మౌలిక సదుపాయాలు.",
    "hero.stage6.title": "SETBIN",
    "hero.stage6.subtext": "భారతీయ స్మార్ట్‌ఫోన్ సేవా పరిశ్రమ కోసం మౌలిక సదుపాయాలు",
    "hero.stage7.title": "మొబైల్ సేవల భవిష్యత్తును శక్తివంతం చేయడం",
    "hero.stage7.btn": "ప్లాట్‌ఫారమ్‌ను అన్వేషించండి",
    "platform.chip": "ప్లాట్‌ఫారమ్",
    "platform.title": "తదుపరి తరం సేవను శక్తివంతం చేయడం",
    "platform.desc": "స్మార్ట్‌ఫోన్ సేవా పరిశ్రమ కోసం రూపొందించబడిన పర్యావరణ వ్యవస్థ.",
    "platform.card1.title": "ఏకీకృత నిర్వహణ",
    "platform.card1.desc": "వ్యాపారంలోని అన్ని అంశాలను ఒకే చోట కనెక్ట్ చేయండి.",
    "platform.card2.title": "AI-ఆధారిత రోగ నిర్ధారణ",
    "platform.card2.desc": "ఖచ్చితమైన సమస్య గుర్తింపు కోసం అధునాతన విశ్లేషణ.",
    "platform.card3.title": "భారతీయ సప్లై చైన్",
    "platform.card3.desc": "ధృవీకరించబడిన సరఫరాదారుల నుండి భాగాలు పొందండి.",

    "pillars.chip": "ఆవిష్కరణల మూలస్తంభాలు",
    "pillars.title": "మరమ్మత్తు భవిష్యత్తును <br/>నిర్మించడం.",
    "pillars.desc": "సరఫరా గొలుసులు, సేవా కేంద్రాలు మరియు AI రోగ నిర్ధారణను మేము ఒకే చోట కలుపుతున్నాము.",
    "pillars.footer": "స్కేల్ కోసం నిర్మించబడింది • ఇంటెలిజెన్స్ శక్తి • నిపుణుల విశ్వాసం",
    "pillars.connect.subtitle": "పర్యావరణ వ్యవస్థ",
    "pillars.repair.subtitle": "మౌలిక సదుపాయాలు",
    "pillars.schemic.subtitle": "ఇంటెలిజెన్స్",
    "connect.chip": "SETBIN CONNECT",
    "connect.title": "భారతీయ B2B నెట్‌వర్కింగ్",
    "connect.desc": "ప్రపంచంలోనే అతిపెద్ద నెట్‌వర్క్‌లో చేరండి.",
    "connect.features.suppliers": "సరఫరాదారు యాక్సెస్",
    "connect.features.tools": "సాధనాల సేకరణ",
    "connect.features.wholesale": "టోకు ధరలు",
    "connect.btn": "నెట్‌వర్క్‌లో చేరండి",

    "connect.story.chip": "SETBIN CONNECT",
    "connect.story.s1.title": "మొబైల్ సేవ కోసం భారతదేశం యొక్క B2B నెట్‌వర్క్",
    "connect.story.s1.desc": "టెక్నీషియన్లు, సేవా కేంద్రాలు మరియు విడి భాగాల సరఫరాదారులను ఒకే నిర్మాణాత్మక పర్యావరణ వ్యవస్థలో కనెక్ట్ చేసే ధృవీకరించబడిన ప్లాట్‌ఫారమ్.",
    "connect.story.s2.tag": "పాత పద్ధతి",
    "connect.story.s2.title": "సోర్సింగ్ ఇంకా మాన్యువల్ & అస్తవ్యస్తంగా ఉంది",
    "connect.story.s2.p1": "రియల్-టైమ్ లభ్యత లేదు",
    "connect.story.s2.p2": "ధర స్పష్టత లేదు",
    "connect.story.s2.p3": "నకిలీ విడిభాగాల ప్రమాదం ఎక్కువ",
    "connect.story.s2.p4": "అంతులేని కాల్‌లు మరియు సందేశాలు",
    "connect.story.s3.tag": "పరిష్కారం",
    "connect.story.s3.title": "గందరగోళం నుండి నిర్మాణం వరకు",
    "connect.story.s3.desc": "నమ్మకమైన సరఫరాదారుల నుండి ధృవీకరించబడిన విడిభాగాలను వెతకండి, పోల్చండి మరియు వెంటనే పొందండి.",
    "connect.story.s4.title": "నేరుగా సరఫరాదారు యాక్సెస్",
    "connect.story.s4.desc": "జాప్యం లేకుండా భారతదేశం అంతటా ధృవీకరించబడిన హోల్‌సేలర్లతో నేరుగా కనెక్ట్ అవ్వండి. దళారీలు లేరు.",
    "connect.story.s5.title": "రియల్-టైమ్ ఇన్వెంటరీ",
    "connect.story.s5.desc": "ఆర్డర్ చేయడానికి ముందు ఏమి అందుబాటులో ఉందో సరిగ్గా తెలుసుకోండి. లైవ్ స్టాక్ సూచికలు అనిశ్చితిని తొలగిస్తాయి.",
    "connect.story.s5.feed": "నేరు స్టాక్ ఫీడ్",
    "connect.story.s5.stock": "స్టాక్‌లో ఉంది",
    "connect.story.s5.p1": "iPhone 13 Pro స్క్రీన్",
    "connect.story.s5.p2": "Samsung S22 బ్యాటరీ",
    "connect.story.s5.p3": "Type-C పోర్ట్ IC",
    "connect.story.s6.title": "నిజమైన హోల్‌సేల్ ధర",
    "connect.story.s6.desc": "వెంటనే పారదర్శక B2B ధరను యాక్సెస్ చేయండి. ధృవీకరించబడిన సరఫరాదారుల అంతటా రేట్లను పోల్చండి.",
    "connect.story.s6.retail": "రిటైల్ సరాసరి",
    "connect.story.s7.title": "ధృవీకరించబడిన అసలైన విడిభాగాలు",
    "connect.story.s7.desc": "నకిలీ భాగాల ప్రమాదాన్ని తగ్గించండి. OEM మరియు అధిక నాణ్యత అఫ్టర్‌మార్కెట్ విడిభాగాలను నిర్ధారించడానికి మా సరఫరాదారు నెట్‌వర్క్ కఠినంగా పరీక్షించబడింది.",
    "connect.story.s8.title": "గంటల నుండి నిమిషాలకు",
    "connect.story.s8.desc": "ఒకప్పుడు గంటల కాల్‌లు అవసరమైనది ఇప్పుడు భారతదేశం యొక్క ధృవీకరించబడిన ప్లాట్‌ఫారమ్‌లో సెకన్లలో జరుగుతుంది.",
    "connect.story.s8.btn": "కనెక్ట్ ఎకోసిస్టమ్ అన్వేషించండి",

    // SaaS Showcase Rebrand
    "pro.showcase.heading": "మీ మొత్తం సర్వీస్ బిజినెస్‌ను ఒకే సిస్టమ్‌లో నిర్వహించండి",
    "pro.showcase.subheading": "SETBIN REPAIR",
    "pro.showcase.desc": "జాబ్ ఇన్‌టేక్ నుండి బిల్లింగ్ వరకు, ఇన్వెന്റరీ నుండి ఫైనాన్షియల్ ట్రాకింగ్ వరకు — SETBIN మొಬైల్ సర్వీస్ సెంటర్ల కోసం ప్రతి ఆపరేషన్‌ను ఒకే అతుకులు లేని వర్క్‌ఫ్లోగా మారుస్తుంది.",
    "pro.showcase.cta.demo": "డెమో పొందండి",
    "pro.showcase.cta.free": "ఉచిత ట్రయల్ ప్రారంభించండి",
    "pro.showcase.nav.daybook": "డేబుక్",
    "pro.showcase.nav.billing": "బిల్లింగ్",
    "pro.showcase.nav.inventory": "ఇన్వెంటరీ",
    "pro.showcase.nav.reports": "రిపోర్ట్స్",
    "pro.showcase.nav.dues": "బకాయిలు",
    "pro.showcase.nav.exp": "ఖర్చులు",
    "pro.showcase.card.rev.title": "రాబడి",
    "pro.showcase.card.rev.amt": "$198.5M",
    "pro.showcase.card.due.title": "బకాయిలు",
    "pro.showcase.card.due.amt": "$15.3M",
    "pro.showcase.card.rules.title": "సేవా నియమాలు",
    "pro.showcase.card.rules.r1": "రేటబుల్",
    "pro.showcase.card.rules.r2": "పాయింట్_ఇన్_టైమ్",
    "pro.showcase.card.rules.r3": "ప్రొపోర్షనల్",
    
    "pro.chip": "SETBIN REPAIR",
    "pro.title": "మీ సేవా వ్యాపారాన్ని మెరుగుపరచుకోండి",
    "pro.desc": "మరమ్మతు దుకాణాల కోసం పూర్తి నిర్వహణ పైప్‌లైన్.",
    "pro.features.repair": "మరమ్మతు ట్రాకింగ్",
    "pro.features.inventory": "ఇన్వెంటరీ మేనేజ్మెంట్",
    "pro.features.customer": "కస్టమర్ కమ్యూనికేషన్",
    "pro.btn": "నిర్వహణను ప్రారంభించండి",
    "ai.chip": "SCHEMIC AI",
    "ai.title": "నెక్స్ట్-జెన్ రోగనిర్ధారణ",
    "ai.desc": "హార్డ్‌వేర్ లోపాలను గుర్తించడానికి AIని ఉపయోగించండి.",
    "ai.features.analysis": "తక్షణ విశ్ಲೇషణ",
    "ai.features.faults": "లోపాల గుర్తింపు",
    "ai.features.solutions": "పరిష్కారాల డేటాబేస్",
    "ai.btn": "Schemic AIని ప్రయత్నించండి",
    "network.chip": "జాతీయ నెట్‌వర్క్",
    "network.title": "నిపుణులచే విశ్వసించబడింది",
    "network.desc": "SETBINపై ఆధారపడే వేలాది వ్యాపారాలలో చేరండి.",
    "contact.chip": "సంప్రదించండి",
    "contact.title": "కలిసి భవిష్యత్తును నిర్మిద్దాం",
    "contact.desc": "వ్యాపారాన్ని మార్చడానికి సిద్ధంగా ఉన్నారా?",
    "contact.info.title": "సంప్రదింపు సమాచారం",
    "contact.info.email": "ఈమెయిల్ చేయండి",
    "contact.info.phone": "కాల్ చేయండి",
    "contact.info.address": "మమ్మల్ని సందర్శించండి",
    "contact.form.name": "పూర్తి పేరు",
    "contact.form.submit": "సందేశం పంపండి",
    "cta.title": "విప్లవం తీసుకురావడానికి సిద్ధంగా ఉన్నారా?",
    "cta.desc": "SETBINని ఉపయోగిస్తున్న నిపుణులతో చేరండి.",
    "cta.btn.start": "ఈరోజే ప్రారంభించండి",
    "cta.btn.contact": "సేల్స్‌ను సంప్రదించండి"
  },
  kn: {
    "nav.connect": "ಸೆಟ್‌ಬಿನ್ ಕನೆಕ್ಟ್",
    "nav.repair": "ಸೆಟ್‌ಬಿನ್ ರಿಪೇರಿ",
    "nav.schemic": "ಸ್ಕೆಮಿಕ್ AI",
    "nav.connectBtn": "ನಮ್ಮೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಿ",
    "nav.connectBtnMobile": "ಸಂಪರ್ಕಿಸಿ",
    "hero.stage1.title": "SETBIN",
    "hero.stage1.subtitle": "ಸ್ಮಾರ್ಟ್‌ಫೋನ್ ಸೇವಾ ಉದ್ಯಮದ ಡಿಜಿಟಲ್ ಬೆನ್ನೆಲುಬು",
    "hero.stage2.title": "ಬಿಲಿಯನ್ ಡಾಲರ್ ಉದ್ಯಮ<br/>ಮೂಲಸೌಕರ್ಯವಿಲ್ಲದೆ ನಡೆಯುತ್ತಿದೆ",
    "hero.stage2.subtext": "ತಂತ್ರಜ್ಞರು. ಭಾಗಗಳು. ಕಾರ್ಯಾಚರಣೆಗಳು. ಬುದ್ಧಿವಂತಿಕೆ.<br/>ಎಲ್ಲವೂ ಕಡಿತಗೊಂಡಿದೆ.",
    "hero.stage3.title": "ವಿಘಟನೆಯಿಂದ<br/>ರಚನೆಯವರೆಗೆ",
    "hero.stage3.subtext": "ಎಲ್ಲವೂ ಒಟ್ಟಾಗಿ ಕೆಲಸ ಮಾಡಿದರೆ ಏನಾಗುತ್ತದೆ?",
    "hero.stage4.title": "SETBIN ಪರಿಸರ ವ್ಯವಸ್ಥೆಯನ್ನು ಸಂಪರ್ಕಿಸುತ್ತದೆ",
    "hero.stage4.subtext": "ಬಿಡಿಭಾಗಗಳ ಸಂಗ್ರಹಣೆ<br/>ಸೇವಾ ಕಾರ್ಯಾಚರಣೆಗಳು<br/>ತಾಂತ್ರಿಕ ಬುದ್ಧಿವಂತಿಕೆ<br/>ಎಲ್ಲವೂ ಒಂದೇ ವೇದಿಕೆಯಲ್ಲಿ.",
    "hero.stage5.title": "ಸಂಪರ್ಕಿಸಿ. ನಿರ್ವಹಿಸಿ.",
    "hero.stage5.subtext": "ಆಧುನಿಕ ರಿಪೇರಿ ಉದ್ಯಮಕ್ಕಾಗಿ<br/>ಮೂಲಸೌಕರ್ಯ.",
    "hero.stage6.title": "SETBIN",
    "hero.stage6.subtext": "ಭಾರತದ ಸ್ಮಾರ್ಟ್‌ಫೋನ್ ಸೇವಾ ಉದ್ಯಮಕ್ಕೆ ಮೂಲಸೌಕರ್ಯ",
    "hero.stage7.title": "ಮೊಬೈಲ್ ಸೇವೆಯ ಭವಿಷ್ಯವನ್ನು ಸಬಲೀಕರಣಗೊಳಿಸುವುದು",
    "hero.stage7.btn": "ವೇದಿಕೆಯನ್ನು ಅನ್ವೇಷಿಸಿ",
    "platform.chip": "ವೇದಿಕೆ",
    "platform.title": "ಸೇವೆಯನ್ನು ಸಬಲೀಕರಣಗೊಳಿಸುವುದು",
    "platform.desc": "ಸ್ಮಾರ್ಟ್‌ಫೋನ್ ಸೇವಾ ಉದ್ಯಮಕ್ಕಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾದ ವೇದಿಕೆ.",
    "platform.pillar1.title": "SETBIN CONNECT",
    "platform.pillar1.subtitle": "ಪರಿಶೀಲಿಸಿದ ಬಿಡಿಭಾಗಗಳ ಮಾರುಕಟ್ಟೆ",
    "platform.pillar1.body": "ವಿಶ್ವಾಸಾರ್ಹ ಪೂರೈಕೆದಾರರೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಿ. ಸಂಪೂರ್ಣ ಪಾರದರ್ಶಕತೆಯೊಂದಿಗೆ ಅಸಲಿ ಭಾಗಗಳನ್ನು ವೇಗವಾಗಿ ಪಡೆಯಿರಿ.",
    "platform.pillar2.title": "SETBIN REPAIR",
    "platform.pillar2.subtitle": "ಸೇವಾ ಕೇಂದ್ರ ಕಾರ್ಯನಿರ್ವಹಣಾ ವ್ಯವಸ್ಥೆ",
    "platform.pillar2.body": "ಕೆಲಸಗಳನ್ನು ನಿರ್ವಹಿಸಿ, ರಿಪೇರಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ, ದಾಸ್ತಾನು ನಿಯಂತ್ರಿಸಿ ಮತ್ತು ನಿಮ್ಮ ಕೆಲಸದ ಹರಿವನ್ನು ಸುಗಮಗೊಳಿಸಿ.",
    "platform.pillar3.title": "SCHEMIC AI",
    "platform.pillar3.subtitle": "AI-ಚಾಲಿತ ರೋಗನಿರ್ಣಯ ಬುದ್ಧಿವಂತಿಕೆ",
    "platform.pillar3.body": "ಪ್ರಯೋಗ-ಮತ್ತು-ದೋಷ ರಿಪೇರಿಗಳ ಬದಲಿಗೆ ಸ್ಕೆಮ್ಯಾಟಿಕ್ ಲಾಜಿಕ್ ಬಳಸಿ ದೋಷಗಳನ್ನು ಗುರುತಿಸಿ.",
    "platform.viewMore": "ಇನ್ನಷ್ಟು ನೋಡಿ →",

    "pillars.chip": "ನಾವೀನ್ಯತೆಯ ಸ್ತಂಭಗಳು",
    "pillars.title": "ರಿಪೇರಿ ಭವಿಷ್ಯವನ್ನು <br/>ನಿರ್ಮಿಸುವುದು.",
    "pillars.desc": "ಪೂರೈಕೆ ಸರಪಳಿಗಳು, ಸೇವಾ ಕೇಂದ್ರಗಳು ಮತ್ತು AI ರೋಗನಿರ್ಣಯವನ್ನು ಒಂದು ವೇದಿಕೆಯಲ್ಲಿ ನಾವು ತರುತ್ತಿದ್ದೇವೆ.",
    "pillars.footer": "ಬೆಳವಣಿಗೆಗಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ • ಬುದ್ಧಿವಂತಿಕೆಯಿಂದ ಚಾಲಿತ • ತಜ್ಞರ ವಿಶ್ವಾಸ",
    "pillars.connect.subtitle": "ಪರಿಸರ ವ್ಯವಸ್ಥೆ",
    "pillars.repair.subtitle": "ಮೂಲಸೌಕರ್ಯ",
    "pillars.schemic.subtitle": "ಬುದ್ಧಿವಂತಿಕೆ",
    "connect.chip": "SETBIN CONNECT",
    "connect.title": "ಭಾರತದ B2B ನೆಟ್‌ವರ್ಕಿಂಗ್",
    "connect.desc": "ಭಾರತದ ಅತಿದೊಡ್ಡ ನೆಟ್‌ವರ್ಕ್‌ಗೆ ಸೇರಿ.",
    "connect.features.suppliers": "ನೇರ ಪೂರೈಕೆದಾರ ಪ್ರವೇಶ",
    "connect.features.tools": "ಸಾಧನ ಸಂಗ್ರಹಣೆ",
    "connect.features.wholesale": "ಸಗಟು ಬೆಲೆ",
    "connect.btn": "ನೆಟ್‌ವರ್ಕ್‌ಗೆ ಸೇರಿ",

    "connect.story.chip": "SETBIN CONNECT",
    "connect.story.s1.title": "ಮೊಬೈಲ್ ಸೇವೆಗಾಗಿ ಭಾರತದ B2B ನೆಟ್‌ವರ್ಕ್",
    "connect.story.s1.desc": "ತಂತ್ರಜ್ಞರು, ಸೇವಾ ಕೇಂದ್ರಗಳು ಮತ್ತು ಬಿಡಿಭಾಗಗಳ ಪೂರೈಕೆದಾರರನ್ನು ಒಂದೇ ರಚನಾತ್ಮಕ ಪರಿಸರ ವ್ಯವಸ್ಥೆಯಲ್ಲಿ ಸಂಪರ್ಕಿಸುವ ಪರಿಶೀಲಿಸಿದ ವೇದಿಕೆ.",
    "connect.story.s2.tag": "ಹಳೆಯ ವಿಧಾನ",
    "connect.story.s2.title": "ಸೋರ್ಸಿಂಗ್ ಇನ್ನೂ ಹಸ್ತಚಾಲಿತ ಮತ್ತು ಅಸ್ತವ್ಯಸ್ತ",
    "connect.story.s2.p1": "ನಿಜ-ಸಮಯ ಲಭ್ಯತೆ ಇಲ್ಲ",
    "connect.story.s2.p2": "ಬೆಲೆ ಸ್ಪಷ್ಟತೆ ಇಲ್ಲ",
    "connect.story.s2.p3": "ನಕಲಿ ಭಾಗಗಳ ಹೆಚ್ಚಿನ ಅಪಾಯ",
    "connect.story.s2.p4": "ಅಂತ್ಯವಿಲ್ಲದ ಕರೆಗಳು ಮತ್ತು ಸಂದೇಶಗಳು",
    "connect.story.s3.tag": "ಪರಿಹಾರ",
    "connect.story.s3.title": "ಗೊಂದಲದಿಂದ ರಚನೆಗೆ",
    "connect.story.s3.desc": "ವಿಶ್ವಾಸಾರ್ಹ ಪೂರೈಕೆದಾರರಿಂದ ಪರಿಶೀಲಿಸಿದ ಭಾಗಗಳನ್ನು ಹುಡುಕಿ, ಹೋಲಿಸಿ ಮತ್ತು ತಕ್ಷಣ ಪಡೆದುಕೊಳ್ಳಿ.",
    "connect.story.s4.title": "ನೇರ ಪೂರೈಕೆದಾರ ಪ್ರವೇಶ",
    "connect.story.s4.desc": "ವಿಳಂಬ ಇಲ್ಲದೆ ಭಾರತ ಉದ್ದಕ್ಕೂ ಪರಿಶೀಲಿತ ಸಗಟು ವ್ಯಾಪಾರಿಗಳೊಂದಿಗೆ ನೇರವಾಗಿ ಸಂಪರ್ಕಿಸಿ. ಯಾವುದೇ ಮಧ್ಯವರ್ತಿಗಳಿಲ್ಲ.",
    "connect.story.s5.title": "ನಿಜ-ಸಮಯ ದಾಸ್ತಾನು",
    "connect.story.s5.desc": "ಆರ್ಡರ್ ಮಾಡುವ ಮೊದಲು ನಿಖರವಾಗಿ ಏನು ಲಭ್ಯವಿದೆ ಎಂದು ತಿಳಿಯಿರಿ. ಲೈವ್ ಸ್ಟಾಕ್ ಸೂಚಕಗಳು ಅನಿಶ್ಚಿತತೆಯನ್ನು ನಿವಾರಿಸುತ್ತವೆ.",
    "connect.story.s5.feed": "ಲೈವ್ ಸ್ಟಾಕ್ ಫೀಡ್",
    "connect.story.s5.stock": "ಸ್ಟಾಕ್‌ನಲ್ಲಿದೆ",
    "connect.story.s5.p1": "iPhone 13 Pro ಸ್ಕ್ರೀನ್",
    "connect.story.s5.p2": "Samsung S22 ಬ್ಯಾಟರಿ",
    "connect.story.s5.p3": "Type-C ಪೋರ್ಟ್ IC",
    "connect.story.s6.title": "ನಿಜವಾದ ಸಗಟು ಬೆಲೆ",
    "connect.story.s6.desc": "ತಕ್ಷಣ ಪಾರದರ್ಶಕ B2B ಬೆಲೆ ನಿರ್ಧಾರ ಪ್ರವೇಶಿಸಿ. ಪರಿಶೀಲಿತ ಪೂರೈಕೆದಾರರ ನಡುವೆ ದರಗಳನ್ನು ಹೋಲಿಸಿ.",
    "connect.story.s6.retail": "ಚಿಲ್ಲರೆ ಸರಾಸರಿ",
    "connect.story.s7.title": "ಪರಿಶೀಲಿಸಿದ ಅಸಲಿ ಭಾಗಗಳು",
    "connect.story.s7.desc": "ನಕಲಿ ಘಟಕಗಳ ಅಪಾಯ ಕಡಿಮೆ ಮಾಡಿ. ನಮ್ಮ ಪೂರೈಕೆದಾರ ನೆಟ್‌ವರ್ಕ್ OEM ಭಾಗಗಳನ್ನು ಖಾತ್ರಿಗೊಳಿಸಲು ಕಟ್ಟುನಿಟ್ಟಾಗಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ.",
    "connect.story.s8.title": "ಗಂಟೆಗಳಿಂದ ನಿಮಿಷಗಳಿಗೆ",
    "connect.story.s8.desc": "ಒಮ್ಮೆ ಗಂಟೆಗಟ್ಟಲೆ ಕರೆ ಮಾಡಬೇಕಿದ್ದ ಕೆಲಸ ಈಗ ಭಾರತದ ಪರಿಶೀಲಿತ ವೇದಿಕೆಯಲ್ಲಿ ಸೆಕೆಂಡುಗಳಲ್ಲಿ ಆಗುತ್ತದೆ.",
    "connect.story.s8.btn": "ಕನೆಕ್ಟ್ ಇಕೋಸಿಸ್ಟಮ್ ಅನ್ವೇಷಿಸಿ",

    // SaaS Showcase Rebrand
    "pro.showcase.heading": "ನಿಮ್ಮ ಇಡೀ ಸೇವಾ ವ್ಯವಹಾರವನ್ನು ಒಂದೇ ಸಿಸ್ಟಮ್‌ನಲ್ಲಿ ನಡೆಸಿ",
    "pro.showcase.subheading": "SETBIN REPAIR",
    "pro.showcase.desc": "ಜಾಬ್ ಇಂಟೇಕ್‌ನಿಂದ ಬಿಲ್ಲಿಂಗ್‌ವರೆಗೆ, ದಾಸ್ತಾನುಗಳಿಂದ ಆರ್ಥಿಕ ಟ್ರ್ಯಾಕಿಂಗ್‌ವರೆಗೆ — SETBIN ಮೊಬೈಲ್ ಸೇವಾ ಕೇಂದ್ರಗಳಿಗಾಗಿ ಪ್ರತಿ ಕಾರ್ಯಾಚರಣೆಯನ್ನು ಒಂದು ತಡೆರಹಿತ ವರ್ಕ್‌ಫ್ಲೋ ಆಗಿ ಏಕೀಕರಿಸುತ್ತದೆ.",
    "pro.showcase.cta.demo": "ಡೆಮೊ ಪಡೆಯಿರಿ",
    "pro.showcase.cta.free": "ಉಚಿತ ಪ್ರಯೋಗ ಪ್ರಾರಂಭಿಸಿ",
    "pro.showcase.nav.daybook": "ಡೇಬುಕ್",
    "pro.showcase.nav.billing": "ಬಿಲ್ಲಿಂಗ್",
    "pro.showcase.nav.inventory": "ದಾಸ್ತಾನು",
    "pro.showcase.nav.reports": "ವರದಿಗಳು",
    "pro.showcase.nav.dues": "ಬಾಕಿ",
    "pro.showcase.nav.exp": "ವೆಚ್ಚಗಳು",
    "pro.showcase.card.rev.title": "ಆದಾಯ",
    "pro.showcase.card.rev.amt": "$198.5M",
    "pro.showcase.card.due.title": "ಬಾಕಿ",
    "pro.showcase.card.due.amt": "$15.3M",
    "pro.showcase.card.rules.title": "ಸೇವಾ ನಿಯಮಗಳು",
    "pro.showcase.card.rules.r1": "ರೇಟಬಲ್",
    "pro.showcase.card.rules.r2": "ಸರಿಯಾದ ಸಮಯದಲ್ಲಿ",
    "pro.showcase.card.rules.r3": "ಅನುಪಾತದ",
    
    "pro.chip": "SETBIN REPAIR",
    "pro.title": "ವ್ಯವಹಾರವನ್ನು ಉನ್ನತೀಕರಿಸಿ",
    "pro.desc": "ರಿಪೇರಿ ಅಂಗಡಿಗಳಿಗೆ ಸಂಪೂರ್ಣ ನಿರ್ವಹಣೆ ಪೈಪ್‌ಲೈನ್.",
    "pro.features.repair": "ರಿಪೇರಿ ಟ್ರ್ಯಾಕಿಂಗ್",
    "pro.features.inventory": "ದಾಸ್ತಾನು ನಿರ್ವಹಣೆ",
    "pro.features.customer": "ಗ್ರಾಹಕ ಸಂವಹನ",
    "pro.btn": "ನಿರ್ವಹಣೆಯನ್ನು ಪ್ರಾರಂಭಿಸಿ",
    "ai.chip": "SCHEMIC AI",
    "ai.title": "ನೆಕ್ಸ್ಟ್-ಜೆನ್ ರೋಗನಿರ್ಣಯ",
    "ai.desc": "ದೋಷಗಳನ್ನು ಗುರುತಿಸಲು AI ಬಳಸಿ.",
    "ai.features.analysis": "ತತ್‌ಕ್ಷಣದ ವಿಶ್ಲೇಷಣೆ",
    "ai.features.faults": "ದೋಷಗಳನ್ನು ಗುರುತಿಸುವುದು",
    "ai.features.solutions": "ರಿಪೇರಿ ಪರಿಹಾರಗಳು",
    "ai.btn": "Schemic AI ಅನ್ನು ಪ್ರಯತ್ನಿಸಿ",
    "network.chip": "ರಾಷ್ಟ್ರೀಯ ನೆಟ್‌ವರ್ಕ್",
    "network.title": "ತಜ್ಞರಿಂದ ವಿಶ್ವಾಸಾರ್ಹ",
    "network.desc": "SETBIN ಅನ್ನು ನಂಬುವ ಸಾವಿರಾರು ವ್ಯವಹಾರಗಳಿಗೆ ಸೇರಿ.",
    "contact.chip": "ಸಂಪರ್ಕಿಸಿ",
    "contact.title": "ಒಟ್ಟಾಗಿ ಭವಿಷ್ಯವನ್ನು ನಿರ್ಮಿಸೋಣ",
    "contact.desc": "ವ್ಯವಹಾರವನ್ನು ಬದಲಾಯಿಸಲು ಸಿದ್ಧರಿದ್ದೀರಾ?",
    "contact.info.title": "ಸಂಪರ್ಕ ಮಾಹಿತಿ",
    "contact.info.email": "ಇಮೇಲ್ ಮಾಡಿ",
    "contact.info.phone": "ಕರೆ ಮಾಡಿ",
    "contact.info.address": "ನಮಗೆ ಭೇಟಿ ನೀಡಿ",
    "contact.form.name": "ಪೂರ್ಣ ಹೆಸರು",
    "contact.form.submit": "ಸಂದೇಶ ಕಳುಹಿಸಿ",
    "cta.title": "ಕ್ರಾಂತಿ ತರಲು ಸಿದ್ಧರಿದ್ದೀರಾ?",
    "cta.desc": "ವೃತ್ತಿಪರರೊಂದಿಗೆ ಸೇರಿ.",
    "cta.btn.start": "ಇಂದೇ ಪ್ರಾರಂಭಿಸಿ",
    "cta.btn.contact": "ಬಿಕ್ರಿ ಶಾಖೆಯನ್ನು ಸಂಪರ್ಕಿಸಿ"
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
